### ISSUE TITLE
Tooltip using another graph

### ISSUE THREAD

**Issue by acappelletti** [VolkovLabs/volkovlabs-echarts-panel#100]
Hi, I point out a function that I often use in Power Bi, that is, when I pass over a graph, instead of the tootip, I show another graph.. maybe a pie. I don't know if it is possible to do this already with eCharts. If it were possible and you can show me a sample I would greatly appreciate it.

Below is an example from my PBI

![image](https://user-images.githubusercontent.com/43847440/205857672-0ea4a6d5-b77b-4ef0-866e-ad2064f075db.png)

Alen

**Comment by mikhail-vl** [comment]
@acappelletti It may be possible. I am migrating Apache ECharts to our Grafana instance and will let you know if I find anything similar.

**Comment by mikhail-vl** [comment]
@acappelletti I have not seen Examples that demonstrated this kind of behavior.

  It may be possible to implement this using custom components, but it's out of the score of the plugin.
