### ISSUE TITLE
Control margins/padding in charts

### ISSUE THREAD

**Issue by evertoncolling** [VolkovLabs/volkovlabs-echarts-panel#104]
I haven't found a way to control the margins/padding of charts. For most cases, that's not needed, but in some scenarios my charts are not centered in the panel, as can be seen below:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/33816483/207003966-0f39fc06-d78f-418d-a5ca-6dd67edc24b1.png">

Sometimes the charts are also cropped (where parts of the visual elements are going beyond the panel margins), as can be seen below:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/33816483/207003303-c76af527-2bd5-4ace-9299-fcbbfc26870d.png">

I have been playing around with the `grid` option, but it does not seem to do anything when it comes to margins/padding tweaking. Is it something that could be done to allow users to properly center charts in Grafana panels and avoid cropping charts (with visual components hidden outside of the panel area)?

**Comment by mikhail-vl** [comment]
@evertoncolling In ECharts, various visualization use different options to control margins and padding:

```
  calendar: {
    top: 120,
    left: 30,
    right: 30,
    cellSize: ['auto', 13],
    range: '2016',
    itemStyle: {
      borderWidth: 0.5
    },
    yearLabel: { show: false }
  },
```

  We have not migrated Calendar to https://echarts.volkovlabs.io yet. Meanwhile, you can check it at https://echarts.apache.org/examples/en/index.html#chart-type-calendar. There is a cheat sheet for all visualization you can use to find the correct options: https://echarts.apache.org/en/cheat-sheet.html.

  Let me know if it works for you.

**Comment by mikhail-vl** [comment]
Same for Sankey:

```
   {
      type: 'sankey',
      left: '2%',
      top: '2%',
      right: 150,
}
```
![Screen Shot 2022-12-12 at 12 20 07](https://user-images.githubusercontent.com/47795110/207111291-50257f87-a470-4056-9ba4-1bacee079d2c.png)

**Comment by evertoncolling** [comment]
I was not aware of this way to manipulate the margins/padding. It works perfectly fine with both `Sankey` and `Calendar` charts. Thanks for the tip!

Ideally it would still be great if the charts would align to the center of the panel automagically, but I understand that this is a challenging endeavour (specially, if the positioning of the charts is controlled individually for each chart type).

Since it's possible to adjust padding/margins, I'm closing this issue.
