### ISSUE TITLE
Is it possible to search by dragging to the Apache ECharts Panel?

### ISSUE THREAD

**Issue by YoonSungHyun-inzent** [VolkovLabs/volkovlabs-echarts-panel#108]
Hello,

Is it possible to search for timestamps in Apache ECharts Panel by dragging in the graph area like Grafana?

Would it be possible to be above the graph rather than the search area at the bottom of the EChart?

like this 

https://github.com/apache/echarts/issues/13397

**Comment by uebenes** [comment]
That would be a nice feature regarding the usability, because normally you have Grafana widgets and eChart widgets in the same dashboard. It would be great, when they behave simelar.

**Comment by mikhail-vl** [comment]
@YoonSungHyun-inzent Thank you for opening the issue.

  As said in the provided issue, there is a workaround to enable data zoom by default without clicking on the toolbox. In the case of the Apache ECharts panel, it can be done using 1s timeout after chart initialization:

```js
setTimeout(() => echartsInstance.dispatchAction({
  type: 'takeGlobalCursor',
  key: 'dataZoomSelect',
  dataZoomSelectActive: true,
}), 1000);
```

  But the behavior is different for Data Zoom in ECharts and highlighting in Grafana. Data Zoom is performing zooming without changing the time range, TimeSeries panel in Grafana update time range. Which one do you expect to happen?

  Same question to @uebenes do you want to have a data zoom feature similar to Grafana? then it should update the time range in the dashboard.

  btw, you can experiment on our Apache ECharts grafana instance: https://echarts.volkovlabs.io/d/tg6gWiKVk/line?orgId=1&editPanel=38

**Comment by mikhail-vl** [comment]
@uebenes This is an example how to update Time Range in Grafana similar to native TimeSeries panel

```js
const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;

  return {
    name: s.refId,
    type: 'line',
    showSymbol: false,
    areaStyle: {
      opacity: 0.1,
    },
    lineStyle: {
      width: 1,
    },
    data: sData.map((d, i) => [sTime[i], d.toFixed(2)]),
  };
});

/**
 * Enable Data Zoom by default
 */
setTimeout(() => echartsInstance.dispatchAction({
  type: 'takeGlobalCursor',
  key: 'dataZoomSelect',
  dataZoomSelectActive: true,
}), 500);

/**
 * Update Time Range on Zoom
 */
echartsInstance.on('datazoom', function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  locationService.partial({ from: startValue, to: endValue });
});

return {
  backgroundColor: 'transparent',
  tooltip: {
    trigger: 'axis',
  },
  legend: {
    left: '0',
    bottom: '0',
    data: data.series.map((s) => s.refId),
    textStyle: {
      color: 'rgba(128, 128, 128, .9)',
    },
  },
  toolbox: {
    left: 'center',
    feature: {
      dataZoom: {
        yAxisIndex: 'none'
      },
      restore: {}
    }
  },
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value',
    min: 'dataMin',
  },
  grid: {
    left: '2%',
    right: '2%',
    top: '40',
    bottom: 24,
    containLabel: true,
  },
  series,
};
```

**Comment by mikhail-vl** [comment]
@YoonSungHyun-inzent We updated Documentation and updated the default line Chart with enabled Data Zoom to update Time Range: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/options#data-zoom-to-update-time-range

  Let us know if there is anything else.

**Comment by YoonSungHyun-inzent** [comment]
@mikhail-vl It seems to have added some very good features. I am so grateful. Thank you for your efforts.
