### ISSUE TITLE
Filter arrays from datasource

### ISSUE THREAD

**Issue by slindersAmsterdam** [VolkovLabs/volkovlabs-echarts-panel#109]
I can convert one-dimensional arrays into many-dimensional arrays (like the example at https://volkovlabs.io/plugins/volkovlabs-echarts-panel/datasources/ ) . The arrays are based on a table (as a result from a query), for example with 3 columns: year, valueX, valueY  
My query filters on country by using a variable in grafana. Now I have to rerun my query to filter the data to new table values if I change the variable to another country. This takes query calculationtime.

If I add the country column to my table, I only have to run my query ones. But then I have to filter in grafana/echarts on the variable (column) 'countries', is this possible?

**Comment by mikhail-vl** [comment]
@slindersAmsterdam ECharts's Function is a Javascript you can easily filter using `.filter` or `if` statements to show all countries.

   What kind of data source do you use? The question is if the data source will query data again if you update the variable, and it does not make any difference. Have you tried it?

  From Apache ECharts I would suggest doing something like that:
```
const var = replaceVariables("${var}");
const country = {};
const series = data.series.map((s) => {
  const countries = s.fields.find((f) => f.name === 'Country').values.buffer;
  const rates = s.fields.find((f) => f.name === 'Rate').values.buffer;
  const calls = s.fields.find((f) => f.name === 'Calls').values.buffer;
  const names = s.fields.find((f) => f.name === 'Name').values.buffer;

  return rates.map((d, i) => {
   country[countries[i]].push([d, calls[i], names[i]]);
   return [d, calls[i], names[i], countries[i]]);
  }
})[0];

console.log(country[var]);
```

  In the end, you should have a hash with all countries and an array of arrays for each country.
  Or you can filter by country in the returned `series[0]`.

  Let me know what you ended up with.

**Comment by slindersAmsterdam** [comment]
Thank for your quick reply. It's a mssql query on a local database. The variable won't influence the query. 
I'll try it out with .filter (haven't seen any examples yet in grafana/echarts? or maybe missed it).

Also thanks for the code. This is exactly what I was looking for (an array of arrays that I can filter).
But the code has a ) in the wrong place I think. I get an error when I paste it in grafana/echarts.

I have to try it out next year. Have a nice New Years Eve tomorrow.

**Comment by mikhail-vl** [comment]
@slindersAmsterdam Have you had a chance to try the code? Did it work for you?

  Here is the updated version of the code:

```
const v = replaceVariables("${var}");

const country = {};
const series = data.series.map((s) => {
  const countries = s.fields.find((f) => f.name === 'Country').values.buffer;
  const names = s.fields.find((f) => f.name === 'Name').values.buffer;
  const amounts = s.fields.find((f) => f.name === 'Amount').values.buffer;

  return amounts.map((d, i) => {
    country[countries[i]] = country[countries[i]] ?? []
    country[countries[i]].push([d, names[i]])

    return [d, names[i], countries[i]];
  })
})[0];

console.log(country[v]);

return {APACHE-ECHART-JSON}
```

  Let me know if there is anything else.

**Comment by slindersAmsterdam** [comment]
Yes Mikhail, this does the trick that I planned. Thanks very much 
But my plan does not speed up the process.

The variable [v] does not get used in the query, but the query still recalculates. 
(that's what you asked in the first place, but I thought that would be about if I used the variable within the query, which I do not).
Is there a way to have dedicated variables so the query wont start again?
