### ISSUE TITLE
Apache ECharts Grafana and Websocket API

### ISSUE THREAD

**Issue by myrulezzz** [VolkovLabs/volkovlabs-echarts-panel#110]
Hi, is it possible to render websocket data into an apache echart. Data are coming from grafana websocket plugin.
For example i have 2 columns.
category and count.
category has fixed 5 values.
I want to create a bar chart which updates with the latest counts of websocket incoming records

**Comment by mikhail-vl** [comment]
@myrulezzz That's interesting. I never tried it, and need to check how the panel behaves.

  Just to confirm, you are using https://grafana.com/grafana/plugins/golioth-websocket-datasource/?

**Comment by myrulezzz** [comment]
> @myrulezzz That's interesting. I never tried it, and need to check how the panel behaves.
> 
> 
> 
>   Just to confirm, you are using https://grafana.com/grafana/plugins/golioth-websocket-datasource/?

Hi.Yes exactly.And i have one column category which has 5 categories and then i have a column which is counting totals and sending to the websocket {category: categ1, totals:100}
i wanted to update the 5 gatecories with the new values that are coming from them websocket without needing to refresh the chart.with a dimple grafana table i am able to load websocket data without refresh.i was looking to to do the same with a chart

**Comment by mikhail-vl** [comment]
@myrulezzz We added Streaming support for streaming Data Source and Grafana Live. It will be available in the upcoming 4.1.0.

  Meanwhile, you can download the artifact from CI to test: https://github.com/VolkovLabs/volkovlabs-echarts-panel/actions/runs/3825904989.

  Initial Documentation: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/streaming/
  Please let me know if it works or have any questions.

**Comment by myrulezzz** [comment]
@mikhail-vl Tested. Working perfect. Thanks

**Comment by mikhail-vl** [comment]
@myrulezzz Thank you for confirming.

  Let us know if there is anything else.

**Comment by myrulezzz** [comment]
I have one more wuestion.I jave a neo4j graph and i can import the graph in grafana with neo4j connector.Is it possible to visualize the graph with any of the available graphs from apache echart?

**Comment by mikhail-vl** [comment]
@myrulezzz We created two parts YouTube tutorial on how to create graphs from Postgres, which should be similar to the data returned from Neo4J: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/tutorials/graph

  Here are Examples to start with: https://echarts.volkovlabs.io/d/oKc5di54k/graph?orgId=1

**Comment by mikhail-vl** [comment]
@myrulezzz It may be challenging because we can't predict what was changed and what kind of data arrived.

  You are welcome to submit PR if you make it work.

**Comment by myrulezzz** [comment]
@mikhail-vl 
I was trying the chart Aggregate Scatter to bar:
Here is my code:


let purple205Values = [];
let cr261Values = [];
data.series.map((s) => {
  if (s.refId === "PURPLE205") {
    let retailvalue = s.fields.find((f) => f.name === 'RetailValue').values.buffer;
    let adjvalue = s.fields.find((f) => f.name === 'AdjValue').values.buffer;
    purple205Values.push([retailvalue, adjvalue]);
  } else if (s.refId === "CR-261") {
    let retailvalue = s.fields.find((f) => f.name === 'Retail1').values.buffer;
    let adjvalue = s.fields.find((f) => f.name === 'Adjust1').values.buffer;
    cr261Values.push([retailvalue, adjvalue]);
  }
});

let purplestring = purple205Values.map((val) => `[${val[0]}, ${val[1]}]`).join(',');
let cr261string = cr261Values.map((val) => `[${val[0]}, ${val[1]}]`).join(',');





function calculateAverage(data, dim) {
  let total = 0;
  for (var i = 0; i < data.length; i++) {
    total += data[i][dim];
  }
  return (total /= data.length);
}
const scatterOption = (option = {
  xAxis: {
    scale: true
  },
  yAxis: {
    scale: true
  },
  series: [
    {
      type: 'scatter',
      id: 'purple205',
      dataGroupId: 'purple205',
      universalTransition: {
        enabled: true,
        delay: function (idx, count) {
          return Math.random() * 400;
        }
      },
      data: purplestring
    },
    {
      type: 'scatter',
      id: 'cr261',
      dataGroupId: 'cr261',
      universalTransition: {
        enabled: true,
        delay: function (idx, count) {
          return Math.random() * 400;
        }
      },
      data: cr261string
    }
  ]
});
const barOption = {
  xAxis: {
    type: 'category',
    data: ['PURPLE-205', 'CR-261']
  },
  yAxis: {},
  series: [
    {
      type: 'bar',
      id: 'total',
      data: [
        {
          value: calculateAverage(purplestring, 0),
          groupId: 'purple205'
        },
        {
          value: calculateAverage(cr261string, 0),
          groupId: 'cr261'
        }
      ],
      universalTransition: {
        enabled: true,
        seriesKey: ['purple205', 'cr261'],
        delay: function (idx, count) {
          return Math.random() * 400;
        }
      }
    }
  ]
};
let currentOption = scatterOption;
setInterval(function () {
  currentOption = currentOption === scatterOption ? barOption : scatterOption;
  myChart.setOption(currentOption, true);
}, 2000);

However i receive error 
TypeError: Cannot read properties of undefined (reading 'baseOption')
    at eval (http://etltool2:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:1311101)
    at t.setOption (http://etltool2:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:1311521)
    at e.setOption (http://etltool2:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:1303241)
    at e.setOption (http://etltool2:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:1411352)
    at eval (http://etltool2:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:2773573)
    at Du (http://etltool2:3000/public/build/9512.8fae0c667bb767d8cfd1.js:2:846990)
    at t.unstable_runWithPriority (http://etltool2:3000/public/build/9512.8fae0c667bb767d8cfd1.js:2:2751113)
    at Ho (http://etltool2:3000/public/build/9512.8fae0c667bb767d8cfd1.js:2:787640)
    at Ru (http://etltool2:3000/public/build/9512.8fae0c667bb767d8cfd1.js:2:846453)
    at vu (http://etltool2:3000/public/build/9512.8fae0c667bb767d8cfd1.js:2:837981)
Any clue what could be the problem?

**Comment by myrulezzz** [comment]
@mikhail-vl  Here is the error from the dev tool
VM167:99 Uncaught ReferenceError: myChart is not defined
    at eval (eval at <anonymous> (module.js:1:1), <anonymous>:99:3)
eval @ VM167:99

**Comment by mikhail-vl** [comment]
@myrulezzz `myChart` should be updated to `echartsInstance` as described in the Documentation, https://volkovlabs.io/plugins/volkovlabs-echarts-panel/options.

  Some Apache ECharts are more challenging than others and require updating before using in Grafana, this was the reason for us to create https://echarts.volkovlabs.io/d/pL5iH7FVk/home?orgId=1, which has 100+ examples.

  Let me know if there is anything else.
