### ISSUE TITLE
Cannot install plugin in Grafana 9.0.5 or 9.2.1

### ISSUE THREAD

**Issue by Jopinc** [VolkovLabs/volkovlabs-echarts-panel#114]
Hi! 
I am facing some issue to install the echart plugin. I donwoladed the ZIP file from grafana repository and extracted it into grafana path. Then I restarted grafana service and I can see the echart plugin in Grafana, but when I want to create a new panel and select the plugin, Grafana show me the following error message:

Error loading: volkovlabs-echarts-panel

The name of the ZIP from Grafana repository is: volkovlabs-echarts-panel-4.0.0.zip

Some suggestion to solve this issue?

BR
Jorge

**Comment by mikhail-vl** [comment]
@Jopinc, do you see any errors in the Browser Console?

  Are you working in a closed environment without Internet access?

**Comment by mikhail-vl** [comment]
@Jopinc, I have tried multiple Docker containers for Grafana 9.2.1, 9.0.5, without Internet access.

  Everything works as expected. And we have not heard about similar issues since we release 4.0.0, which was tested by the Grafana team.

  Do you use Grafana in Docker or Host installation? Maybe it was not fully upgraded?

  Apache ECharts supports Grafana 8.5+, and it should not have any issues with any 9.X.

**Comment by Jopinc** [comment]
@mikhail-vl Thank you for testing. It is a host installation in a Windows VM.

I will install again Grafana. Could you please share me the ZIP File that you used for test? Just in case.

Thanks.

**Comment by mikhail-vl** [comment]
@Jopinc, you can download the latest versions directly from the GitHub repository: https://github.com/VolkovLabs/volkovlabs-echarts-panel/releases.

  Grafana Catalog has the latest release 4.0.0, which is exactly the same as the file in the repository. You can try one of the latest dev builds with streaming support from CI.

  A simple test will be to install Docker on Windows VM and try from there.

**Comment by Jopinc** [comment]
Thank you @mikhail-vl for your support. I will try to fix it and let you know.

**Comment by Jopinc** [comment]
@mikhail-vl Please take a look to this test (just add some additional test):

Grafana version:
![image](https://user-images.githubusercontent.com/57772247/210428334-f0fac63a-22ec-4ee7-bfdf-ea9be8553d3a.png)


First, I connect VM to internet throught a proxy. Then, i test the following http request for "Text" plugin
"https://grafana.com/api/plugins/text"

I got a correct api answer (![image](https://user-images.githubusercontent.com/57772247/210426384-b698e2d6-d3cd-469f-8fa9-62119aa81337.png)

But when I do the same with "volkovlabs-echarts-panel" I got this (
![image](https://user-images.githubusercontent.com/57772247/210426547-f62aaf4b-5d1d-46f6-9014-28e395ae76d1.png)

I will install again grafana.

**Comment by mikhail-vl** [comment]
@Jopinc What do you see in the API output?

```
GET https://GRAFANA-INSTANCE/api/health
```

Should be similar to 

```
{
  "commit": "21c1d14e91",
  "database": "ok",
  "version": "9.3.2"
}
```

**Comment by Jopinc** [comment]
@mikhail-vl Yes. 

![image](https://user-images.githubusercontent.com/57772247/210433327-0d7944c8-b117-444b-8dd5-fc2cc4798246.png)

**Comment by mikhail-vl** [comment]
@Jopinc Ok, that looks good then.

  I don't really understand what you are trying to do by browsing to `grafana.com/api/plugins/repo/volkovlabs-echarts-panels`. I believe it's related to your Grafana Cloud instance and not your local.

**Comment by Jopinc** [comment]
@mikhail-vl Take a look on this:

when I execute CLI command to download the plugin (Because the local ZIP doesnt work):
grafana-cli plugins install volkovlabs-echarts-panel

The output of the command is:
![image](https://user-images.githubusercontent.com/57772247/210434250-a83c3e97-ed7e-4555-b7e5-cce98e5277bf.png)

As you can see, the command do a GET to the URL: https://grafana.com/api/plugins/repo/volkovlabs-echarts-panel

So, if you try to do GET to thist URL (Without "/repo/" folder): https://grafana.com/api/plugins/volkovlabs-echarts-panel
I received a correct answer. 

Am i doing something wrong?

**Comment by Jopinc** [comment]
Finally I install Grafana 9.3.1 and I get the same result. 

In the Grafana Plugins Menu, I see the plugin:
![image](https://user-images.githubusercontent.com/57772247/210442281-77083a1c-1cb5-41e7-8cb3-c8e42e38f955.png)

![image](https://user-images.githubusercontent.com/57772247/210442671-32c35327-8007-49c5-8747-285ed1d168aa.png)


But when i create a new dashboard and add a new panel, I get this error:

![image](https://user-images.githubusercontent.com/57772247/210442748-f82338dd-4872-4886-b181-13e45a1c0de6.png)

Please help me to check if the plugin folder content is correct
![image](https://user-images.githubusercontent.com/57772247/210442915-99e0919e-7dc6-48cc-a0bf-6a903ec22106.png)

**Comment by mikhail-vl** [comment]
@Jopinc I just did a clean Windows installation test on Google Cloud, and the panel works as expected. To rule out any Windows-related issues, it's not a platform we use for development.

  Regarding "https://grafana.com/api/plugins/repo/volkovlabs-echarts-panel" the `grafana-cli` is doing a special request, which we explained in one of our blog posts about Private Repository. Your main issue is that because of the closed environment, your connection is blocked by the firewall. This is why you see `Timeout` issues. Your only option is to download the zip file.

  I have not tested Apache ECharts without the Internet, and I will do a couple more tests on my Linux with cables disconnected.

**Comment by Jopinc** [comment]
@mikhail-vl I tried it in my local laptop (Windows 10). I installed Grafana 9.3.1

I ran CLI command to install the plugin: C:\Program Files\GrafanaLabs\grafana\bin>grafana-cli plugins install volkovlabs-echarts-panel

This is the output:
![image](https://user-images.githubusercontent.com/57772247/210457042-3fade4f1-5b9d-4b0b-9c32-38d0689f2eef.png)

As you can see, there was not a timeout responde and the plugin was installed correctly. BUT, if you see the PATH where the command unzip the plugin it is different from grafana default. However I restarted Grafana and finally it work fine!! 

![image](https://user-images.githubusercontent.com/57772247/210458235-90806c8a-e976-4455-8465-a8378f7a27ce.png)

So, i decided to copy the folder and pasted it into Windows VM and finally work fine too. There was a thing that I caught my attention. In this case the Plugin was detected as "Signed" (See the image below)

![image](https://user-images.githubusercontent.com/57772247/210458623-33b1a3bf-1505-430f-a6a1-a57fe677a721.png)

Before this test, the plugin was detected as "Core"

All is very extrange!! :) :)

**Comment by mikhail-vl** [comment]
@Jopinc I am thinking that the files got corrupted when unpacking.

  Plugin's definition is set in the `plugin.json`. If the plugin was detected at "Core", this file got corrupted.
  Good luck coding with Apache ECharts.
