### ISSUE TITLE
Grafana Dashboard Refresh Causes Loss of Toolips and Legend

### ISSUE THREAD

**Issue by Barryetter** [VolkovLabs/volkovlabs-echarts-panel#120]
I have a Dashboard that is set to auto-refresh every few seconds, and an ECharts panel showing basically the "beef map" example - an SVG with colored regions and a slider legend at the bottom to filter by price range using visualMap.

If I change the "Price" slider while in view mode, it gets reset when Grafana refreshes the dashboard. Is there a way to avoid this, while still allowing dashboard auto-refresh?

**Comment by mikhail-vl** [comment]
@Barryetter Are you looking to refresh the panel and preserve a slider value? Then you should use dashboard variables to keep the value when updating: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/variables

  Or do you want to update the whole dashboard and prevent updating the ECharts panel?

**Comment by mikhail-vl** [comment]
@Barryetter In case of the 2nd, we can add an option to prevent updating the panel on the `data` object, then you have to work with data source directly.

**Comment by Barryetter** [comment]
Hello, Mikhail. Thanks for the reply. For the first suggestion, dashboard variables, do you mean something like this pseudo-code?
grab slider value
set dashboard variable to slider's value
do update of data
set slider value back to dashboard variable value
If so, 
1. How do I get the slider value?
2. Where should this code be executed?

Thanks again for the great plugins, and quick responses.

**Comment by mikhail-vl** [comment]
@Barryetter You are correct.

1. Sliders and any other elements generate Events, which can be handled: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events

2. Dashboard variable can be updated using `locationService`, we need to update the documentation for ECharts like

```js
locationService.partial({ 'var-name': value }, true);
```

3. Variable should be used in the Apache ECharts code: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/variables

It will be similar to the Data Zoom to update Time Range, which we recently added: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events#data-zoom-to-update-time-range

  Please let me know if it's clear. We explained many Apache ECharts concepts in the YouTube tutorials: https://www.youtube.com/@volkovlabs/videos

**Comment by mikhail-vl** [comment]
I updated documentation on how to update Dashboard Variables: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/variables/#update-dashboard-variables.

**Comment by mikhail-vl** [comment]
@Barryetter It's tricky :) You need to keep the `var-` in front.

```js
locationService.partial({ 'var-datarangeStart': 3 }, true);
```

**Comment by Barryetter** [comment]
Got it. It's working now. Thank you very much.

**Comment by mikhail-vl** [comment]
@Barryetter Great to hear! You are welcome to share your final code to include in the documentation if possible.

**Comment by Barryetter** [comment]
Good idea. So, for future reference, to save the visualMap range slider settings across Dashboard refreshes:

1. Create two dashboard variables (Constants are fine, and they should be hidden from the user). I named them datarangeStart and datarangeEnd, and set them to some initial values.
2. In the EChart panel code editor (before the return), add an event handler for the **datarangeselected** event. Note that you have to first remove any event handler because the refresh will create duplicate handlers if you don't.

`echartsInstance.off('datarangeselected');`
`echartsInstance.on('datarangeselected', function (params) {`
`  const startValue = params.selected[0];`
`  const endValue = params.selected[1];`
`  locationService.partial({ 'var-datarangeStart': startValue, 'var-datarangeEnd': endValue }, true);`
`});`

3. In the visualMap definition, set the **range** property to the Dashboard variables using the **replaceVariables** method:

`visualMap: [{`
`    type: 'continuous',`
`    left: 'center',`
`    bottom: '0%',`
`    min: 0,`
`    max: 30,`
**`    range: [replaceVariables('$datarangeStart'), replaceVariables('$datarangeEnd')],`**
`    orient: 'horizontal',`
`    text: ['', 'Occupancy'],`
`    realtime: true,`
`    calculable: true,`
`    dimension: 0,`
`    inRange: {`
`      color: ['#ffffff', '#0000ff', '#ffff00', '#ff00ff']`
`    }`
`  }`

**Comment by mikhail-vl** [comment]
@Barryetter Appreciate it. I will include this in the Documentation and publish a blog post with this and other examples from the community later this week: https://github.com/VolkovLabs/volkovlabs.io/pull/185
