### ISSUE TITLE
Google Maps ECharts

### ISSUE THREAD

**Issue by myrulezzz** [VolkovLabs/volkovlabs-echarts-panel#123]
@mikhail-vl I am trying to change the color of dots on google map and they are not changing color let lng = [];
let lat = [];

data.series.map((s) => {
  lng = s.fields.find((f) => f.name === 'lon').values.buffer;
  lat = s.fields.find((f) => f.name === 'lat').values.buffer;
});

let pairs = [];

for (let i = 0; i < lng.length; i++) {
  let pair = { lng: lng[i], lat: lat[i] };
  pairs.push(pair);
}

let result = pairs.join(',');

const gmap = {
  gmap: {
    /**
     * Center and Zoom
     */
    center: { lng: 35.166406, lat: 33.347922 },
    zoom: 7,

    // whether echarts layer should be rendered when the map is moving. `true` by default.
    // if false, it will only be re-rendered after the map `moveend`.
    // It's better to set this option to false if data is large.
    renderOnMoving: true,
  },
  series: [
    {
      type: 'scatter',
      coordinateSystem: 'gmap',
      // data items [[lng, lat, value], [lng, lat, value], ...]
      data: pairs.map(pair => [pair.lng, pair.lat]),
      //encode: {
      // encode the third element of data item as the `value` dimension
      //  value: 2,
      //  lng: 0,
      //  lat: 1
      // }
    }
  ]
};

/**
 * Loading
 */
const loading = {
  graphic: {
    elements: [
      {
        type: 'group',
        left: 'center',
        top: 'center',
        children: new Array(7).fill(0).map((val, i) => ({
          type: 'rect',
          x: i * 20,
          shape: {
            x: 0,
            y: -40,
            width: 10,
            height: 80
          },
          style: {
            fill: '#5470c6'
          },
          keyframeAnimation: {
            duration: 1000,
            delay: i * 200,
            loop: true,
            keyframes: [
              {
                percent: 0.5,
                scaleY: 0.3,
                easing: 'cubicIn'
              },
              {
                percent: 1,
                scaleY: 1,
                easing: 'cubicOut'
              }
            ]
          }
        }))
      }
    ]
  }
}

/**
 * Maps are Ready
 */
window.gmapReady = () => {
  notifySuccess(['Google Maps', 'Loaded...']);
  echartsInstance.setOption(gmap, notmerge = true);
}

return typeof google === 'object' && typeof google.maps === 'object' ? gmap : loading;
I am changing the style fill. Am i changing the correct parameter. Also what other options are available? Do you have any documentation? How to add labels on markers. Thanks

**Comment by mikhail-vl** [comment]
@myrulezzz Take a look at the example in the GitHub repository for the extension: https://github.com/plainheart/echarts-extension-gmap

- [Scatter](https://github.com/plainheart/echarts-extension-gmap/tree/master/examples/scatter.html)
- [Lines](https://github.com/plainheart/echarts-extension-gmap/tree/master/examples/lines.html)
- [Heatmap](https://github.com/plainheart/echarts-extension-gmap/tree/master/examples/heatmap.html)
- [Pie](https://github.com/plainheart/echarts-extension-gmap/tree/master/examples/pie.html)

**Comment by myrulezzz** [comment]
Thanks @mikhail-vl I ll have a look.

**Comment by mikhail-vl** [comment]
@myrulezzz Let me know and post a solution if you find it.

**Comment by myrulezzz** [comment]
in series component label: {
        formatter: '{c}',
        position: 'right',
        show: false
      },
      itemStyle: {
        color: '#de00cf', did the trick Thanks

**Comment by mikhail-vl** [comment]
@myrulezzz Awesome, thank you for sharing.

  Formatting is powerful in ECharts.
