### ISSUE TITLE
External npm packages

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#124]
Hello

Does the grafana plugin allow for bringing in external npm plugins? 

Thanks

**Comment by mikhail-vl** [comment]
@yosiasz Do you have a specific plugin in your mind? The library has to be compiled and loaded with the plugin to use.

  Apache ECharts panel already included the most popular extension, and we can add more if required.

**Comment by yosiasz** [comment]
Gotcha, I was just asking in general. There was a question on grafana about FFT and that got my wheels spinning. Thanks

**Comment by yosiasz** [comment]
https://community.grafana.com/t/how-to-add-custom-transformation/79963

**Comment by mikhail-vl** [comment]
@yosiasz It should be possible, and I replied as well.

  Thank you.
