### ISSUE TITLE
How to use shared crosshair

### ISSUE THREAD

**Issue by selvavm** [VolkovLabs/volkovlabs-echarts-panel#125]
Hi,

First of all, thanks for the great plugin. 

I have N panels (repeating panel) in my dashboard and they are line charts. I want to enable shared crosshair, so when my user hover on one panel, he can see the tooltip on all the panels. 

How can I achieve this?

**Comment by mikhail-vl** [comment]
@selvavm Thank you. It's a good question and should be done using Events Handling: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events

  Unfortunately, I don't know the specifics of how shared crosshair is implemented.
  Please share if you make it work.

**Comment by selvavm** [comment]
thanks for the response, @mikhail-vl 

I am new to JS, echart and Grafana. Hence, took some time to explore. 

I found how to use events to show the tooltip in all the charts as per this [stackoverflow link](https://stackoverflow.com/questions/70471817/show-tooltips-onhover-for-all-the-charts-at-same-date), however, I am having trouble using this example in Grafana.

How can I get the handle of other echart panels (in the example link, the `myChart2` variable)? 

Note: Not sure if this is useful, but I am using repeating panel feature in Grafana

**Comment by selvavm** [comment]
Hi @mikhail-vl 

Nevermind, I found it. I added below two lines in my panel and then all are connected. So, when I zoom in one panel, all panels zoom. Likewise, when I hover in one panel all are showing tooltip.

**Comment by mikhail-vl** [comment]
@selvavm Could you please clarify what did you do to update documentation?
  You added those two lines or there was something else?

```
echartsInstance.on('mouseover', (params) => {
  var event = params.event;
  echartsInstance.on.dispatchAction({
    type: 'showTip',
    x: event.offsetX,
    y: event.offsetY,
  });
});

echartsInstance.on('globalout', (params) => {
  echartsInstance.on.dispatchAction({
    type: 'hideTip'
  });
});
```

**Comment by briha** [comment]
This doesn't seem to work, @mikhail-vl (on the newest grafana version). The events fire properly, but the crosshair doesn't show. How to fix this (and make it bi-directional)? And where, in general, do I find a list of the available 'dispatchAction' values and the parameters they take?

**Comment by mikhail-vl** [comment]
@briha Please open a new issue to investigate.
