### ISSUE TITLE
Can you please support installing packages?

### ISSUE THREAD

**Issue by selvavm** [VolkovLabs/volkovlabs-echarts-panel#126]
Hi,

I see that this plugin is really awesome for bringing lot of visualisation to Grafana. However, in my usecase, we need to install existing packages to do complex transformations. 

Can you support this?

I came across [live-plugin-manager](https://www.npmjs.com/package/live-plugin-manager) which has support to install packages and use them. Can this be supported?

This way, I can avoid deployment challenges. 

I also feel this will be a common usecase as Grafana don't allow custom transformation.

**Comment by mikhail-vl** [comment]
@selvavm It's not supported in Grafana. All plugins are compiled and signed to avoid modifications.

  Also, from a security point of view, it's not recommended.
