### ISSUE TITLE
Multiple Metrics not showing for Line Chart Panels with Apache ECharts Grafana

### ISSUE THREAD

**Issue by viralui** [VolkovLabs/volkovlabs-echarts-panel#127]
![image](https://user-images.githubusercontent.com/95187171/214224949-23a9a1b1-16bd-4a60-a926-64f28cd71d72.png) --with Time Series Panel Grafana - Working Fine, Showing A & C

![image](https://user-images.githubusercontent.com/95187171/214225168-0d55b332-2eaf-4af6-bb4c-9e4e44956931.png) -- with Apache ECharts Grafana Only Showing A.

Need to use same query only.

Apache ECharts Default Grafana JS - const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;

  return {
    name: s.refId,
    type: 'line',
    showSymbol: false,
    areaStyle: {
      opacity: 0.1,
    },
    lineStyle: {
      width: 1,
    },
    data: sData.map((d, i) => [sTime[i], d]),
  };
});

/**
 * Enable Data Zoom by default
 */
setTimeout(() => echartsInstance.dispatchAction({
  type: 'takeGlobalCursor',
  key: 'dataZoomSelect',
  dataZoomSelectActive: true,
}), 500);

/**
 * Update Time Range on Zoom
 */
echartsInstance.on('datazoom', function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  locationService.partial({ from: startValue, to: endValue });
});

return {
  backgroundColor: 'transparent',
  tooltip: {
    trigger: 'axis',
  },
  legend: {
    left: '0',
    bottom: '0',
    data: data.series.map((s) => s.refId),
    textStyle: {
      color: 'rgba(128, 128, 128, .9)',
    },
  },
  toolbox: {
    feature: {
      dataZoom: {
        yAxisIndex: 'none',
        icon: {
          zoom: 'path://',
          back: 'path://',
        },
      },
      saveAsImage: {},
    }
  },
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value',
    min: 'dataMin',
  },
  grid: {
    left: '2%',
    right: '2%',
    top: '2%',
    bottom: 24,
    containLabel: true,
  },
  series,
};

----Please Help

**Comment by viralui** [comment]
How to add multiple metrics dynamically to Apache ECharts Line Chart. With the default coding ( when we add Apache Echarts to Grafana) as mentioned above, with one metrics, it's working fine but when it's loading more than 1 metrics, it's showing the first metrics only

**Comment by viralui** [comment]
I need to know how to fetch the metrics and its value dynamically, and put it with Apache Echarts Line Chart

**Comment by viralui** [comment]
Please update

**Comment by mikhail-vl** [comment]
@viralui You will need to modify the `data.series.map` function to retrieve more than 1 metric, which is the first field with `number` type in the default coding.

  Take a look at https://volkovlabs.io/plugins/volkovlabs-echarts-panel/datasources/, it has example and YouTube video explaining how to do it.

  Let me know if it's clear.

**Comment by viralui** [comment]
@mikhail-vl , Nope, it's not clear to me on how to tweak data.series.map function to retrieve metric of type number, dynamically

**Comment by mikhail-vl** [comment]
@viralui If you have multiple queries, like in the screenshot. They should be displayed out of the box with default function.

![Screen Shot 2023-04-17 at 11 44 50](https://user-images.githubusercontent.com/47795110/232539664-49f81190-d034-4408-b161-6d40aa37c7ec.png)
