### ISSUE TITLE
query cache valid 'til panel

### ISSUE THREAD

**Issue by acappelletti** [VolkovLabs/volkovlabs-echarts-panel#128]
Hi...
Hello, I would like to give you an idea for a panel...
For example… I set 1h cache in one panel query… but I can't know how long this will be valid exactly

I would like to have a plug for display the end of cache like a label (data valid 'til hh:mm) related to a query/panel.

Is it possible?

Alen

**Comment by mikhail-vl** [comment]
@acappelletti Thank you for the idea. What kind of data source you are looking for?

  I checked the `data` and it has `data.request.cacheTimeout`, but it's `undefined` for the JSON API datasource, which seems to be more a cache on a frontend side.
  The same time `data.request.targets[0]` has `cacheDurationSeconds` which you specify for the cache, but I don't see a property when it's expired. I have to look at the Grafana source code if it's possible to get it from the panel.

**Comment by acappelletti** [comment]
Hi @mikhail-vl, I'm using google sheet data source and the query can be cached... but I've half resolved inserting a now() in a column in the sheet, In this way I know always the data freshness... 'cause I saw also that when time goes over (5' cache)... seems that isn't always a refresh.. I tested on my page... remain the same also over time... it seems to understand that originally, although it exceeded the maximum cache time, since it is not a change it keeps the data present.

It's a little confusing the time picker, the overwrite the time picker directly nella query and also the cache... it's not always clear, also for the business managers usage, the really time connection on the page/panel.

ALEN

**Comment by mikhail-vl** [comment]
@acappelletti Looks like you have your workaround with returning `now()`.

  I believe it's out of the scope of the panel plugins and something which should be done in the data source.
  Closing.
