### ISSUE TITLE
how can we add json to google map?

### ISSUE THREAD

**Issue by alpglide** [VolkovLabs/volkovlabs-echarts-panel#129]
I want to add json( lots of polygons transfered from kml file) to google map, and make the polygons clickable. 
just like use this (https://echarts.volkovlabs.io/d/X1mkMIFVz/geo-map?orgId=1&editPanel=13) as background  and this  (https://echarts.volkovlabs.io/d/X1mkMIFVz/geo-map?orgId=1&editPanel=10) as interactive layer.
Any example for this kind of application? 
Thanks

**Comment by alpglide** [comment]
I may ask this way:
Can we get the gmap instance? if yes, we can add GeoJSON like this:
https://developers.google.com/maps/documentation/javascript/examples/layer-data-simple

I tried to get gmap instance like this, but failed:

window.gmapReady = () => { 
  echartsInstance.setOption(gmap, notmerge = true);
  const gmapComponent =echartsInstance.getModel().getComponent('gmap');
  const gmapInstance = gmapComponent.getGMap();
  gmapInstance.data.loadGeoJson(
    "https://storage.googleapis.com/mapsdevsite/json/google.json"
  );

**Comment by mikhail-vl** [comment]
@alpglide I don't think that you can mix GeoJSON and Google Maps. Apache ECharts provides capabilities to visualize lines, polygons, etc. using map's coordinates. You can find examples on the official site: https://echarts.apache.org/examples/en/index.html#chart-type-map

  I hope it helps.

**Comment by mikhail-vl** [comment]
Let me know if anything else is required.
