### ISSUE TITLE
Tooltip are blocked by panel, how to adjust it?

### ISSUE THREAD

**Issue by IBUMBLEBEE** [VolkovLabs/volkovlabs-echarts-panel#130]
![7c634ed8e3cd0f5c6aedce5bfebc1d4](https://user-images.githubusercontent.com/16176000/216544303-4d861ff7-71fb-4c80-a86b-59207c7afade.png)

https://echarts.volkovlabs.io/d/X1mkMIFVz/geo-map?orgId=1&editPanel=11

**Comment by mikhail-vl** [comment]
@IBUMBLEBEE Tooltip are fully customizable: https://echarts.apache.org/en/option.html#tooltip

  Let me know if it helps.

**Comment by IBUMBLEBEE** [comment]
I'm new to eChart, but I'm going to try it, thank you for your reply.

**Comment by mikhail-vl** [comment]
@IBUMBLEBEE We produced multiple YouTube tutorials for the ECharts, which helps with the learning curve.

  We used the GeoJSON maps in our latest project for Website Analytics and will cover it in the upcoming tutorial. I will ask to include tooltip customization.
