### ISSUE TITLE
Chart does not always refresh properly after a mouse-wheel-zoom or mouse-drag-zoom operation

### ISSUE THREAD

**Issue by Lroy** [VolkovLabs/volkovlabs-echarts-panel#133]
When using the mouse wheel to zoom, or when using the mouse to drag-zoom over a subset of the chart plots, the chart will sometimes fail to remove older traces.  A new set of traces will appear, while the previous traces are still be displayed.

Moving the mouse to cause a hover event will frequently clear the older "ghost" traces from the chart.

The ghosting does not appear to occur when the charts renderer is set to 'SVG'.

I have attached a dashboard that uses the echarts plugin and the grafana data source (random walk series) (Change file extension from .txt to .json).

Reproduce the issue:
1. Set the echarts renderer to 'Canvas'
2. Set the time scale to 12 hours
3. Use the mouse to drag-zoom a subset of the data
4. The drag-zoom may need to be performed several times to witness the 'ghost' effects
5. Moving the mouse will frequently cause the chart to remove the ghost traces
6. Using the mouse wheel to zoom a subset of the data will also frequently produce ghost traces

1. Set the renderer to 'SVG'
2. Set time scale to 12 hours
3. Use the mouse to drag-zoom a subset of the data
4. The chart renders the data for the new time range correctly
[ECharts Debug Ghosting-1676564844616.txt](https://github.com/VolkovLabs/volkovlabs-echarts-panel/files/10758331/ECharts.Debug.Ghosting-1676564844616.txt)

**Comment by mikhail-vl** [comment]
@Lroy Thank you for submitting an issue. I will take a look.

**Comment by Lroy** [comment]
Just an FYI...

I am pretty sure that this behavior is located in the browser somewhere... I can move my mouse over the chart area, and in the vast majority of cases, the chart immediately updates to the correct state.

**Comment by mikhail-vl** [comment]
@Lroy This is what you see as a ghosting, correct?

![Screen Shot 2023-04-17 at 15 08 28](https://user-images.githubusercontent.com/47795110/232586820-53a39c2b-bbc1-4ce0-adba-0c337b2308b0.png)

**Comment by mikhail-vl** [comment]
@Lroy I found that `showSymbol` cause the issue using Canvas. If you disable it, you don't see any ghosting. I don't use symbols, so I have not seen it when tested data zoom.

```
    showSymbol: true,
```

  Briefly looking I can't find relevant issues on Apache ECharts. I can look for possible workaround if you need to.

**Comment by Lroy** [comment]
That is correct.  That is exactly what I see.

And yes, I use showSymbol = true, so that user gets an idea where the datapoint is that can be clicked.

I don't need a work-around at the moment, as I have started to use SVG option, and that doesn't seem to show the ghosting...

**Comment by mikhail-vl** [comment]
@Lroy Thank you for confirming.

  I will take a closer look to see if we can clear the canvas or something to remove the ghosting.

**Comment by mikhail-vl** [comment]
It seems to be an issue in the Apache ECharts. Looks like various rendering optimization in browsers cause ghosting effect.

Similar issue https://github.com/apache/echarts/issues/15483, which is not resolves in the Apache ECharts repository.
