### ISSUE TITLE
[query] how to generate legend of table format like in line graph like grafana  

### ISSUE THREAD

**Issue by maplewf** [VolkovLabs/volkovlabs-echarts-panel#135]
Hi,

I must say that this is great plugin to extend grafana panel option. I'm trying to use this plugin to implement grafana-like line graph, but I met a problem about how to generate proper legend. 

As you know, grafana's line graph has very nice legend format, especially for table format statistics about max/min/avg/current etc option, and they can be scrolled when number of legend is too much. see below:
![image](https://user-images.githubusercontent.com/18524415/220099158-0a918580-e1df-46db-850f-1b78aa02a9c8.png)

I'm new for echarts, do anyone have example to implement this kind of legend? thanks

**Comment by maplewf** [comment]
@mikhail-vl Thanks for your reply, you'are right, grafana original `Time Series` is very nice. But it can't fulfill some unique requirements from us. So We want to re-create it by using Apache ECharts, then adding our feature on it. Anyway, thanks for your information.

**Comment by mikhail-vl** [comment]
@maplewf Happy coding with Apache ECharts! Please let me know if you are able to recreate the legend table to include in the documentation.
