### ISSUE TITLE
Function visibility question

### ISSUE THREAD

**Issue by ftasso** [VolkovLabs/volkovlabs-echarts-panel#136]
Hello,
I have a problem regarding functions visibility if I create a callback function from text.

I made an example using a toolbox, I hope this can help you to understand my issue:

CASE A - IT WORKS

- add an eCharts panel and put this script:

```
function myFunction(text) {
  alert(text);
}

return {
  toolbox: {
    show: true,
    itemSize: 30,
    feature: {
      my1: {
        title: 'chart',
        icon: 'M4.1,28.9h7.1l9.3-22l7.4,38l9.7-19.7l3,12.8h14.9M4.1,58h51.4',
        onclick: function (option1) {
          myFunction("chart click");
        }
      }
    }
  }
};
```

CASE B - the onclick callback is called but the internal call to myFunction doesn't work, myFunction is no more visible

- add an second eCharts panel and put this script:

```
function myFunction(text) {
  alert(text);
}

let myTextCallback = "function (option1) { myFunction(\"chart click\"); }";

let myToolbox = {
  toolbox: {
    show: true,
    itemSize: 30,
    feature: {
      my1: {
        title: 'chart',
        icon: 'M4.1,28.9h7.1l9.3-22l7.4,38l9.7-19.7l3,12.8h14.9M4.1,58h51.4',
        onclick: new Function('return ' + myTextCallback)()
      }
    }
  }
};

return myToolbox;
```

Thank you for your support,
Fabrizio

**Comment by mikhail-vl** [comment]
@ftasso I think it's a race condition. Apache ECharts function which you provide in the panel options are executed using new Function as well. When it's interpreted it tried to resolve the `myFunction`, which is not exists yet.

  What do you try to do so you need to use `new Function`?

**Comment by ftasso** [comment]
Hello Mikhail,
thank you for your reply.

I have some complex ECharts objects, for example sunburst and toolbox, strongly dynamic that depends to many variables.
For these cases a static ECharts script can't solve my problem, so I use specific servlet with JSON output + Infinity datasource to retrieve results in Grafana. 
Everything ok until a function is needed because JSON can't permit to "transfer" a function script.

The solution I found is to pass the function script as text string and then to create that with the "new Function".

Thank you,
Fabrizio

**Comment by mikhail-vl** [comment]
@ftasso It's mind-blowing. So you found a workaround and it works now for you?

  It's going beyond what we wanted to accomplish with Apache ECharts! I would love to learn more about your use case and write a blog post for the community if you are interested.

**Comment by ftasso** [comment]
No Mikhail, unfortunatelly I didn' found a workaround.

Take a look again to the script, I made some small changes to explain better:
```
function myCallback(text) {
  alert(text);
}

let myTextCallbackHelper = "function (option1) { " +
  "alert(\"Step 1\");" +                                                          // Step 1
  "myCallback(\"Step 2\");" +                                                // Step 2
  "}";

let myToolbox = {
  toolbox: {
    show: true,
    itemSize: 30,
    feature: {
      my1: {
        title: 'chart',
        icon: 'M4.1,28.9h7.1l9.3-22l7.4,38l9.7-19.7l3,12.8h14.9M4.1,58h51.4',
        onclick: new Function('return ' + myTextCallbackHelper)()
      }
    }
  }
};

return myToolbox;
```

The toolbox.feature.my1.onclick callback function (defined in text variable myTextCallbackHelper) is correctly converted to a real function and correctly called; if I click on the toolbox icon I see the alert "Step 1".
The problem is after, when myCallback is called, because the function seems to be undeclared but the function exists...

About this:

"I would love to learn more about your use case and write a blog post for the community to share your experience if you are interested."

it's a pleasure for me

**Comment by mikhail-vl** [comment]
@ftasso This is how I would do it.

  Please try and let me know if it's what you are looking for.

```js
myCallback = (text) => {
  alert(text);
}

let myTextCallbackHelper = "alert(\"Step 1\"); myCallback('Step2');"
const onclick = new Function(myTextCallbackHelper);

let myToolbox = {
  toolbox: {
    show: true,
    itemSize: 30,
    feature: {
      my1: {
        title: 'chart',
        icon: 'M4.1,28.9h7.1l9.3-22l7.4,38l9.7-19.7l3,12.8h14.9M4.1,58h51.4',
        onclick
      }
    }
  }
};

return myToolbox;
```

**Comment by ftasso** [comment]
You are a genius! It works!

**Comment by mikhail-vl** [comment]
@ftasso Thank you. We include this example in the Apache ECharts 4.2.0 release blog post.

Let me know if there is anything else.
Resolved in https://github.com/VolkovLabs/volkovlabs.io/pull/185
