### ISSUE TITLE
Non baidu map

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#137]
Greetings

So I am trying to understand if this plugin can do any none Baidu maps such as googlemap without any sort of even the smallest entanglement with PROC?

**Comment by mikhail-vl** [comment]
@yosiasz Please take a look at documentation.

  Baidu Maps API will be used only if Baidu is selected. GeoJSON or Google Maps does not require to call for Baidu API.
  You can see the code here: https://github.com/VolkovLabs/volkovlabs-echarts-panel/blob/8a63187cb94d297d7e29f88d664e492fb6d2e832/src/components/EChartsPanel/EChartsPanel.tsx#L149

  Let me know if it helps.

**Comment by yosiasz** [comment]
Ah,beautiful! Good to know. Thanks

**Comment by mikhail-vl** [comment]
@yosiasz The guy who posted about Apache ECharts connection to Baidu, probably, clicked on all possible options and then disappeared without proper explanation.

  I would not worry about it.

**Comment by yosiasz** [comment]
ok I looked high and low and cannot find how to use gmap? where would I find these details in the docs

**Comment by mikhail-vl** [comment]
@yosiasz There is a special sections for each supported Map types: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/maps/google/.

  You can also find examples for all Maps in Examples with Edit mode to try it out: https://echarts.volkovlabs.io/d/X1mkMIFVz/geo-map?orgId=1
