### ISSUE TITLE
where is this doc file located at

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#140]
Greetings 

In the following page: 
![image](https://user-images.githubusercontent.com/900951/221693394-d6d00ace-9c44-450e-b7dd-c30e7de31eba.png)

it references : docs/volkovlabs-echarts-panel/maps/geojson.js

would be nice if this was a link. No idea where to find this file, tried all kinds of locations

**Comment by mikhail-vl** [comment]
@yosiasz We had a link before to the original file, but there is nothing else in the file. Why do you want to see it?

  Here is the location: https://github.com/VolkovLabs/volkovlabs.io/tree/main/docs/volkovlabs-echarts-panel/maps

**Comment by yosiasz** [comment]
just wanted to see how to map geojson data. And does not seem that is what I am looking for and I see the example code when I scroll further down on my phone.

**Comment by yosiasz** [comment]
with this type of geojson data with geometry etc

```
"geometry": {
				"type": "MultiPolygon",
				"coordinates": [
					[
						[
							[
								-119.876152,
								46.567575,
								0
							],
							[
			
```

**Comment by mikhail-vl** [comment]
@yosiasz So, you want to display polygons on the GeoJSON Map or Google Maps? you lost me.

**Comment by yosiasz** [comment]
@mikhail-vl never mind found what I needed. Uses a geojson map.

https://echarts.apache.org/examples/en/editor.html?c=map-bar-morph

**Comment by mikhail-vl** [comment]
@yosiasz Great! We actually explained how to work with GeoJSON and LogQL in the latest video: https://www.youtube.com/watch?v=0EyFmMlIXPo

  Let me know if there is anything else.

**Comment by yosiasz** [comment]
I may be missing something from that video and I perused everywhere but I am not seeing a solid example on how to use geometry data from geojson to create boundaries within a apache echart map. The video does show how to use data from geojson but not the geometry part. Good homework for me.

for example this code

```
$.get(ROOT_PATH + '/data/asset/geo/USA.json', function (usaJson) {
  myChart.hideLoading();
  echarts.registerMap('USA', usaJson, {
```

uses the USA.json geojson data (https://echarts.apache.org/examples/data/asset/geo/USA.json)

but how would one go about doing the above code in grafana apache eChart plugin to map things out, boundaries, states, counties etc. Is that possible?

I don't want hand holding, code examples, just point me in the right direction and I will dig in.
