### ISSUE TITLE
In the case of animation, the chart starts at 0 each time the data is updated

### ISSUE THREAD

**Issue by dzgxb** [VolkovLabs/volkovlabs-echarts-panel#144]
For example, if I use Gauge and use a real-time data source(grafana live ->random-2s-stream), when the data is updated, the pointer moves from 0 to the new value, not from the previous value to the new value. Is there any way  can be set to make the point change continuously? thank you!

**Comment by mikhail-vl** [comment]
@dzgxb When the new streaming data coming in, ECharts is refreshing the whole object.

  ECharts support updating options on the fly and it should be possible to do it with the streaming.
  I will take a look what we can do.

**Comment by dzgxb** [comment]
excellent , thanks

**Comment by mikhail-vl** [comment]
I tested it with the latest version and created a test function to investigate further:

```
let sData = []
const series = data.series.map((s) => {
  sData = s.fields.find((f) => f.type === 'number').values.buffer || s.fields.find((f) => f.type === 'number').values;
});

return {
  tooltip: {
    formatter: '{a} <br/>{b} : {c}%'
  },
  series: [
    {
      name: 'Pressure',
      type: 'gauge',
      detail: {
        formatter: '{value}'
      },
      animate: false,
      data: [
        {
          value: Math.round(sData[sData.length-1] * 100) / 100,
          name: 'SCORE'
        }
      ]
    }
  ]
};
```

![Screenshot 2023-06-03 at 12 01 35](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/36de6fa7-d672-4d1c-b453-1617bf9b9b8a)

**Comment by mikhail-vl** [comment]
@dzgxb The issue was that the chart got cleared and started at 0 on each re-render.

  We removed clear, which seems unnecessary, and the live gauge started to work as expected.
  You can download the artifact in the latest CI workflow before the official release.
  Let us know if there is anything else.

**Comment by dzgxb** [comment]
I tested it with the 4.6.0  and it worked fine.thanks

**Comment by mikhail-vl** [comment]
@dzgxb Thank you for confirming.

  We have one more feature to add and I will release 5.0.0 based on Grafana 10 with removed Grafana 8.5 support.
