### ISSUE TITLE
Right click on a draggable point keeps the point in dragging mode untill click

### ISSUE THREAD

**Issue by alpglide** [VolkovLabs/volkovlabs-echarts-panel#150]
same as this one [https://github.com/apache/echarts/issues/14109](https://github.com/apache/echarts/issues/14109).  it says the issue may got fixed in echart v5.4.0  but I do have this problem. I am using volkovlabs-echarts-panel v4.3.0.

**Comment by alpglide** [comment]
> This issue is still open, and it's not clear if it was fixed. You may do your own event handling to override the default if it's the issue.
@mikhail-vl  got it. I will try to override the default action. Thanks again for your help.

**Comment by mikhail-vl** [comment]
@alpglide Also, please reply in the ECharts issue, that it's still an issue for them to investigate.

**Comment by mikhail-vl** [comment]
Let me know if there is anything else.
