### ISSUE TITLE
ECharts reported an exception just after zooming in on a data range using mouse-drag

### ISSUE THREAD

**Issue by Lroy** [VolkovLabs/volkovlabs-echarts-panel#151]
I had a chart that I wanted to zoom in on.

I did a mouse-drag across the range that I wanted to display.

The chart area displayed exception information.

I then clicked on the browser refresh, and the range that I wanted appeared on the chart.

I have attached a screenshot of the exception.
![Screen Shot 2023-03-26 at 8 54 20 AM](https://user-images.githubusercontent.com/290178/227788759-ed3657a1-c9b3-4f64-b460-d5aef6954a11.png)

**Comment by mikhail-vl** [comment]
@Lroy If you see the new range after the refresh, then location replacement worked, but another event probably got triggered and looped.

  It's unclear if `history.replaceState()` is a part of your code or Apache ECharts. Check the event handling in your code.

  Let me know if it helps.

**Comment by mikhail-vl** [comment]
Let me know if it's still an issue.
