### ISSUE TITLE
Visualize realtime data through echart using MQTT #151

### ISSUE THREAD

**Issue by SRoy0001** [VolkovLabs/volkovlabs-echarts-panel#152]
Hi, I want to visualize the automobile metrics using Dynamic Data + Time Axis graph of Apache Echart. The data is coming from an MQTT topic. The datasource is configured in Grafana, but I'm unable to visualize it. This is the code below for the graph. Where do I add the topic name in this code?

`function randomData() {
  now = new Date(+now + oneDay);
  value = value + Math.random() * 21 - 10;
  return {
    name: now.toString(),
    value: [
      [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
      Math.round(value)
    ]
  };
}

let values = [];
let now = new Date(1997, 9, 3);
let oneDay = 24 * 3600 * 1000;
let value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
  values.push(randomData());
}

option = {
  grid: {
    top: '4%',
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  tooltip: {
    trigger: 'axis',
    formatter: function (params) {
      params = params[0];
      var date = new Date(params.name);
      return (
        date.getDate() +
        '/' +
        (date.getMonth() + 1) +
        '/' +
        date.getFullYear() +
        ' : ' +
        params.value[1]
      );
    },
    axisPointer: {
      animation: false
    }
  },
  xAxis: {
    type: 'time',
    splitLine: {
      show: false
    }
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '100%'],
    splitLine: {
      show: false
    }
  },
  series: [
    {
      name: 'Fake Data',
      type: 'line',
      showSymbol: false,
      data: values
    }
  ]
};

setInterval(function () {
  for (var i = 0; i < 5; i++) {
    values.shift();
    values.push(randomData());
  }
  echartsInstance.setOption({
    series: [
      {
        data: values
      }
    ]
  });
}, 1000);

return option;`

Any help on this would be much appreciated.

**Comment by mikhail-vl** [comment]
@SRoy0001 If you have a data source configured, take a look at the documentation on how to get data from the data source: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/datasources/

  If you want Streaming, we tested the panel with Grafana Live and WebSocket data sources. You can find examples in the documentation: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/streaming/

  Let me know if it helps.

**Comment by mikhail-vl** [comment]
Let me know if there is anything else.
