### ISSUE TITLE
How can I import echarts Library or an extern module ? 

### ISSUE THREAD

**Issue by EmilioIppoliti** [VolkovLabs/volkovlabs-echarts-panel#153]
I'm trying to use the following panel from echarts on grafana, but I can't use it because of an external module, would it be possible to import it in grafana, I was thinking about dockerfile, but is there a more immediate solution ? 
![image](https://user-images.githubusercontent.com/74774607/230378690-c47d8db9-9f8d-433f-a0d3-05561ce4749c.png)

**Comment by mikhail-vl** [comment]
@EmilioIppoliti Grafana plugins use Webpack, and you can't load external modules unless modifying the Grafana image. It should be possible to do it in the Dockerfile.

  Are you looking at https://github.com/josephg/noisejs used in this example or something else? NoiseJS is very simple, and I would just copy-paste the required function

  Let me know if it helps.

**Comment by mikhail-vl** [comment]
Let us know if you need anything else.
