### ISSUE TITLE
When resizing the panel, the axis labels get out of the panel and disappear

### ISSUE THREAD

**Issue by ldrame21** [VolkovLabs/volkovlabs-echarts-panel#159]
The only way to avoid the yaxis labels to get out of the panel when resizing is to set "autolabel: true" in the "grid" field. However, it only partly solves the issue as only a large margin will keep the label inside the panel when resizing. A large margin is unfortunately not very graphically appealing and it would be great if we could have a similar behavior to the Grafana panel resizing.

Thank you for your time!

**Comment by mikhail-vl** [comment]
@ldrame21 Could you demonstrate how it looks on your charts?

  There are many examples on https://echarts.volkovlabs.io, and they scale fine unless I am missing something. They are available in the Editor mode if you want to experiment and demonstrate on them.

**Comment by mikhail-vl** [comment]
@ldrame21 You can use Width and Height of the panel if it helps: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/instance/#scale-when-resizing

**Comment by ldrame21** [comment]
@mikhail-vl  Thank you very much for your answer!
 I see a similar "problem" on the examples above. Here's an illustration of my problem. 

<img width="1512" alt="Screenshot 2023-05-04 at 10 40 36" src="https://user-images.githubusercontent.com/83647155/236154341-30cdb0d1-ec38-43d3-9921-6d0ec3bfe4ad.png">
<img width="1509" alt="Screenshot 2023-05-04 at 10 40 59" src="https://user-images.githubusercontent.com/83647155/236154378-2b234e7f-b75f-4fe5-bd32-2eed71943167.png">

As you can see, when resizing the panel the yaxis label gets out of the container. This is why I had to set a large margin but ideally, I would like to set a similar margin as the native grafana panels for consistency. The grid.containLabels set to true doesn't seem to contain the axis labels as I mentioned. I will try to find a solution with the echartsInstance.getWidth().

**Comment by mikhail-vl** [comment]
@ldrame21 Apache ECharts allows specifying various options for the grid and legends: https://echarts.apache.org/en/option.html#grid.

  There are defaults in the Apache ECharts, but the layout and scaling are the user's responsibility depending on your use case. 

  This is what we usually use for the grid, which is adjustable and depends on the labels, tooltip, toolbox, etc.:
```
  grid: {
    bottom: "3%",
    containLabel: true,
    left: "3%",
    right: "4%",
    top: "4%",
  },
```

  Let us know if there is anything else.

**Comment by mikhail-vl** [comment]
Let us know if there is anything else.
