### ISSUE TITLE
leaflet.js

### ISSUE THREAD

**Issue by supportdesk-si** [VolkovLabs/volkovlabs-echarts-panel#16]
eCharts supports the library. Experimenting with the plugin we were unable to confirm the use of leaflet is possible. It probably should be loaded as part of install and initiated.

**Comment by mikhail-vl** [comment]
The Leaflet echarts plugin is outdated. If you are looking to display interactive maps please consider looking at the Geomap plugin. The Leaflet project looks interesting and we may consider creating a separate Grafana plugin for it in future.
