### ISSUE TITLE
Would it be possible to alter the visible timespan from the echarts plugin?

### ISSUE THREAD

**Issue by Thyraz** [VolkovLabs/volkovlabs-echarts-panel#160]
I've seen that  zooming in is already possible, and that it sets the visible timespan in Grafana accordingly.
So I wondered if we could use some Javascript to completely alter the visible timespan as well?

Grafana still misses the possibility to setup user-defined timespans, even that this is an often requested feature.

Some charts e.g. make just sense with a specific time range, like a day.
Having some chart specific  presets in a dropdown would be awesome.

**Comment by mikhail-vl** [comment]
@Thyraz It's possible to have a select in the Apache ECharts. Also you can have a toolbox with button for different time ranges and adjust them using the `locationService` like zooming: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events/#update-time-range

  There is an example in the latest blog for the select https://volkovlabs.io/blog/echarts-panel-4.3.0-20230417/#panel-variables.

  Let me know if it's what you are looking for.

**Comment by Thyraz** [comment]
@mikhail-vl ah I see, `locationService.partial` can update Grafana vars:
https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/#set-a-variable-from-your-plugin

And "from" and "to" are global variables that change the time range:
https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#global-variables

Pretty neat.
Thanks a lot for exposing all this useful stuff to the end user in your wonderful plugin. 🙂👍

**Comment by mikhail-vl** [comment]
@Thyraz That's correct. This is exactly how we implemented Data Zoom similar to the Grafana's Time Series:

```
/**
 * Update Time Range on Zoom
 */
echartsInstance.on("datazoom", function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  locationService.partial({ from: startValue, to: endValue });
});
```

  Let us know if there is anything else.
