### ISSUE TITLE
Revive word-cloud extension

### ISSUE THREAD

**Issue by ioachim-hub** [VolkovLabs/volkovlabs-echarts-panel#161]
Hello,

Is it possible to bring word-cloud extension back?

**Comment by mikhail-vl** [comment]
@ioachim-hub I see the ECharts team released a new version in Nov 2022: https://github.com/ecomfe/echarts-wordcloud.

  I have not used it, but it should easy to add.

**Comment by ioachim-hub** [comment]
Thank you!
