### ISSUE TITLE
Is it possible to make the time axis like Grafana?

### ISSUE THREAD

**Issue by YoonSungHyun-inzent** [VolkovLabs/volkovlabs-echarts-panel#162]
Hello, 
I have some questions while using the tool.
When setting the time range of the Grafana, it sets the time based on the query result, allowing to set the time left and right of the center.
Is it possible to change the X-axis settings to display only a certain time range from the current time, like in Grafana, instead of setting it based on the values?

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/95339676/61d27d52-653b-4ef9-ae2e-88ec434ef2a0)

Grafana : 

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/95339676/16371227-a323-4658-be9a-0dd6c8c0f9f1)

Apache echart panel:

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/95339676/377a3db5-5429-4b1f-a687-03cc3acc2eb9)

The type of xAxis is time.

const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;

  return {
    name: s.name,
    type: 'scatter',
    showSymbol: false,
    areaStyle: {
      opacity: 0.5,
    },
    lineStyle: {
      width: 1,
    },
    data: sData.map((d, i) => [sTime[i], d.toFixed(2)]),
  };
});

The result of variable "s" is as follows. 

{
    "name": "11826",
    "refId": "A",
    "meta": {
        "executedQueryString": ""
    },
    "fields": [
        {
            "name": "Time",
            "type": "time",
            "config": {},
            "values": [
                1683762719117
            ],
            "state": {
                "scopedVars": {
                    "__series": {
                        "text": "Series",
                        "value": {
                            "name": "11826"
                        }
                    },
                    "__field": {
                        "text": "Field",
                        "value": {}
                    }
                },
                "seriesIndex": 0
            }
        },
        {
            "name": "Value",
            "type": "number",
            "config": {
                "displayNameFromDS": "11826"
            },
            "values": [
                1
            ],
            "labels": {
                "pid": "11826",
                "query_start": "2023-05-11 08:51:58.589433 +0900 KST"
            },
            "state": {
                "scopedVars": {
                    "__series": {
                        "text": "Series",
                        "value": {
                            "name": "11826"
                        }
                    },
                    "__field": {
                        "text": "Field",
                        "value": {}
                    }
                },
                "seriesIndex": 0,
                "range": {
                    "min": 1,
                    "max": 1,
                    "delta": 0
                }
            }
        }
    ],
    "length": 1
}

**Comment by mikhail-vl** [comment]
@YoonSungHyun-inzent, have you had a chance to figure it out?

  If not, I will take a look and test your function.

**Comment by mikhail-vl** [comment]
@YoonSungHyun-inzent You can filter values within the required time range using a simple `if` statement.

  Let us know if there is anything else.
