### ISSUE TITLE
Skipping loading plugin due to problem with signature

### ISSUE THREAD

**Issue by robinwangrubin** [VolkovLabs/volkovlabs-echarts-panel#17]
Hi,
    When i was trying to install this plugin. i found out below error log from my `/var/log/grafana/grafana.log`,
    BTW: I already configureate this `allow_loading_unsigned_plugins = volkovlabs-echarts-panel` in my grafana.ini

```
logger=plugin.manager t=2022-07-04T10:59:28.958393913+08:00 level=info msg="Plugin registered" pluginId=input

logger=plugin.loader t=2022-07-04T10:59:29.082900685+08:00 level=warn msg="Could not find root URL that matches running application URL" plugin=volkovlabs-echarts-panel appUrl=http://xxxxxx:8080/ rootUrls="unsupported value type"

logger=plugin.loader t=2022-07-04T10:59:29.082991956+08:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=volkovlabs-echarts-panel status=invalid```

**Comment by robinwangrubin** [comment]
Looks like it's my problem

**Comment by robinwangrubin** [comment]
My grafana Version is the newst Version: 9.0.2

**Comment by mikhail-vl** [comment]
Hello @robinwangrubin, 

  All our plugins, which are not included in the official Grafana repository, are signed as Private for RootURL `http://localhost:3000/` as you can see in the `MANIFEST.txt` file.

  We recommend to use Grafana behind NGINX for additional security and use the default host and port for Grafana.
  Please remove the `MANIFEST.txt` file from the plugin's folder and you should be able to load it as `unsigned plugins` allowing it in the configuration.

  Alternatively, you can clone, build and signed plugin for your specific domain.

**Comment by mikhail-vl** [comment]
Hello @neshorg,

  Please take a look at the previous comment, it should work for you as well, but your Grafana version 8.4.3 is a little bit old and may not be fully compatible with the plugins build with the latest Grafana 9 toolkit.

  Please test and let me know if there is any issue, but I would recommend to upgrade to 8.5 for best user experience.

**Comment by neshorg** [comment]
Hi @mikhail-vl, 

Thanks for replying!
Your trick with removing the manifest.txt worked perfectly, even with my older grafana version.
Also, due to a specific test environment I haven't upgraded it yet, but so far it seems to plot/work just fine. 

Btw, my compliments on making these plugins! You've really taken things to another level 👍

**Comment by mikhail-vl** [comment]
@neshorg Thank you for confirming.

  You are welcome and please let us know if you need anything else.
  Would love to see what you are build if it's available anywhere.

**Comment by neshorg** [comment]
@mikhail-vl It's not online, but I'll try and post pic's if I can when it's done 👍

**Comment by mikhail-vl** [comment]
@robinwangrubin Please let me know if it works for you as well.

**Comment by robinwangrubin** [comment]
> m closing the issue for now.

@mikhail-vl  Thanks for you advice. It works when i change my grafana port to 3000.  hahah thanks a lot.

**Comment by mikhail-vl** [comment]
@robinwangrubin Nice! We recommend to keep the default port and use NGINX in front of it.
