### ISSUE TITLE
Line Chart Not Showing in Grafana 10

### ISSUE THREAD

**Issue by itsnull12** [VolkovLabs/volkovlabs-echarts-panel#174]
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/22ad8f87-a960-476c-a5cd-e5df355ad8b7)

I don't know why, today my echart panel not showing the line chart. but yesterday it was working fine.
I using Grafana Cloud

In yesterday like this
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/d5ee16c4-04b2-4bf3-8f32-1627d22f8dfd)

**Comment by mikhail-vl** [comment]
@itsnull12 Was you Grafana instance updated to Grafana 10?

  It looks like `values.buffer` was updated, and it's just `values` now.

```
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;
```

  Please let me know if it's what you see.

**Comment by itsnull12** [comment]
@mikhail-vl yes i using grafana cloud and always up to date version.

> It looks like values.buffer was updated and it's just values now.

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/56a18fb8-e770-4c94-9d43-f7cb237e09dc)

Solved, thanks mikhail

**Comment by mikhail-vl** [comment]
@itsnull12 Thank you for confirming.

  It looks like it's a breaking change for Grafana 10. I will update the default example and documentation.
