### ISSUE TITLE
Sunburst panel doesn't zoom in after update variable in handle click function.

### ISSUE THREAD

**Issue by xiaobeiyang** [VolkovLabs/volkovlabs-echarts-panel#181]
echartsInstance.on("click", (params) => {
  locationService.partial({ "var-namespace": params.data.name }, true);
});

My panel handle mouse click event in a Sunburst panel. When I click the Sunburst char, the variable value change, but the chart self doesn't zoom in. Looks like the panel is re-rendered and the zoom-in state lost.

**Comment by mikhail-vl** [comment]
@xiaobeiyang That's correct. When the dashboard variable changes panel re-rerender because the state changes.

  To keep the zoom-in state, you must set it in the dashboard variable and then select the Function.
  Let me know if there is anything else.

**Comment by mikhail-vl** [comment]
Let us know if there is anything else.
