### ISSUE TITLE
grafana 10 is on my system Panels will not run

### ISSUE THREAD

**Issue by tuvok81** [VolkovLabs/volkovlabs-echarts-panel#183]
Hello,
i have update my system and grafana 10 is installed.. but the command

grafana-cli plugins install volkovlabs-echarts-panel will only install the 4.4.0 on the system .. 
can you help me with that?

**Comment by mikhail-vl** [comment]
@tuvok81 Version 4.5.0 was submitted to the Grafana team for review. It's still pending.

  Version 4.4.0 is working with Grafana 10, except `values.buffer` should be update to just `values`.
  Let us know if there is anything else.

**Comment by tuvok81** [comment]
ah ok .. t hanks
