### ISSUE TITLE
not showing chart on grafana 10

### ISSUE THREAD

**Issue by kangbobi** [VolkovLabs/volkovlabs-echarts-panel#186]
not showing chart on grafana 10

**Comment by mikhail-vl** [comment]
@kangbobi Grafan 10 introduced breaking changes in the data frames. Update `values.buffer` to `values`.

  Take a look at https://volkovlabs.io/blog/echarts-panel-4.5.0-20230603/#changes-in-grafana-10
  Let us know if there is anything else.

**Comment by kangbobi** [comment]
@mikhail-vl thanks solved

**Comment by mikhail-vl** [comment]
@kangbobi Great! Thank you for confirming.
