### ISSUE TITLE
 echart function is executed multiple times?

### ISSUE THREAD

**Issue by alpglide** [VolkovLabs/volkovlabs-echarts-panel#187]
I have a simple echart function as the following with variable named mt, which is a custom variable with 3 possible values, for example, 0,1,2. 

`let mt = replaceVariables('$mt');`
 `echartsInstance.on('dblclick', function (params) {`
 ` console.log("doubleclick: ", mt); `
 `});`
`let myopt = {`
`  geo: {`
 `   map: "USA",`
`  },   `
`};`
`return myopt;`

at the beginning, for example, mt=0, doulbleclick anywhere in the map, console output as "doubleclick 0", that's correct.
when we choose mt =2, doubleclick anywhere in the map, console outputs two lines "doubleclick 0" and "doubleclick 2", instead of just "doubleclick 2" as expected.

**Comment by alpglide** [comment]
I did try v2.
if I use the same  echart configuration as the following, I got the same result. (when user choose different variable value, the console output all old variable (mt) values and new value.

let mt = replaceVariables('$mt');
echartsInstance.on('dblclick', function (params) {
console.log("doubleclick: ", mt);
});
let myopt = {
  geo: {
   map: "USA",
 },  
};
return myopt;

if I rewrite echart   new version of config as the following, nothing shows up in echart (even no USA map):
let mt = replaceVariables('$mt');
echartsInstance.on('dblclick', function (params) {
  console.log("doubleclick: ", mt);
});
let myopt = {
  resultVersion: 2,
  optionConfig: { notMerge: true },
  option: {
  geo: {
    map: "USA",
  }
  },
  unsubscribeFunction: () => {
    console.log('unsubscribeFunction')
  }
};
return myopt;

**Comment by mikhail-vl** [comment]
@alpglide When Apache ECharts panel refreshes instances are still the same and event handlers are preserved.

You can disable all previous events before set it again like

```
echartsInstance.off("dblclick");
echartsInstance.on('dblclick', function (params) {
console.log("doubleclick: ", mt);
});
```

  This is what we are working in v2, that in the `unsubscribeFunction` you can disable previous events and remove all subscriptions.

**Comment by mikhail-vl** [comment]
There is similar example in the Blog post: https://volkovlabs.io/blog/echarts-panel-4.2.0-20230304/#preserve-visual-map-selected-range

**Comment by alpglide** [comment]
wow, that  'echartsInstance.off("dblclick");' works in v2.
Your help is highly appreciated.

**Comment by alpglide** [comment]
Any suggestion on [#185 ](https://github.com/VolkovLabs/volkovlabs-echarts-panel/issues/185). I thought I figured it out, but I was wrong.

**Comment by mikhail-vl** [comment]
@alpglide Thank you for confirming.
