### ISSUE TITLE
Communication between charts for zooming and ranging

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-echarts-panel#19]
Using `eventBus` for notifications.

Example: https://community.grafana.com/t/how-to-subscribe-to-grafana-application-events/59147.

**Comment by supportdesk-si** [comment]
This is much needed option. However, this needs to be controlled via global variable that can be set as `true` or `false`. Example is one dashboard can use it and another allows charts to be independent. Often used for comparative review or analysis.

**Comment by mikhail-vl** [comment]
@supportdesk-si, Thank you for the feedback. I am planning to use the `eventBus` (https://community.grafana.com/t/how-to-subscribe-to-grafana-application-events/59147) and It will be available in the next version 3.2.0.

**Comment by mikhail-vl** [comment]
We may look into it further if we see interest from the community in this feature. Closing for now,
