### ISSUE TITLE
Request Add Locale Format

### ISSUE THREAD

**Issue by itsnull12** [VolkovLabs/volkovlabs-echarts-panel#194]
Dear VolkovLabs,

I need locale format on markPoin like this 999.999.999
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/28b1d39a-5cc1-4e40-bfd7-17aa08dab0ba).

Is it available for next update ?

Thank you

**Comment by mikhail-vl** [comment]
@itsnull12 You can use formatter to format the way you wanted it: https://echarts.apache.org/en/option.html#series-line.markPoint.label.formatter

  Let us know if there is anything else.

**Comment by itsnull12** [comment]
Could you please tell me to use it ? i can't find it in the documentation.

In antoher official panel from Grafana, i just setup Standard option > Unit > Locale format. It will change the number format to thousand separator.
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/ecb03a20-170e-47bc-8293-c15077fbcd60)

**Comment by mikhail-vl** [comment]
@itsnull12  You can use `.toLocaleString` for the value in the label's formatter.

```
      markPoint: {
        label: {
          formatter: (param) => {
            return param.value.toLocaleString();
          }
        },
```

  Let us know if there is anything else.
