### ISSUE TITLE
Legend doesn't work in dark Mode

### ISSUE THREAD

**Issue by CodyGirl** [VolkovLabs/volkovlabs-echarts-panel#203]
When trying to display the Legend of a network graph with profile theme as 'dark', it picks up default theme colors instead of the ones passed in the return value of options.
Grafana version: 10.0.2
Apache Echarts Plugin version: 5.0.0 (same behavior with 4.5.0)

Code that returns legend colors:
`return {
  legend: [
    {
      data: categories.map(function (a) {
        return a.name;
      })
    }
  ],
  color: ['red', 'blue'],
.......`

Below screenshot shows the legend in dark mode (**Current** Behavior):
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/14803653/cdf0e2fd-2cfb-4265-bea9-fafb14c7211d)

Same graph with Light Mode (**Expected** Behavior):
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/14803653/70034b4c-3033-421c-bcef-9d581c3a2662)

Please feel free to point me in the right direction if I'm missing something.

**Comment by mikhail-vl** [comment]
@CodyGirl I just tested on https://echarts.volkovlabs.io, and it works as expected using the latest 5.0.0. It should be something related to your code or configuration.
  
![Screenshot 2023-07-27 at 13 21 23](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/4fbd6096-7655-4f45-89a9-cf983da7db8a)

    Do you use a default or custom theme?

**Comment by CodyGirl** [comment]
Thank you so much for your quick response, please guide me if I'm doing something wrong here. I've pasted the code below:

```let nodeIds = [], titles = [], url = [], degree = [], color = [];
let sources = [].targets = [], edgeIds = [];
let category = [];
let repos = [], statuses = [];
data.series.map((s) => {
  if (s.refId == 'nodes') {
    nodeIds = s.fields.find((f) => f.name === 'id').values.buffer || s.fields.find((f) => f.name === 'id').values;
    titles = s.fields.find((f) => f.name === 'title').values.buffer || s.fields.find((f) => f.name === 'title').values;
    url = s.fields.find((f) => f.name === 'url').values.buffer || s.fields.find((f) => f.name === 'url').values;
    degree = s.fields.find((f) => f.name === 'degree').values.buffer || s.fields.find((f) => f.name === 'degree').values;
    color = s.fields.find((f) => f.name === 'color').values.buffer || s.fields.find((f) => f.name === 'color').values;
  } else if (s.refId == 'edges') {
    sources = s.fields.find((f) => f.name === 'source').values.buffer || s.fields.find((f) => f.name === 'source').values;
    targets = s.fields.find((f) => f.name === 'target').values.buffer || s.fields.find((f) => f.name === 'target').values;
    edgeIds = s.fields.find((f) => f.name === 'id').values.buffer || s.fields.find((f) => f.name === 'id').values;
  } else if (s.refId == 'statuses') {
    repos = s.fields.find((f) => f.name === 'repo').values.buffer || s.fields.find((f) => f.name === 'repo').values;
    statuses = s.fields.find((f) => f.name === 'state').values.buffer || s.fields.find((f) => f.name === 'state').values;
  }
})

color = [];
for (let i = 0; i < url.length; i++) {
  if (url[i] && url[i] != '') {
    repository = url[i].split('/').pop()
    index = repos.indexOf(repository)
    if (index != -1) {
      if (statuses[index] == false) {
        color[i] = '#f5715f' // fail state
      } else if (statuses[index] == true) {
        color[i] = '#9ae376' // pass state
      } else {
        color[i] = "#e9ed77" // state not available
      }
    } else {
      color[i] = "#e9ed77" // not a precice repo
    }
  }
}

const connections = sources.map(function (value, i) {
  return { source: value, target: targets[i] }
})

const nodes = titles.map(function (value, i) {
  return {
    fixed: false,
    name: nodeIds[i],
    value: value,
    itemStyle: {
      color: color[i],
      borderWidth: 1,
      borderColor: 'black'
    },
    url: url[i],
    symbolSize: (degree[i] + 5) * 1.5,
    smooth: true,
    label: {
      padding: [5, 5],
      position: 'bottom',
      textStyle: { fontWeight: '500s' }
    }
  }
})

echartsInstance.on('click', { dataType: 'node' }, params => {
  if (!params.data.url) {
    return;
  }
  window.open(params.data.url, '_blank')
})

category = ['Failure', 'Successful', 'Not Available']
const categories = category.map(function (value, i) {
  return { name: value }
})

return {
  colorBy: "series",
  legend: [
    {
      data: categories.map(function (a) {
        return a.name;
      })
    }
  ],
  color: ['#f5715f', '#9ae376', '#e9ed77'],
  series: [
    {
      type: 'graph',
      layout: 'force',
      roam: true,
      draggable: true,
      scaleLimit: { min: 0.0, max: 50 },
      label: {
        show: true,
        formatter: '{b}'
      },
      data: nodes,
      edges: connections,
      categories: categories,
      edgeSymbol: ['none', 'arrow'],
      force: {
        initLayout: 'circular',
        repulsion: 10,
        gravity: 0.03,
        edgeLength: 150
      },
      lineStyle: {
        color: '#525453',
        curveness: 0.1
      },
      emphasis: {
        focus: 'adjacency',
        lineStyle: {
          width: 10
        }
      },
    },
  ]
};```


The color of each node is calculated on the go and the categories are kind of fixed for now.
When I switch Grafana user's preference to dark mode, it stops showing the colors I've passed in the color[] array and uses some default color scheme. However, it works perfectly if user's preference is 'light' theme.
Please pardon the rookiness in my code style, I'm just trying to learn how to work echarts in grafana.

**Comment by CodyGirl** [comment]
@mikhail-vl In the screenshot that you attached above, did you change it to "dark" theme from user profiles or by changing your system settings?
Since I can't login on https://echarts.volkovlabs.io/login, I replicated this on my local with same plugin version (5.0.0) and when I change user profile preference to "Dark" it always shows default colors and not the ones passed in color:[] property for the legend. However, it works fine with profile preference as "light". Could this be a plugin issue or grafana profile theme issue?

**Comment by mikhail-vl** [comment]
@CodyGirl, I tried your code and can see the issue with dark theme legend colors.

  I am checking why it's happening and get back to you.

**Comment by mikhail-vl** [comment]
@CodyGirl Your issue is similar to the issue opened in the ECharts: https://github.com/apache/echarts/issues/18951

  The dark theme merges with the manual colors, and it becomes overridden.
  I would suggest using the `itemStyle`, which allows specifying color for each node: https://echarts.apache.org/en/option.html#series-graph.itemStyle.color.
  Legend is done the same way.

**Comment by CodyGirl** [comment]
@mikhail-vl Thanks for your reply. So using itemStyle works for changing color of nodes irrespective of the theme. However, do you have any example where I can see how it can be used for legends? Because color=[] in return value still will get merged with theme irrespective of node color.

**Comment by mikhail-vl** [comment]
@CodyGirl Should be similar to the nodes: https://echarts.apache.org/en/option.html#legend.data.itemStyle.color

  Let me know if it helps.

**Comment by CodyGirl** [comment]
@mikhail-vl I tried it but the legend colors just changed to black and grey:
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/14803653/f1596195-a6a8-4164-862c-c0131b41eddb)
`  legend: [
    {
      data: categories.map(function (a) {
        return a.name;
      }),
      itemStyle: {
        color: ['red', 'blue', 'green'],
        borderWidth: 1,
        borderColor: "white"
      },
    }
  ],`

**Comment by mikhail-vl** [comment]
@CodyGirl Each value should have a color like this:
```
const legendColors = ['#f5715f', '#9ae376', '#e9ed77'];
const legend = [
  {
    data: categories.map(function (a, i) {
      return {
        name: a.name, itemStyle: {
          color: legendColors[i]
        }
      };
    })
  }
];
```

**Comment by mikhail-vl** [comment]
@CodyGirl Thank you for confirming. You can open the issue in the Apache ECharts repository for a better way to match colors with categories.

  Ideally, the color issue should be fixed in the Apache ECharts https://github.com/apache/echarts/issues/18951. We always keep the panel updated with the latest version of the library.

  Let us know if there is anything else.
