### ISSUE TITLE
Time range resets after MW scrolldown

### ISSUE THREAD

**Issue by cringoleg** [VolkovLabs/volkovlabs-echarts-panel#204]
## Expected behavior
When using `datazoom` in options object (echarts options parameter): 
``` javascript
options = {
  // ...
  dataZoom: [
    {
      show: true,
      realtime: true,
      start: 30,
      end: 70,
      xAxisIndex: [0, 1]
    },
    {
      type: 'inside',
      realtime: true,
      start: 30,
      end: 70,
      xAxisIndex: [0, 1]
    }
  ],
  // ...
}
```
And scrolling wheel down, the panel is expected to zoom out on already zoomed in part of data. Check out [apache echarts example](https://echarts.apache.org/examples/en/editor.html?c=grid-multiple).

## Actual behavior

The scrolldown button causes the whole dashboard to reset the time range.
In my case it resets to `last 30 minutes` even though I have set it to specific time range beforehand.

I also use the following code to allow data zoom in every echarts panel:
``` javascript
/**
 * Enable Data Zoom by default
 */
setTimeout(() => echartsInstance.dispatchAction({
  type: 'takeGlobalCursor',
  key: 'dataZoomSelect',
  dataZoomSelectActive: true,
}), 500);

/**
 * Update Time Range on Zoom
 */
echartsInstance.on('datazoom', function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  locationService.partial({ from: startValue, to: endValue });
});
```
---
Also this problem is not reproducible while editing the panel, only while using it in dashboard view.

**Comment by mikhail-vl** [comment]
@cringoleg The `datazoom` feature provides the same functionality by updating the time range as the native Time Series panel. This is what causes updating the Time Range.

  If you don't need to update the time range and use native Data Zoom functionality, you can remove this event handler:
```
/**
 * Update Time Range on Zoom
 */
echartsInstance.on('datazoom', function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  locationService.partial({ from: startValue, to: endValue });
});
```

**Comment by mikhail-vl** [comment]
@cringoleg I hope it's clear.

  Let us know if there is anything else.
