### ISSUE TITLE
Increasing heap memory leads to Out Of Memory

### ISSUE THREAD

**Issue by sergiomonteroselma** [VolkovLabs/volkovlabs-echarts-panel#205]
Hello, 
I am testing to use the plugin with data from input JSON get by JSON API Datasource. However, the data from the JSON API is maintain in memory as String and after a period that depends on the data get and the refresh period, the browser crash with "Out of Memory" message. 
This does not happen when using the same Datasource and other graph or plugin to draw the data. 
I have Grafana v9.5.1 and Apache ECharts 5.0.0, but I have also test it on Grafana v10.0.3 and the same happen.
I have also to test the Apache Echart V2 with the unsubscribe function, but the same results I get. 
Even It happen if I maintain JSON API Datasource, and Use an Apache Echart Graph with data inside the code, since data are also query to the source... It seems like the plugging maintain reference to the previous data and the Garbage Collector does not remove it.
Inside the code, I used JSON.parse and forEach function, in order to count the number of items and show it as a Echart Bar graph.

Is there something I'm doing wrong with the graph?

Is there any impediment to use as datasource the plugin "JSON API v1.3.6" from Marcus Olson?

Thanks for considering my request, 

Sergio Montero

**Comment by mikhail-vl** [comment]
@sergiomonteroselma How much data do you retrieve from the JSON API Datasource?

  All data sources retrieve data in data frames that are the same for all panels.
  If other panels work, the problem may be in the Apache ECharts panel, not the JSON API Data Source.
  We had no reports of the "Out of Memory" issue. We need more information to investigate further.

  Using V2, have you tried to add to the unsubscribe function `echartsInstance.dispose()`. I wonder if it can resolve the issue.

  Can you share the link for the API if it's open?
  If you can tell me how many records and formats, we can reproduce it using the Static Data Source, or you can do it yourself. The latest version support JavaScript, so you can generate millions of records if required.
  If you do, please provide a dashboard to troubleshoot further.

**Comment by sergiomonteroselma** [comment]
Thanks for the response. 

The JSON is very large, between 10MB and 100MB based on dashboard Filters.

Sorry, I cannot share the API, because is under development, but here are the steps to reproduce the error with another API (JSON with 24.9 MB) and the minimum code to have the issue.

Environment: 
-Grafana v9.5.1 (bc353e4b2d)
-Apache ECharts 5.0.0 From Volkov Labs
-JSON API 1.3.6 From Marcus Olsson

Grafana v9.5.1 (bc353e4b2d)
Bugfix with "Apache Echart":
1) Add data source (Type: "JSON API"), name: "JSON API LARGE", and URL: https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json
2) Create Dashboard
3) Add visualization
4)  Select Datasource JSON API LARGE, Fields-Field: $[*], cache Time: 0s
5) Select Visualization "Apache Echarts"
6) Add Code: 
           let dataLabels = ['Test']
           let dataSeriesArray = [];
           dataSeriesArray.push(
             {
               data: [1, 0, 0, 0, 0],
               type: 'bar',
               stack: 'bar',
             }
           );
           return {
             yAxis: {
               type: 'category',
               data: dataLabels
             },
             xAxis: {
               type: 'value',
               minInterval: 1
             },
             series: dataSeriesArray,
           }
7) Save Dashboard with name OOM
8) Copy the URL of the Dashboard
9) Open the Dashboard in a new tab, and close the previous one
10) Open browser DevTools
11) Go to memory and "Take snapshot", it should be around 60MB, and Constructor (String) around 36MB
12) Refresh dashboard to get data from the source using the refresh button inside dashboard
13) Take a new Memory Snapshot and now it should be around 86MB, and Constructor (String) around 64MB
14) Refresh dashboard to get data from the source using the refresh button inside dashboard
15) Take a new Memory Snapshot and now it should be around 115MB, and Constructor (String) around 91MB

No Bugfix with "Stats":
1) Create Dashboard
2) Add visualization
3)  Select Datasource JSON API LARGE, Fields-Field: $[*], cache Time: 0s
4) Select Visualization "Stats"
5) Save Dashboard with name NO-OOM
6) Copy the URL of the Dashboard
7) Open the Dashboard in a new tab, and close the previous one
8) Open browser DevTools
9) Go to memory and "Take snapshot", it should be around 50MB, and Constructor (String) around 32MB
10) Refresh dashboard to get data from the source using the refresh button inside dashboard
11) Take a new Memory Snapshot and now it should be around 50MB, and Constructor (String) around 32MB
12) Refresh dashboard to get data from the source using the refresh button inside dashboard
13) Take a new Memory Snapshot and now it should be around 50MB, and Constructor (String) around 32MB

Thank you very much

**Comment by mikhail-vl** [comment]
@sergiomonteroselma Thank you for providing details to reproduce the issue.

  I tested on Grafana 9.5.1 and Grafana 10.0.3 both panels. I see the heap memory increase for both panels equally

![Screenshot 2023-08-10 at 09 43 30](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/c6630494-085a-4baf-a17f-e39d4e255c4f)

  I will do more tests and get back to you.

**Comment by mikhail-vl** [comment]
@sergiomonteroselma I did more tests with Stats and Grafana Random Walk data source. It's not as bad as with big JSON files, but you can still see the increase.

  As you can see, Heap size is constantly increasing. I am not sure how you got 50Mb consistent.

![Screenshot 2023-08-10 at 11 24 57](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/85f1985c-b35f-44eb-b973-4e6f4a44c864)

**Comment by mikhail-vl** [comment]
@sergiomonteroselma As I mentioned in the first response, `dispose` may resolve the issue.

  Looks like we have to dispose ECharts on refresh.
  I tested it with the new extended format, which allows to specify unsubscribe function. The heap memory seems stable after 3rd refresh. We will add it in the upcoming version.

```
let dataLabels = ['Test']
let dataSeriesArray = [];

dataSeriesArray.push(
  {
    data: [1, 0, 0, 0, 0],
    type: 'bar',
    stack: 'bar',
  }
);

return {
  version: 2,
  config: { notMerge: true },
  option: {
    yAxis: {
      type: 'category',
      data: dataLabels
    },
    xAxis: {
      type: 'value',
      minInterval: 1
    },
    series: dataSeriesArray,

  },
  unsubscribe: () => {
    if (echartsInstance) {
      echartsInstance.dispose();
    }
  }
};
```

**Comment by asimonok** [comment]
A memory leak issue in Apache Echarts - https://github.com/hustcc/echarts-for-react/issues/533

**Comment by asimonok** [comment]
@mikhail-vl  @sergiomonteroselma 
Memory leak appears by new subscriptions on restore event which is being called on each data update. The subscription copies all chart state (current and previous). Added unsubscribe from the event before new subscription. It fixed the problem. With this solution, disposing of the chart is not necessary so chart refreshing with animations will be still working.


Comparison of the memory usage without fix and with fix. Tests are: initial dashboard load, 5 refreshes before each snapshot.

Without fix:
<img width="883" alt="Screenshot 2023-08-11 at 10 49 55" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/15867703/d8d1fb6e-aa56-4c61-8b2b-352a3c0275eb">

With fix:
<img width="879" alt="Screenshot 2023-08-11 at 10 51 20" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/15867703/825c7986-4340-48da-a3fc-f2fd664a703b">

In panel edit mode, memory is still increasing but not too much large.

**Comment by sergiomonteroselma** [comment]
Thanks @mikhail-vl and @asimonok.

@mikhail-vl I have tested the dispose and the heap memory seems stable after 3rd refresh because not get the data (I do not think that due to It is not used in the Echart Graph, since in the real one, the data is not load too). Could you check that with echartsInstance.dispose(), each refresh the dashboard is getting the data from the source?

@asimonok, What fix are you referring to? using the echartsInstance.dispose()? If so, could you check that each refresh the dashboard is getting the data from the source too? If not, when a version with the fix is expected to be released?

**Comment by mikhail-vl** [comment]
@asimonok Well done!

@sergiomonteroselma I will release 5.1.0 today with included fix and send to Grafana team for review.

**Comment by mikhail-vl** [comment]
@sergiomonteroselma Version 5.1.0 released https://github.com/VolkovLabs/volkovlabs-echarts-panel/releases/tag/v5.1.0

**Comment by sergiomonteroselma** [comment]
@mikhail-vl, @asimonok

Being pending of some longer tests, everything indicates that the memory no longer grows after three increments when I have updated the plugin to the Version 5.1.0. 

Great job,

Thank you very much for your help and effort

**Comment by mikhail-vl** [comment]
@sergiomonteroselma Thank you for confirming.

  Let us know if there is anything else.
