### ISSUE TITLE
Exception raised when showing an SVG

### ISSUE THREAD

**Issue by XIIIVI** [VolkovLabs/volkovlabs-echarts-panel#212]
Hi all,

Thanks for all the amazing work you're doing.
I'm using the v5.1.0 of the echart panel.
My goal is to display an SVG (a building) and to update it depending on the result of request.
Everything works fine except the first time the dashboard is displayed as the following error is raised:
```
ECharts Execution Error
Cannot read properties of undefined (reading 'regions')
TypeError: Cannot read properties of undefined (reading 'regions')
    at t.getFilledRegions (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:1552681)
    at e.optionUpdated (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:1553170)
    at e.eval (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:552990)
    at Array.forEach (<anonymous>)
    at wt (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:379245)
    at e.eval (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:552607)
    at t.topologicalTravel (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:545959)
    at e._mergeOption (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:552103)
    at Rd (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:557265)
    at e._resetOption (http://127.0.0.1:3000/public/plugins/volkovlabs-echarts-panel/module.js:2:551368)
```

When the dashboard is refreshed, the message disappeared and left a blank at the panel position.
When going back (button with the left arrow in the web browser) and "go ahead" (button with the right arrow in the web browser), the error is not raised and the SVG is displayed.

Here is the definition of the dashboard
```
option = {
  tooltip: {
  },
  series: [],
  geo: {
    map: 'building',
    type: "map",
    zoom: 2.0,
    regions: [
      {
        name: "dcfc",
        itemStyle: {
          normal: {
            opacity: 0
          }
        },
        label: {
          show: false
        }
      }
    ],
    emphasis: {
      focus: 'self',
      itemStyle: {
        color: null
      },
      label: {
        position: 'bottom',
        distance: 0,
        textBorderColor: '#fff',
        textBorderWidth: 2
      }
    },
    blur: {},
    select: {
      itemStyle: {
        color: '#b50205'
      },
      label: {
        show: false,
        textBorderColor: '#fff',
        textBorderWidth: 2
      }
    }
  }
};
```
I have been stuck for 2 months and any help will be appreciated,

Thanks in advance,

Paul

**Comment by mikhail-vl** [comment]
@XIIIVI I think you have a race condition. How do you load your SVG file? If you do async, then update it to use sync more or update options when SVG is loaded.

  We have an example how to load the SVG file from the data source: https://echarts.volkovlabs.io/d/X1mkMIFVz/geo-map?orgId=1&editPanel=8.

  Let me know if it helps.

**Comment by XIIIVI** [comment]
Hi Mikhail,

Thanks for your feedback.
I load the map like this

```
fetch('public/img/icons/building.svg')
  .then(function (response) {
    return response.text();
  })
  .then(function (svgText) {
    const parser = new DOMParser();

    svgDOM = parser.parseFromString(svgText, 'image/svg+xml').documentElement;

    echarts.registerMap('building', { svg: svgDOM });
  })
...
```
To make it synchronous, I changed into
```
async function loadMap() {
  await fetch('public/img/icons/building.svg')
  .then(function (response) {
    return response.text();
  })
  .then(function (svgText) {
    const parser = new DOMParser();

    svgDOM = parser.parseFromString(svgText, 'image/svg+xml').documentElement;

    echarts.registerMap('building', { svg: svgDOM });
  })
}

try {
  loadMap();
} catch (error) {
  console.error(error);
}

```

The SVG file is embedded with Grafana.

In your example, I noticed you are using "visualmap".
If I change "visualmap" into "geo", your example got the same error.

Many thanks for your precious help,

Paul

**Comment by mikhail-vl** [comment]
@XIIIVI When do you return ECharts options after the `try` statement? Then it's not sync.

  The options returned before your SVG loaded and map registered.

**Comment by mikhail-vl** [comment]
@XIIIVI Totally forgot that it's explained in the documentation:

https://volkovlabs.io/plugins/volkovlabs-echarts-panel/maps/geojson/#dynamic-maps-loading

**Comment by XIIIVI** [comment]
Hi Mikhail,

This is the point I missed.
I'm very grateful for this, you saved my life :)

Once again, many thanks for your beautiful work.

All the best,

Paul

**Comment by mikhail-vl** [comment]
@XIIIVI Thank you for confirming.

  Let us know if there is anything else.
