### ISSUE TITLE
Grafana Apache Echarts - Reinitialise chart

### ISSUE THREAD

**Issue by viralui** [VolkovLabs/volkovlabs-echarts-panel#213]
How to reinitialise Apache echarts on mouse over event in Grafana. Basically want to change some series properties and reinitialise the chart.

**Comment by mikhail-vl** [comment]
@viralui Use `setOption()` to update chart's options.

  There is an examples in the documentation: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/maps/geojson/#switching-between-maps
