### ISSUE TITLE
Apache Echarts - Grafana- Event Handling - Location.Partial and Set Option

### ISSUE THREAD

**Issue by viralui** [VolkovLabs/volkovlabs-echarts-panel#216]
On click event need to perform, location.partial action to change variable values as well as echarts.setoption to make changes to series parameters. What is the best way to perform this type of action. 
If we use promise function,then it's possible to perform the action one after another, but how to capture the response for location.partial as it's reinitializing the whole dashboard

**Comment by mikhail-vl** [comment]
@viralui `location.partial` refresh dashboard and re-render panels.

  You can't capture the response from it, you will need to rethink your logic.
