### ISSUE TITLE
Fetch users default theme

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-echarts-panel#219]
I want to create a gap between values in pie charts in a similar wasy to grafana's pie chart. Echarts doesnt have a way i can see to create that so i could acheive the same creating a transparent border but echarts doesnt support that either. If i can figure out the color theme a user has set in grafana i can then color the border the same as the backgorund making it transparent.

Is it possible to fetch that in javascript using your panel, if so how would i do that, any suggestions? Cheers

**Comment by mikhail-vl** [comment]
@craftzneko You can take it from the `theme` object: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/options/

```
    let echartsTheme = theme.isDark ? 'dark' : undefined;
```

**Comment by craftzneko** [comment]
Perfect thanks @mikhail-vl
