### ISSUE TITLE
How to pass the variable text to replaceVariables in Grafana

### ISSUE THREAD

**Issue by SC-66** [VolkovLabs/volkovlabs-echarts-panel#220]
I have a variable with a key : value pair. I want to get the variable text displayed in my echart and not the value.
So if the variable has these key/values
Table : 1 , Chair : 2 , Lamp : 3
and I pass the variable to replaceVariables it will get the 1, 2, 3 values, but not the text of the variable value., se below.
If I try to type MyVariable:text I get an error.

title: {
    text: replaceVariables('$MyVariable'), // I Want to pass $MyVariable:text here !!!
    },

**Comment by mikhail-vl** [comment]
@SC-66 The `key:value` mapping is not disclosed to the variable value and can't be retrieved using `replaceVariables()`.

  To get this mapping you would need access to the Template Service, which is not exposed to the ECharts function.

  If you retrieve this mapping using Query you can use the same query in the Query Editor for the panel and then parse it from `data`. If it's static, then define it as a hash in the code.
