### ISSUE TITLE
Use variable change as event to change a display

### ISSUE THREAD

**Issue by kyrianae** [VolkovLabs/volkovlabs-echarts-panel#221]
Is there a way to use event on a variable change in order to change display for example from line to donut in a echart panel 
witch kind of event we need to use to do that if it's possible.

example I set a variable display in custom with "line" and "donut" value
in order to change the dashboard content

**Comment by mikhail-vl** [comment]
@kyrianae Yes, it's possible with dynamic updating ECharts options.

  You can find examples in the documentation: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/
