### ISSUE TITLE
Open link in new window - How to?

### ISSUE THREAD

**Issue by SC-66** [VolkovLabs/volkovlabs-echarts-panel#222]
I want to open a link to a new dashboard into a new window. When I use the following method it opens the new dashboard in the same window and "back" does not work or does not go back to previous dashboard.  So how can I open another dashboard into another window on click? (I.e. mimic the way as data links works in Grafana default visualisations)

echartsInstance.on('click', (params) => {
  locationService.replace('/d/PQeH9VFVk/gauge?orgId=1');
});

**Comment by mikhail-vl** [comment]
@asimonok Any suggestions?

**Comment by asimonok** [comment]
@SC-66 to open a new window you can use `window.open('/d/PQeH9VFVk/gauge?orgId=1')`. Location Service is only for working with the current window.
