### ISSUE TITLE
Dynamic custom theming when embedding a panel

### ISSUE THREAD

**Issue by armanossiloko** [VolkovLabs/volkovlabs-echarts-panel#223]
I know Apache Echarts supports custom theming using the theme builder, but is it possible to pass in a theme (or some of its properties / colors) and apply that on the theme when embedding a panel elsewhere (e.g I'd like my colors to come from a datasource or be defined using the embed URL)?

**Comment by armanossiloko** [comment]
As it turns out, it is possible to change the colors of the series in the `setOption` function. Data can be retrieved from a Grafana dashboard variable using `replaceVariables("$varName")` (e.g `let colorsList = replaceVariables("$colors");`)  and from there, playing around with the values would make this whole thing doable.

**Comment by mikhail-vl** [comment]
@armanossiloko That's a correct approach. I hope it works for you.
