### ISSUE TITLE
Default Content

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-echarts-panel#224]
When a data source doesn't return any data the panel will display an error unless i handle it in javascript. In other panels such as dynamic text you have an option for what to display as default content if no data is received, is this something that could be added to this as well?

**Comment by mikhail-vl** [comment]
@craftzneko Thank you for opening the feature request.

  In PR https://github.com/VolkovLabs/volkovlabs-echarts-panel/pull/211 we adding Visual Editor, which should help with data from data sources.
