### ISSUE TITLE
data extraction helper feature 

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#225]
Hello

Currently when instantiating the apache echart panel by default it comes out with

```
const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer || s.fields.find((f) => f.type === 'number').values;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer || s.fields.find((f) => f.type === 'time').values;
```

It would really be cool if this plugin implemented data extraction helper feature that would assist a non js dev/expert to extract their data points as follows

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/900951/372f2a4d-ccc5-43a8-a937-596b03e71606)

In above picure from dynamic text, use can select components one would like to implement. Would be nice if apache echart would do something similar with the data coming from data source. It would list out the data points (columns) for the dev and the dev would select which columns from data source to use. Maybe these data points would come under a certain static domain ie `aec_data` apache echart data so that in the js code section one can refer to these as `aec_data.createtime` `aec_data.value` `aec_data.metric` etc

This is of course in addition to the current way of custom code.

I think adoption of this plugin would increase if such an data extraction assistor was implemented?

Thanks!

**Comment by mikhail-vl** [comment]
Resolved in #211.
