### ISSUE TITLE
Zabbix data source

### ISSUE THREAD

**Issue by michalsandt** [VolkovLabs/volkovlabs-echarts-panel#226]
Hi, any chance fo exapamles (dashboard) where data source is from Zabbix?

**Comment by mikhail-vl** [comment]
@michalsandt We don't use Zabbix in our projects.

  As I replied on YT, all data source are the same from the panel point of view. There is no difference between PostgreSQL and Zabbix in the way they return data frames.

**Comment by mikhail-vl** [comment]
You can check with Community on the Forum. There are Grafana Champions who master the Zabbix and can guide you: https://community.grafana.com
