### ISSUE TITLE
Copy text to clibboard from label/tooltip

### ISSUE THREAD

**Issue by culaja** [VolkovLabs/volkovlabs-echarts-panel#229]
Hi,

Is there a possibility to copy text from label or tooltip?

ClipboardJS library is currently not compiled together with plugin so I'm not sure if this is possible today?

Kind regards,
Stanko.

**Comment by mikhail-vl** [comment]
@culaja Have you tried Clipboard API?

```
  navigator.clipboard.writeText("Help");
```

**Comment by culaja** [comment]
It works, thanks. This is my solution if someone needs it:
`echartsInstance.off("dblclick");
echartsInstance.on("dblclick", (params) => {
  navigator.clipboard.writeText(params.data);
});
`

**Comment by mikhail-vl** [comment]
@culaja Great, thank you sharing.
