### ISSUE TITLE
Mapping data with same ref name 

### ISSUE THREAD

**Issue by Alexstat98** [VolkovLabs/volkovlabs-echarts-panel#230]
Hi everybody,

I want to produce a line graph with two lines and the same date, nothing challenging at a glance.
But, the problem is, when I query the data (using flux) and I try to map them, I noticed that the two series were called in the Json Dataframe with the exact same name, and so I cannot map them, becouse only the first one is taken in consideration.

I tried fetching the data with two different queries, but the same problem occurs, and I don´t know what else to try, since I am not familiar with Json, there is a way to change the read only editor in order to change the name of the series? Anyone with the same problem?

**Comment by mikhail-vl** [comment]
@Alexstat98 Take a look at the documentation and YouTube tutorials: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/datasources/. It explains how to check `RefId` or field names to separate data.

**Comment by mikhail-vl** [comment]
@Alexstat98 If you can't distinguish fields by name in different series, then

  1. First example includes check for RefId: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/datasources/
  2. Access series directly like `data.series[0].fields` and `data.series[1].fields`, you don't need `map` in this case.

**Comment by punu1103** [comment]
Hi 
Congratulation for making nice plugin. 
i am trying to work on multi series data from ( influx db flux  query )  here is my data frame json . 
i am trying to make line charts . 
Could please guide me how to map data for echart . query can return  multiple series too. so i want to make it dynamic .
[
  {
    "schema": {
      "refId": "A",
      "meta": {
        "typeVersion": [
          0,
          0
        ],
        "executedQueryString": "from(bucket: \"HULDATA\")\r\n  |> range(start: 2024-03-23T07:40:35.904Z, stop: 2024-03-23T07:45:35.904Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HUL\")\r\n  |> filter(fn: (r) => r[\"Location\"] == \"HOMOGENISER\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Stg1_Pressure_UHP\")\r\n  |> stateDuration(unit: 1s, fn: (r) => true)\r\n \r\n"
      },
      "name": "HUL",
      "fields": [
        {
          "name": "_time",
          "type": "time",
          "typeInfo": {
            "frame": "time.Time",
            "nullable": true
          },
          "config": {}
        },
        {
          "name": "_value",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          },
          "labels": {
            "Batch": "IC-T-20247053",
            "Location": "HOMOGENISER",
            "_field": "Stg1_Pressure_UHP",
            "_start": "2024-03-23 07:40:35.904 +0000 UTC",
            "_stop": "2024-03-23 07:45:35.904 +0000 UTC"
          },
          "config": {}
        },
        {
          "name": "stateDuration",
          "type": "number",
          "typeInfo": {
            "frame": "int64",
            "nullable": true
          },
          "labels": {
            "Batch": "IC-T-20247053",
            "Location": "HOMOGENISER",
            "_field": "Stg1_Pressure_UHP",
            "_start": "2024-03-23 07:40:35.904 +0000 UTC",
            "_stop": "2024-03-23 07:45:35.904 +0000 UTC"
          },
          "config": {}
        }
      ]
    },
    "data": {
      "values": [
        [
          1711179636915,
          1711179641936,
          1711179646947,
          1711179651962,
          1711179656964,
          1711179661967,
          1711179666972,
          1711179671975,
          1711179676974,
          1711179681986,
          1711179686994,
          1711179692002,
          1711179696987,
          1711179701999,
          1711179707012,
          1711179712042,
          1711179717051,
          1711179722065,
          1711179727074,
          1711179732084,
          1711179737078,
          1711179742082,
          1711179747089
        ],
        [
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42
        ],
        [
          0,
          5,
          10,
          15,
          20,
          25,
          30,
          35,
          40,
          45,
          50,
          55,
          60,
          65,
          70,
          75,
          80,
          85,
          90,
          95,
          100,
          105,
          110
        ]
      ]
    }
  },
  {
    "schema": {
      "refId": "A",
      "name": "HUL",
      "fields": [
        {
          "name": "_time",
          "type": "time",
          "typeInfo": {
            "frame": "time.Time",
            "nullable": true
          },
          "config": {}
        },
        {
          "name": "_value",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          },
          "labels": {
            "Batch": "IC-T-20247054",
            "Location": "HOMOGENISER",
            "_field": "Stg1_Pressure_UHP",
            "_start": "2024-03-23 07:40:35.904 +0000 UTC",
            "_stop": "2024-03-23 07:45:35.904 +0000 UTC"
          },
          "config": {}
        },
        {
          "name": "stateDuration",
          "type": "number",
          "typeInfo": {
            "frame": "int64",
            "nullable": true
          },
          "labels": {
            "Batch": "IC-T-20247054",
            "Location": "HOMOGENISER",
            "_field": "Stg1_Pressure_UHP",
            "_start": "2024-03-23 07:40:35.904 +0000 UTC",
            "_stop": "2024-03-23 07:45:35.904 +0000 UTC"
          },
          "config": {}
        }
      ]
    },
    "data": {
      "values": [
        [
          1711179752101,
          1711179757114,
          1711179762120,
          1711179767129,
          1711179772141,
          1711179777161,
          1711179782174,
          1711179787179,
          1711179792188,
          1711179797190,
          1711179802199,
          1711179807212,
          1711179812207,
          1711179817209,
          1711179822222,
          1711179827219,
          1711179832248,
          1711179837263,
          1711179842276,
          1711179847271,
          1711179852285,
          1711179857292,
          1711179862295,
          1711179867311
        ],
        [
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42
        ],
        [
          0,
          5,
          10,
          15,
          20,
          25,
          30,
          35,
          40,
          45,
          50,
          55,
          60,
          65,
          70,
          75,
          80,
          85,
          90,
          95,
          100,
          105,
          110,
          115
        ]
      ]
    }
  },
  {
    "schema": {
      "refId": "A",
      "name": "HUL",
      "fields": [
        {
          "name": "_time",
          "type": "time",
          "typeInfo": {
            "frame": "time.Time",
            "nullable": true
          },
          "config": {}
        },
        {
          "name": "_value",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          },
          "labels": {
            "Batch": "IC-T-20247055",
            "Location": "HOMOGENISER",
            "_field": "Stg1_Pressure_UHP",
            "_start": "2024-03-23 07:40:35.904 +0000 UTC",
            "_stop": "2024-03-23 07:45:35.904 +0000 UTC"
          },
          "config": {}
        },
        {
          "name": "stateDuration",
          "type": "number",
          "typeInfo": {
            "frame": "int64",
            "nullable": true
          },
          "labels": {
            "Batch": "IC-T-20247055",
            "Location": "HOMOGENISER",
            "_field": "Stg1_Pressure_UHP",
            "_start": "2024-03-23 07:40:35.904 +0000 UTC",
            "_stop": "2024-03-23 07:45:35.904 +0000 UTC"
          },
          "config": {}
        }
      ]
    },
    "data": {
      "values": [
        [
          1711179872321,
          1711179877327,
          1711179882340,
          1711179887358,
          1711179892369,
          1711179897372,
          1711179902396,
          1711179907388,
          1711179912405,
          1711179917404,
          1711179922416,
          1711179927411,
          1711179932439
        ],
        [
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42,
          42
        ],
        [
          0,
          5,
          10,
          15,
          20,
          25,
          30,
          35,
          40,
          45,
          50,
          55,
          60
        ]
      ]
    }
  }
]

**Comment by mikhail-vl** [comment]
@punu1103 Have you tried to use the new Visual editor?

**Comment by punu1103** [comment]
Hi Mikhail 
yes i tried and it is showing only first frame . 
![yes](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/134124012/b06a6fec-0c90-4158-9f11-e58adf54aa07)

**Comment by punu1103** [comment]
data set has same field  in all frames . 
one more question with visual editor how to handle if query return different number of frame each time query runs .

**Comment by mikhail-vl** [comment]
@punu1103 This issue is closed.

  Please open a new issue for the visual editor question for tracking purposes.
