### ISSUE TITLE
Issue mapping values from datasource

### ISSUE THREAD

**Issue by Alexstat98** [VolkovLabs/volkovlabs-echarts-panel#231]
Hello,

I am trying to map series from my datasource in order to produce graph with multiple lines.
I am facing a particular issue: when I try to map the data, in the DataFrame JSON (from Query), I get the same name for different series of value, and so I can not refer them correctly when I try to map them.

![issue](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/93215867/79e65ad6-8730-4488-92fa-a9a1b1b490a8)

I saw both documentation and Youtube tutorial, but I can t find any reference to this particular case.

How can I solve that?

**Comment by mikhail-vl** [comment]
@Alexstat98 I saw your reply in https://github.com/VolkovLabs/volkovlabs-echarts-panel/issues/230 and replied there.

  Even, if I closed the issue, you can follow if you still have any questions, you don't need to open a new issue.
