### ISSUE TITLE
After selecting apache echart it shows error Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by ajinkya-mulay** [VolkovLabs/volkovlabs-echarts-panel#233]
I have installed this plugin in my local grafana instance which is 9.5.3 (OSS version) 

I have created a query and can see the data in a table format but when i select echart plugin i am getting below error.
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/95682162/ae9da83b-8184-4aa3-bde1-c98599bdf560)

Can you please suggest if something is wrong here?

**Comment by mikhail-vl** [comment]
@ajinkya-mulay It means that in the code you are trying to access using `.name` is not defined.

   If you are parsing data from the data source, then you are missing something in the code.

**Comment by ajinkya-mulay** [comment]
Thanks for the response but i have not changed anything in javascript code. My expectation was either it shows no data or some user friendly error.
