### ISSUE TITLE
[crosspost from stackoverflow] RangeError rendering echarts tree.

### ISSUE THREAD

**Issue by eostermueller** [VolkovLabs/volkovlabs-echarts-panel#235]
Hi,

Crossposting from StackOverflow.com with just a brief summary and a link:

We're trying to render a tree in this Grafana (v10.3.1 (00a22ff8b2)) plugin for apache echarts: [link](https://grafana.com/grafana/plugins/volkovlabs-echarts-panel/) (version 5.1.0) and we could use some help fixing the below "RangeError: Maximum call stack size exceeded" error.

https://stackoverflow.com/questions/77897257/rangeerror-rendering-tree-with-grafana-plugin-for-apache-echarts-from-volkovlabs

Thanks,

--Erik

**Comment by vitPinchuk** [comment]
Thank you for submitting an issue.
Based on the code from stackoverflow, I'm sure the issue was on the line 
`jsonTree = s.fields.find((f) => f.name === "JsonTree")`

We need to return the values. The values are recived in json format, so we need to return them as JSON.parse()

here is a correct sample:
`jsonTree = JSON.parse(s.fields.find((f) => f.name === "JsonTree").values[0])`

sample code with updated string:
```javascript
function stringify(obj) {
  let cache = [];
  let str = JSON.stringify(obj, function (key, value) {
    if (typeof value === "object" && value !== null) {
      if (cache.indexOf(value) !== -1) {
        // Circular reference found, discard key
        return;
      }
      // Store value in our collection
      cache.push(value);
    }
    return value;
  });
  cache = null; // reset the cache
  return str;
}
console.log("#@a");
let jsonTree;
console.log("#@b");
data.series.map((s) => {
  console.log("#@c");
  if (s.refId === "A") {
    console.log("#@d");
    jsonTree = JSON.parse(s.fields.find((f) => f.name === "JsonTree").values[0])
    console.log("#@e");
    console.log("Found the tree:" + stringify(jsonTree))
    console.log("#@f");
  }
});


return {
  tooltip: {
    trigger: 'item',
    triggerOn: 'mousemove'
  },
  animationDurationUpdate: 15000,
  animationEasingUpdate: 'quinticInOut',
  series: [
    {
      type: 'tree',
      data: [jsonTree],
      top: '1%',
      left: '20%',
      bottom: '12%',
      right: '20%',
      symbolSize: 5,
      edgeShape: 'polyline',
      initialTreeDepth: 5,
      lineStyle: {
        width: 1,
        color: '#664327',
      },
      label: {
        position: 'top'
      },
      leaves: {
        label: {
          position: 'right',
          verticalAlign: 'middle',
          align: 'left'
        }
      },
      emphasis: {
        focus: 'descendant'
      },
      expandAndCollapse: true,
      animationDuration: 550,
      animationDurationUpdate: 750
    }
  ]
};
``` 
Let us know if there is anything else
Thanks.
