### ISSUE TITLE
Apache Echart plugin allow to execute any arbitrary javascript function which can be used to perform unauthorized actions

### ISSUE THREAD

**Issue by ajinkya-mulay** [VolkovLabs/volkovlabs-echarts-panel#236]
We are using Apache Echart latest version and we observed when we add below code in Function section it gets executed. 
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/95682162/058478d7-cfb4-4eba-99ab-c0e5a14868de)

Do we have any solution to prevent the execution of such a code? 

Server: Grafana 9.5.3 OSS

**Comment by yusuf-multhan** [comment]
+1

**Comment by murtazaqa** [comment]
+1

**Comment by mikhail-vl** [comment]
@ajinkya-mulay Please take a look at the Security Guidelines: https://volkovlabs.io/plugins/security/

  Javascript in Grafana runs in a Sandbox, which prevent some malicious executions. If it's a concern, please use native plugins without JS customizations.

**Comment by ajinkya-mulay** [comment]
@mikhail-vl Thanks for the response. As per security guidelines admin and editor is allowed to add the javascript code. but editor can also add the such a arbitrary functions. is there any plan to validate the code return in the textbox before running it?

alternatively from where I can take the native plugins? which is exactly same as this plugin functionality wise?

**Comment by mikhail-vl** [comment]
@ajinkya-mulay We don't plan to validate code, which as I mentioned executing in a Grafana's Sandbox. Apache Charts panel used for a wide range of use cases and validating code can limit its existing functionality.

  Regarding, native panels, there is no one panel which can provide the same functionality as Apache ECharts. Depends on the use case, you can use Trend, 3D, Time Series, Pie Chart.

  Alternatively, you may look at Plotly panels, they also use JavaScript and have the same security concerns.
