### ISSUE TITLE
Need all nodes of ECharts tree to display clickable hyperlinks

### ISSUE THREAD

**Issue by eostermueller** [VolkovLabs/volkovlabs-echarts-panel#244]
Hi,

We're trying to use this EChart:  https://echarts.apache.org/examples/en/editor.html?c=tree-polyline

We'd like to get every node of the tree to have or somehow include a clickable hyperlink.  Left clicking would launch the link in a separate tab.  Perhaps this functionality exists?  If not, pls consider this an enhancement request.

This link ( https://stackoverflow.com/a/38308333/2377579 ) shows the javascript required to create a link on a single echart node, and presumably the volkovlabs-echarts-panel would need to navigate to each tree node and use (something like) this on to create each node's link.

For the c=tree-polylink example linked above, mouse-hovering over a single node displays a nice hover-over box displaying a numeric like this:

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/175773/9f2c6d7b-59dc-4a79-8d8b-606f32e02a8c)

For us, it would preferable to have the hyperlink show up as a new line in that hover-over box, as long as the user could easily activate the link before the hover-over box disappears :-).
But many applications might just want the main node text (name attribute) to be clickable to the href.
Here is a snippet of data for the above linked echarts sample tree c=tree-polyline:

    {
       name: 'display',
       children:
         { name: 'DirtySprite', value: 8833 },
        { name: 'LineSprite', value: 1732 },
        { name: 'RectSprite', value: 3623 }
      ]
    },

The href for each node could be added like this:

    {
       name: 'display',
       children:
         { name: 'DirtySprite', value: 8833, href: 'https://www.google.com', linkDisplayText: 'Google' },
        { name: 'LineSprite', value: 1732, href: 'https://www.wikipedia.org/', linkDisplayText: 'Wikipedia'  },
        { name: 'RectSprite', value: 3623, href: 'https://data.gov/', linkDisplayText: 'data.gov'  }
      ]
    },

This could be helpful for many different kinds of data in a tree.  Org chart -- could click into detail on a single user.  List of brick-and-mortar locations on separate continents -- click into details for each location.  Tree as an outline of a document like some country's Constitution...click to display that Article/Amendment/section/etc..

Thanks for sharing this great plugin,

--Erik

**Comment by mikhail-vl** [comment]
@eostermueller Tooltips in Apache ECharts are customizable: https://echarts.apache.org/en/option.html#grid.tooltip.formatter.

  You can easily add hyperlinks to the tooltip.
