### ISSUE TITLE
Formatted data option

### ISSUE THREAD

**Issue by jacksongoode** [VolkovLabs/volkovlabs-echarts-panel#253]
This is more of a curiosity rather than an issue. I'm also a plugin dev and one of my users realized that the formatted data toggle is not available on our plugin but it is available in the official built-in Grafana plugins. I'm wondering if you found a way to show this toggle within your plugins or if this is a basic limitation of any third-party plugins.

<img width="740" alt="image" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/54308792/aafc6bd5-704d-4f37-b27f-de97903bd308">

vs.

<img width="740" alt="image" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/54308792/4b8c5fea-837e-4893-a90d-b3e431fc3a7d">

**Comment by mikhail-vl** [comment]
@jacksongoode I can see the formatted data is available for the Apache ECharts, which mean that it's available for the 3rd party plugins. I don't remember any special configuration for it. It may be related to the used data source.

![Screenshot 2024-02-14 at 11 41 59 PM](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/9510c2ca-f315-4072-823a-8f115230eb2b)

**Comment by jacksongoode** [comment]
Hmm, its interesting because your Data Manipulation plugin doesn't offer this unless I'm mistaken.

**Comment by mikhail-vl** [comment]
@jacksongoode I just double checked for the Data Manipulation plugin and it works as expected as well. I am using Grafana 10.3.1:

![Screenshot 2024-03-24 at 10 22 12 PM](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/6944c7e1-229f-4d62-8d0c-504001a2a8ad)
