### ISSUE TITLE
#ASK Apache ECharts Panel 5.2.0

### ISSUE THREAD

**Issue by itsnull12** [VolkovLabs/volkovlabs-echarts-panel#258]
Hi VolkovLabs Team,

I saw Apache EChart has been upgraded to 5.2.0. Is there any documentation or YouTube short videos for this version?
Especially on the feature "Add a visual editor to work with data sources (#211)" how does it work ?

Thank you

**Comment by mikhail-vl** [comment]
@itsnull12 We are working on a blog and Shorts. Meanwhile, you can check examples at https://echarts.volkovlabs.io/d/pL5iH7FVk/home?orgId=1&editPanel=23

**Comment by itsnull12** [comment]
@mikhail-vl  sounds good! thank you mikhail.

**Comment by mikhail-vl** [comment]
Will be resolved in https://github.com/VolkovLabs/volkovlabs.io/issues/581 for the Business Charts 6.0.0.
