### ISSUE TITLE
Adding new GeoJSON files to volkovlabs-echarts-panel/maps and how to use them properly?

### ISSUE THREAD

**Issue by tengdagg** [VolkovLabs/volkovlabs-echarts-panel#259]
Adding new GeoJSON files to volkovlabs-echarts-panel/maps and how to use them properly. Please help me.

**Comment by mikhail-vl** [comment]
@tengdagg We have examples in the documentation how to load maps dynamically: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/maps/geojson/#dynamic-maps-loading

  You can upload maps to any external resource or the `maps` folder and then load them dynamically.
