### ISSUE TITLE
Request for Compliance with Apache ECharts Trademark Policy

### ISSUE THREAD

**Issue by Ovilia** [VolkovLabs/volkovlabs-echarts-panel#264]
Hello Team,

First of all, I want to express my appreciation for your work on this project. The integration of ECharts into Grafana through your plugin has been incredibly useful and it’s evident that a lot of effort has gone into making it as effective as it is. However, I’ve noticed some issues concerning the Apache ECharts trademark that I believe need addressing to ensure compliance with the guidelines set out by The Apache Software Foundation.

### 1. Project Description Issue:

The current description of the project seems to be misusing the Apache ECharts brand. According to the Apache trademark policy available at https://www.apache.org/foundation/marks/#products, projects that are not officially part of Apache need to ensure they don’t use the brand name in a way that suggests they are the original Apache project.

**Suggested Change:**
To comply with this policy, a name like “VolkovLabs's Plugin for Grafana powered by Apache ECharts” or any variant that clearly indicates the nature of the project while acknowledging Apache ECharts as the underlying technology would be more appropriate. This adjustment would help in avoiding confusion and ensuring respect for Apache’s brand guidelines.

### 2. Lack of Trademark Acknowledgment:

I’ve also observed that there’s no footer or documentation section that acknowledges Apache and ECharts as trademarks or registered trademarks of The Apache Software Foundation. As per the FAQs on trademark usage (https://www.apache.org/foundation/marks/faq/#attribution), it’s important to include such an acknowledgment to inform users of the trademark status of the terms.

**Suggested Change:**
Including a simple statement in the footer of the project’s main page and in the README file would suffice. For example:
“The Apache Software Foundation Apache ECharts, ECharts, Apache, the Apache feather, and the Apache ECharts project logo are either registered trademarks or trademarks of the Apache Software Foundation.”

These changes would not only ensure compliance with Apache’s trademark policy but also demonstrate good faith and respect for the intellectual property rights of others. It is crucial that **both the website and the GitHub README and project description are updated** to reflect these changes. I believe these adjustments will safeguard the project from potential legal complications and further align it with the open-source community's standards and expectations.

Thank you for considering these suggestions. I look forward to your response and am happy to discuss further if needed.

**Comment by mikhail-vl** [comment]
@Ovilia thank you for letting us know.

  We gladly follow the guidelines to update the project description and add Trademark Acknowledgement.

**Comment by mikhail-vl** [comment]
@Ovilia We updated plugin description, README and Documentation (https://volkovlabs.io/plugins/volkovlabs-echarts-panel/).

  Please let me know if there is anything else.
