### ISSUE TITLE
Plugin signature checksum issue in Grafana Enterprise v10.3.3

### ISSUE THREAD

**Issue by cheesengoon** [VolkovLabs/volkovlabs-echarts-panel#267]
Hi Volkovlabs Team,
I'm facing issue loading the Volkovlabs Echarts plugin into my Grafana Enterprise instance. The error message is indicating that the file checksum for "img/examples.png" do not match the signature 

1. Downloaded Volkovlabs Echarts v5.3.0 and placed in Grafana Enterprise v10.3.3 plugins directory
2. Started Grafana Enterprise
3. During the plugins.signature.validation stage, it failed to validate for Volkovlabs Echarts plugin

**Expected behavior**
Expected plugin to validate and load successfully and able to create a Echarts panel in a dashboard.

**Environment:**
Local instance that is deployed in local Kubernetes cluster

**Comment by cheesengoon** [comment]
Hi @mikhail-vl ,

I have managed to resolve issue on my end. It was a false positive from my end.

Thanks.

**Comment by mikhail-vl** [comment]
@cheesengoon Thank you for reaching out. It's strange that v5.3.0 works as expected from Grafana Cloud, but I was able to reproduce it downloading directly from GitHub.

  What did you figure out?
