### ISSUE TITLE
Where is the plugin panel definition stored

### ISSUE THREAD

**Issue by beau-tang** [VolkovLabs/volkovlabs-echarts-panel#275]
Hi there. 

I have a bunch of dashboards that I work on and I sometimes need to find the right dashboards to change. I've built a panel querying the grafana mysql instance so that I can search for strings, e.g. a table name, to find the dashboards that I need to change.

I'm using some of your plugins for panels in the dashboards and they're terrific, but I can't find my panel code for them in mysql. Is it in there, or somewhere else that I could query? Specifically I'm using apache echarts and dynamic text. I expect that I'll use others in time. 

Many thanks.

**Comment by mikhail-vl** [comment]
@beau-tang Panel code for Apache ECharts, Dynamic Text and any other panels are stored in the dashboards.

  If you open Dashboard Settings -> JSON Model and look inside, you will all the panel properties.
  You should be able to find them in the Grafana configuration database as well.
