### ISSUE TITLE
Google Map API is not loaded error in Echarts

### ISSUE THREAD

**Issue by ehsan007** [VolkovLabs/volkovlabs-echarts-panel#278]
When using your GMap example for Echarts (v6), the chart doesn't load, and it gets stuck with an error message indicating that the Google Map API is not loaded. Waiting on the page does not resolve the issue.

**Comment by mikhail-vl** [comment]
@ehsan007 It works on our examples instance: https://echarts.volkovlabs.io/d/X1mkMIFVz/geo-map?orgId=1&editPanel=13

![Screenshot 2024-04-03 at 7 03 10 PM](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/47795110/69556896-b6cb-48f1-8d4a-13a11c93a3f1)
