### ISSUE TITLE
Breaking changes when replacing `data.series` with `context.panel.data.series`

### ISSUE THREAD

**Issue by padmakr** [VolkovLabs/volkovlabs-echarts-panel#279]
I recently migrated from Grafana 9.5.3 to Grafana 10.4.0 in 3rd week of March

The volkovlabs-echarts-panel renered well with a few minor changes that hadd null checks.

But recently when I re deployed my grafana containers, and tried to push changes to dashboard through provisioning, the plugin blindly prefixed `context.panel` to anything that had `data.series`.

Sensing that I need to add this change for all dashboards, I edited the dashboard JSON externally to add `context.panel`.
On re-deploying the panel I hoped to see it without breaking errors.

However I think it is adding `context.panel` without checking if its already there in the code.
The screenshot below can explain this

![grafana-volkov-issue](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/43269858/1be5ddb5-ded1-4220-bffd-82695e18a64f)

Is there a way to use volkovlabs 5.0.0 with grafana version 10.4.0

**Comment by mikhail-vl** [comment]
@padmakr That's expected behaviour. In Business Charts v6 we introduced breaking change to use `context` for all parameters.

  Migration happens automatically and depends on the `pluginVersion` property, which set to v6 when it's migrated automatically.
  When you edited the dashboard JSON manually, please add `pluginVersion": "6.0.0"` and it will work as expected.

  Depends on your installation, you can specify to use the specific version of the plugin.

**Comment by padmakr** [comment]
@mikhail-vl Thank you for the response.

The following things are still little unclear to me.
1. What if I chose to add 'context.panel' prefix manually in the dashboard jsons?
2. What if I still want to use volkov-echarts-panel 5.0.0? Is that possible by changing `"pluginVersion": "5.0.0"` in dashboard jsons?
3. 
> Depends on your installation, you can specify to use the specific version of the plugin.
If I am building a custom grafana image can I specify this way
`GF_INSTALL_PLUGINS: volkovlabs-echarts-panel 5.0.0`

**Comment by mikhail-vl** [comment]
@padmakr Let me explain:

1. Adding `context.panel` manually should be done together with updating `pluginVersion` for each panel.
2. Dashboard will displayed using installed plugin in Grafana. Only configuration will be migrated if version differs.
4. Specific plugin version should be installed by specifying archive directly: https://grafana.com/docs/grafana/latest/administration/plugin-management/
