### ISSUE TITLE
Could not find root URL that matches running application URL" plugin=volkovlabs-echarts-panel appUrl=http://xxxxxx:3000/grafana/ rootUrls="unsupported value type"

### ISSUE THREAD

**Issue by stdnt-xiao** [VolkovLabs/volkovlabs-echarts-panel#28]
Skipping loading plugin due to problem with signature
Hi, When i was trying to install this plugin. i found out below error log from my /var/log/grafana/grafana.log, BTW: I already configureate this allow_loading_unsigned_plugins = volkovlabs-echarts-panel in my grafana.ini

logger=plugin.manager t=2022-07-04T10:59:28.958393913+08:00 level=info msg="Plugin registered" pluginId=input

logger=plugin.loader t=2022-07-04T10:59:29.082900685+08:00 level=warn msg="Could not find root URL that matches running application URL" plugin=volkovlabs-echarts-panel appUrl=http://localhost:3000/grafana/ rootUrls="unsupported value type"

logger=plugin.loader t=2022-07-04T10:59:29.082991956+08:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=volkovlabs-echarts-panel status=invalid```

and set conf grafana.ini

server:
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path: true

**Comment by stdnt-xiao** [comment]
[https://github.com/VolkovLabs/volkovlabs-echarts-panel/issues/17#issuecomment-1173998642](url)

I have solved this problem.
I am closing the issue for now.

**Comment by mikhail-vl** [comment]
@stdnt-xiao Thank you for use the plugin. You just need to remove the `MANIFEST.txt` file, and you should be good.

Please let us know if there is anything else.
