### ISSUE TITLE
Capture onClick event on a line chart

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#280]
Greetings,

How can one capture click even on an apache echart like

I saw how to do it here, but not sure what the dom id is for apache echart, is it dynamic or static?

https://echarts.apache.org/en/tutorial.html#Events%20and%20Actions%20in%20ECharts

Thanks!

**Comment by mikhail-vl** [comment]
@yosiasz Please take a look at our documentation: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events/

  When you received the Click event, you car see all the data and parameters in the `params`.
