### ISSUE TITLE
Bi-directional shared crosshair between grafana time-series and echarts chart

### ISSUE THREAD

**Issue by briha** [VolkovLabs/volkovlabs-echarts-panel#285]
Hi,

#125 mentions a method to obtain a shared crosshair between echarts and grafana panels. That method is as follows:
```javascript
context.panel.chart.on('mouseover', (params) => {
  var event = params.event;
  context.panel.chart.dispatchAction({
    type: 'showTip',
    x: event.offsetX,
    y: event.offsetY,
  });
});
context.panel.chart.on('globalout', (params) => {
  context.panel.chart.dispatchAction({
    type: 'hideTip'
  });
});
````

Unfortunately, this method seems to have no effect. I tested it both locally and on echarts.volkovlabs.io.
My questions are:
- How do I make this work?
- From what I understand, this method would only display the global crosshair on grafana panels from echarts and not the other way around. How do I obtain both (i.e., what event do I need to listen to for the other way around)?
- Even better, where is the documentation for those events/actions? The events used here (`mouseover` and `globalout`) aren't mentioned on https://volkovlabs.io/grafana/developer/eventbus/ and I can't find any documentation for the `dispatchAction` (actions and parameters) – which I would appreciate having.

**Comment by mikhail-vl** [comment]
@briha We are working on a new blog post about using Shared Crosshair and EventBus to send events to and from Business Charts panel.

**Comment by diliprk** [comment]
Very much like this example [grafana play candlestick dashboard]( https://play.grafana.org/d/candlestick/candlestick?orgId=1 ) I have created two visualizations using VolkovLabs eCharts (Business Charts) library, the first visualization is only the raw candlesticks and the second visualization just shows the volume bars . Of course the second visualization can be merged into the first visualization by using the `grid` option in echarts` but imagine the second visualization could also be some other indicator plot like the MACD.  Below is a screenshot of my grafana dashboard

![Grafana_Dashboard_Test](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/20330371/c3cebf9c-13e7-4453-9e9a-124e69fc6b17)


My questions are 
1.) in the [Grafana Example]( https://play.grafana.org/d/candlestick/candlestick?orgId=1 ) using native grafana candlestick charts visualisations, we see that the movement of the mouse over crosshairs and tooltips are linked, how do I create the same effect with the eChart plots?

2.) Similarly can we also link the `dataZoom` slider option across the 2 eCharts plots

3.) And finally the `axisPointer` (below the X-axis) can also be linked to show tooltips over multiple eCharts plots?


Best Regards,
Dilip

**Comment by vitPinchuk** [comment]
@diliprk Thank you for your questions
  
1) The main issue, on shared crosshair between panels, describe in our new blog post. You can find it useful and helpful.   
   [Panels interconnectivity in Grafana via EventBus](https://volkovlabs.io/blog/echarts-shared-crosshair-and-eventbus-20240520/)

2) Example with `dataZoom` we have in our documentation:
  [The Data Zoom feature allows you to select a time period on the chart for zooming in (datazoom based on time range)](https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events/#update-of-time-range)  
 
3) Please check Example with markline and tooltip and option configuration for charts 
[candlestick-brush](https://echarts.apache.org/examples/en/editor.html?c=candlestick-brush) 

Thank you

**Comment by briha** [comment]
@vitPinchuk thank you very much, this seems like exactly what I was looking for!

**Comment by briha** [comment]
It seems with sparse data, using the zrender event to move the cursor on other panels works better.
```typescript
context.panel.chart.getZr().on("mousemove", function (params) {
  const pointInGrid = context.panel.chart.convertFromPixel('grid', [params.offsetX, params.offsetY]);

  let data = {
    type: "data-hover",
    payload: {
      point: {
        time: pointInGrid[0],
      },
    },

    origin: {
      path: ["echarts-walk-1"],
    },
  };
  context.grafana.eventBus.publish(data);
});
```

Additionally, having sparse data in a grafana timeseries panel means that the cursor on the echarts panel jumps between points, instead of being smoothly following like it does on all other panels (and the other way around, when using the zrender event). Any suggestion on how to fix that? i.e., not have the cursor jump between data points but just follow the grafana cursor?  @vitPinchuk

**Comment by mikhail-vl** [comment]
@vitPinchuk Please follow-up with the question.

**Comment by vitPinchuk** [comment]
@briha  Thank you for your questions

1. The main issue, on shared crosshair between panels, described in our new blog post. This implementation is generic and basic, which can be used as an adaptation for different variants.

2. Using .getZr() is one option. This implementation probably works better for sparse data. It also allows you to send data by moving the cursor on the canvas instead of pointing to the points on the chart.  But when you move the cursor over the Echarts chart, the markline will only appear on the chart points (and looks like a jump) 
Here is an example [line-marker](https://echarts.apache.org/examples/en/editor.html?c=line-marker)
The same behavior when navigating with the cursor 

This is the basic behavior for Echarts charts. Note that the implementation of TimeSeries charts is different. 

Therefore, the implementation of changing and drawing of Echarts can have many different variants and can have a unique implementation (additional functions, etc.) not related to crosshair between charts.

**Comment by briha** [comment]
So, there's no way to "smoothly" show a line on the x-position of the business chart panel that is synchronised with my cursor on the Grafana timeseries panels, for sparse data?
