### ISSUE TITLE
 Is it possible to use Grafana Dashbaord avriables in volkovlabs-echarts-panel?

### ISSUE THREAD

**Issue by gotoworld** [VolkovLabs/volkovlabs-echarts-panel#286]
Is it possible to use grafana dashbaord’s variables in Echarts plugin?

i use below code to get the value in dashboard, is there any better way to do it?
var startTime=document.getElementById(“_from”).title ;

with below script, it’s not working

<img width="1382" alt="image" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/8605471/e6fb71d3-54fa-4d37-9531-755e1111780a">

**Comment by gotoworld** [comment]
And we found that the grafana dashborad variables is can't be get in javascript.

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/8605471/202d0cc9-dcf0-4031-8adf-06aa7d51965b)

**Comment by gotoworld** [comment]
It seems that the issue is not related to the volkovlabs-echarts-panel plugin. It looks like Grafana Dashboard variables cannot be fetched from the web page.

**Comment by vitPinchuk** [comment]
Hi, @gotoworld 
use context.grafana.replaceVariables(string) to get variable 
here is example 
I added new variable `testVar`
you can use `' '` (single quotes) or `" "` (double quotes) 
`console.log('console >> ', context.grafana.replaceVariables('${testVar}'))`
[Link to documentation](https://volkovlabs.io/plugins/volkovlabs-echarts-panel/variables/)  
  

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/bdea29e0-bbb9-46f7-b161-09b926520615)
