### ISSUE TITLE
How can I get Grafana Dashboard variables in Panel Javascript？

### ISSUE THREAD

**Issue by gotoworld** [VolkovLabs/volkovlabs-echarts-panel#287]
How can I get Grafana Dashboard variables, such as the $__from variable, in the Echarts panel? When I use the following JavaScript code to get this variable, I can’t retrieve it. However, it can be displayed in the panel title.

> the variable working in panel title
<img width="1371" alt="image" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/8605471/1f90b8dc-719c-4797-b982-f4a30a5f6315">

> the variable NOT working in Javascript
<img width="1362" alt="image" src="https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/8605471/de4524c7-f7a3-441d-a514-66e5c2073da9">

**Comment by vitPinchuk** [comment]
Hi, @gotoworld 
use context.grafana.replaceVariables(string) to get variable 
here is example 
I added new variable `testVar`
you can use `' '` (single quotes) or `" "` (double quotes) 
`console.log('console >> ', context.grafana.replaceVariables('${testVar}'))`
[Link to documentation](https://volkovlabs.io/plugins/volkovlabs-echarts-panel/variables/)  
  

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/bdea29e0-bbb9-46f7-b161-09b926520615)
