### ISSUE TITLE
Variable not accessible

### ISSUE THREAD

**Issue by lesh3000** [VolkovLabs/volkovlabs-echarts-panel#288]
Hi,
We are doing some OpenSearch data postprocessing, using Business Charts code console and JS. Somehow It stopped working last night.
It looks like the reason some variables are not available anymore like for example we used to call to the following variable: context.panel.data.series[0]['name'] It looks like now 'name' property does not exist anymore in the corresponding object.
This is just one example, in general it looks like the data object structure has been changed. 
Is it something temporary or instead intentional?

I checked the Query output that is made by OpenSearch and it looks like there everything as it was before. 
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/30319422/1fad4df4-c877-4dea-9ea9-d3765b276969)
Before with the name property I could access the column name.

Furthermore, when it comes to group by queries it looks like the data for different layers is missing

**Comment by vitPinchuk** [comment]
Hi @lesh3000 
I believe it depends on the dataSource.
As an example 
I use Static data Source. I have name for my data source, and I see it property in console
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/19167f57-de4b-4c7a-afdd-2b3b87ed2f0b)

After tthat I change my data Source to Grafana -> Random Walk
and my series doesn't have property name
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/9397072a-9a64-4de2-8d5c-7357cfcd852c)

**Comment by lesh3000** [comment]
Thank you!
So you think changes here are related to datasource updates if any?

**Comment by vitPinchuk** [comment]
@lesh3000 yes

**Comment by lesh3000** [comment]
thank you so much I will try to rollback on the datasource, indeed rolling back to 5.3.0 did not resolve the issue
