### ISSUE TITLE
ECharts connect function support

### ISSUE THREAD

**Issue by miguel-toracom** [VolkovLabs/volkovlabs-echarts-panel#290]
Hi,

Is the `echarts.connect` function supported?

I am looking to connect multiple charts using the `echarts.connect` function as described in the documentation [here](https://echarts.apache.org/en/api.html#echarts.connect).

Below is an example of what I want to achieve:
[CodePen Example](https://codepen.io/sjcobb/pen/zYRVpGK)

![ezgif-2-bd71e2443f](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/153656891/3aec9a5f-ce67-4dc0-9536-d10d994d657a)

Thank you in advance for your help.

**Comment by miguel-toracom** [comment]
Hi,

I think I have solved the issue with connecting multiple charts using `echarts.connect`.

Here's what I did:

1. At the beginning of each chart configuration, I included this line:

```javascript
context.panel.chart.group = 'group1';
```
2. In one of the chart configurations, I also added this line:

```javascript
context.echarts.connect('group1');
```

**Comment by mikhail-vl** [comment]
@miguel-toracom ECharts connect can be a good options, but in the Grafana I would recommend to use EventBus, which is a recommended way to send events between panels, both native and community.

  @vitPinchuk is writing a blog post covering it and it's planned for the next week.

**Comment by mikhail-vl** [comment]
Related issue https://github.com/VolkovLabs/volkovlabs-echarts-panel/issues/285

**Comment by miguel-toracom** [comment]
Thank you, @mikhail-vl, for your suggestion and @vitPinchuk for the upcoming blog post. I'm looking forward to it!

**Comment by mikhail-vl** [comment]
@miguel-toracom Blog post is a work in progress, but the code is working: https://github.com/VolkovLabs/volkovlabs.io/pull/667/files

  You are welcome to try it out, while we finishing the blog post.
