### ISSUE TITLE
[Question] How can I move clicked node to the center of a echarts Graph.

### ISSUE THREAD

**Issue by tiantangkuohai** [VolkovLabs/volkovlabs-echarts-panel#296]
I'm building a Graph with volkovlabs-ehcarts-panel. I need to make clicked node centralized. How can I achieve this?

**Comment by vitPinchuk** [comment]
Hi, @tiantangkuohai
We have a good blog post that may be helpful in solving this problem 
https://volkovlabs.io/plugins/volkovlabs-echarts-panel/tutorials/graph/
