### ISSUE TITLE
Disable default onclick behaviour

### ISSUE THREAD

**Issue by lesh3000** [VolkovLabs/volkovlabs-echarts-panel#297]
Hi,
I am trying to disable onclick behaviour on sunburst panel 
https://echarts.volkovlabs.io/d/pL5iH7FVk/home?orgId=1&refresh=5s&editPanel=10
by adding:
`context.panel.chart.off("click");`
before the return statement
somehow the default behavior is still there,
If I add 
`context.panel.chart.on("click", (params) => {
  context.grafana.notifySuccess(["Event", "On Click"]);
  context.panel.chart.resize(); // to redraw visualization
});`
the alert appears there, but grapoh behaviour is still the same.
I am doing something wrong?

**Comment by mikhail-vl** [comment]
@lesh3000 We have an example in the documentation how to implement it: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/events/#mouse-click

```
/**
 * On Mouse Click
 */
context.panel.chart.off("click");
context.panel.chart.on("click", (params) => {
  context.grafana.notifySuccess(["Event", "On Click"]);
  context.panel.chart.resize(); // to redraw visualization
});

/**
 * On Double Click
 */
context.panel.chart.off("dblclick");
context.panel.chart.on("dblclick", (params) => {
  context.panel.chart.resize();
});
```
