### ISSUE TITLE
How to implement GeoJSON map refresh only series?

### ISSUE THREAD

**Issue by SeraphicPrairieWolf** [VolkovLabs/volkovlabs-echarts-panel#303]
For example, the map of Canada in the GeoJson document example:
https://volkovlabs.io/plugins/volkovlabs-echarts-panel/maps/geojson/
After setting automatic refresh, the refresh of the panel causes the map of Canada to be reloaded, which causes blinking. I want to refresh only the series data that changes.

It seems that the built-in world and US maps will not have such issues, but I was unable to add map json files for the plugin.

This is my test panel:
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/168157738/47e56b25-192b-4c6a-8df6-553fa1a289b8)

**Comment by vitPinchuk** [comment]
@SeraphicPrairieWolf Thank you for your question.

Whenever we load additional GeoJSON maps dynamically using JQuery it happens asynchronicity  

To achieve the goal of updating the data source and then updating the map, and not causing the map to blink, we need to make this process synchronous.

As example, I use `Business Input Data Source` (Static Data Source), but you can use `Infinity` or sth. else
I use a map for Canada. We need return JSON for map from data source. In this case we return JSON from data source and register map, synchronically. And our code should return options for Echart

We will update our documentation on this section. 
Thank you

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/553f6f18-2963-493c-8afe-4cacad36c9e1)

code to copy: 
```js

const cityList = context.panel.data.series[0].fields[0].values
const latidList = context.panel.data.series[0].fields[1].values
const longList = context.panel.data.series[0].fields[2].values
const valueList = context.panel.data.series[0].fields[3].values
const json = context.panel.data.series[1].fields[0].values[0]

const mapName = "Canada";


/**
 * Register map
 *
 */
context.echarts.registerMap(mapName, { geoJSON: json })

/**
 * Return settiings
 *
 */
return {
  title: {
    text: mapName,
    left: "right",
  },
  geo: {
    map: mapName,
    roam: true,
  },
  series: cityList.map((city, index) => ({
    type: "scatter",
    coordinateSystem: "geo",
    data: [
      {
        name: city,
        value: [
          parseFloat(latidList[index]),
          parseFloat(longList[index]),
          parseFloat(valueList[index]),
        ]
      }
    ],
    label: {
      show: true,
      position: "top"
    }
  }))
};

```

In the video below you can notice how the map for `China` is blinking when auto-update is enabled. For China, I left the jQuery approach as an example. `Canada` map use json from data source

[Запись экрана от 08.07.2024 16:11:13.webm](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/b4a9a8c7-d41c-4f49-95d1-49b0bcf8395f)

**Comment by mikhail-vl** [comment]
Example updated in the documentation: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/maps/geojson/#dynamic-maps-loading

**Comment by SeraphicPrairieWolf** [comment]
Thank you very much. It works for me. I ended up using grafana's variables to store the map JSON data in a way that didn't affect the data table. Share it with friends who need it
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/168157738/1dc08df5-f065-46b9-9317-e2ef818749ce)
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/168157738/e76b4acc-f4e8-4452-92b2-0e6365ef719b)
