### ISSUE TITLE
Liquid Fill Data Link not working

### ISSUE THREAD

**Issue by MrIngenieur** [VolkovLabs/volkovlabs-echarts-panel#304]
I can not manage to populate the Liquid Fill Template with data from Grafana. 
I tried several versions to link data source but nothing really worked. 
Using Grafana 11. 
Is there any chance to get a version of the code which includes data linkage and where „data:“ is not mapped to constant values?
That would be really great. THANK YOU so much in advance

I tried all the options explained here, but nothing did work:
https://volkovlabs.io/plugins/volkovlabs-echarts-panel/datasources/

I also tried the code from the video, but that also did not work or maybe is outdated in newer versions. 

That‘s the Template i did copy paste:

`return {
  series: [{
    type: 'liquidFill',
    radius: '90%',
    waveAnimation: false,
    animationDuration: 0,
    animationDurationUpdate: 0,
    data: [0.6, 0.5, 0.4, 0.3]
  }]
}; `

**Comment by mikhail-vl** [comment]
@MrIngenieur We have an example you can use to create Liquid Fill: https://echarts.volkovlabs.io/d/pL5iH7FVk/home?orgId=1&refresh=5s&editPanel=25

  I just updated our example Grafana instance to 11.1.0 and it works as expected.

**Comment by MrIngenieur** [comment]
my problem is the following:
all your examples show the data connection with static values like: 
`data: [values[0] / 100, values[1] / 100, values[2] / 100]`

but nowhere out there is a working example where you use a grafana query to feed the Liquid Fill Template with data. 

My problem was NOT that Grafana 11 is not working with Liquid fill. The problem was, that there is now working way to get real data into that template other than your static values. 

All the description and documentation seems to be outdated and not working properly.

**Comment by vitPinchuk** [comment]
@MrIngenieur Thank you for clarification.

I use [Business Input Data Source](https://github.com/volkovlabs/volkovlabs-static-datasource) (Static Data Source)
To make example data source:   
  
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/c91dc2bc-b2fa-4aee-a928-3719245beca0)
  
To take values from second column like `Value` or `E3DC_SOC_Disp.mean`, we can find field by type, or by name
Please use console.log('context:', context) to see all available data and options in code editor.
Here is my example: 
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/426274e5-87f3-4fb1-aed6-f6e2ef9d0611)

code to copy: 
```js
/**
 * Define by field type
 */
const wavesFirstApproach = context.panel.data.series.map((s) => {
  values = s.fields.find((f) => f.type === 'number').values;
  return values
})
console.log('wavesFirstApproach: ', wavesFirstApproach)

/**
 * Define by field name
 */
const wavesSecondApproach = context.panel.data.series.map((s) => {
  values = s.fields.find((f) => f.name === 'Value').values;
  return values
})
```

for your example I guess it should be 
```js
/**
 * Define by field name
 */
const waves = context.panel.data.series.map((s) => {
  values = s.fields.find((f) => f.name === 'E3DC_SOC_Disp.mean').values;
  return values
})
```

After we find appropriate field we need transform values, in current moment my values for `waves` it is `[61, 55, 40, 41, 44, 74, 33, 25]`

![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/ad74ba7c-bee7-4121-811b-1a8e9b71963d)

code to copy: 
```js

/**
 * Define by field name
 * Change Value to appropriate name field from your data frame
 *  f.name === 'E3DC_SOC_Disp.mean'
 */
const waves = context.panel.data.series.map((s) => {
  values = s.fields.find((f) => f.name === 'Value').values;
  return values
})

/**
 * Transform
 */
const transformWaves = waves[0].map((wave) => {
  return Number(wave)/100
})


return {
  series: [{
    type: 'liquidFill',
    radius: '90%',
    data: [...transformWaves]
  }]
};
```
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/7d925d89-86f1-4e43-a8ba-da93c67ee2a1)



Please, try to use this approach for your case. It should help resolve your issue, thank you

**Comment by MrIngenieur** [comment]
Thanks for your great support, 

i don't get errors as long as I leave it to "Value", but as soon as I put my "E3DC_SOC_Disp.mean" in there, I get this error:
ECharts Execution Error
undefined is not an object (evaluating 's.fields.find((f) => f.name === 'E3DC_SOC_Disp.mean').values')

any idea why?
This would be my code:

```

/**
 * Define by field name
 * Change Value to appropriate name field from your data frame
 *  f.name === 'E3DC_SOC_Disp.mean'
 */
const waves = context.panel.data.series.map((s) => {
  values = s.fields.find((f) => f.name === 'E3DC_SOC_Disp.mean').values;
  return values
})

/**
 * Transform
 */
const transformWaves = waves[0].map((wave) => {
  return Number(wave) / 100
})


return {
  series: [{
    type: 'liquidFill',
    radius: '90%',
    data: [...transformWaves]
  }]
};
```

**Comment by vitPinchuk** [comment]
@MrIngenieur 

Please use console.log('context:', context) to see all available data and options in code editor.

I added `f.name === 'E3DC_SOC_Disp.mean'` as example to expected name for field. But, you need to check in console name of your field which in data frame (series)
Probably there is different field name, not a `E3DC_SOC_Disp.mean`
```js
/**
 * Define by field name
 * Change Value to appropriate name field from your data frame
 *  f.name === 'E3DC_SOC_Disp.mean'
 */
console.log('context:', context)
console.log('context.panel.data:', context.panel.data)
const waves = context.panel.data.series.map((s) => {
  values = s.fields.find((f) => f.name === 'Value').values;
  return values
})

/**
 * Transform
 */
const transformWaves = waves[0].map((wave) => {
  return Number(wave) / 100
})


return {
  series: [{
    type: 'liquidFill',
    radius: '90%',
    data: [...transformWaves]
  }]
};
```
![image](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/146737590/4ffc616c-f6a4-4dca-b3df-daf8cb1de8bb)

**Comment by MrIngenieur** [comment]
Thanks for the Update.. we are getting closer... it seems that in the console log the "E3DC_SOC_Disp.mean" is still named `name: Value`.
As it seems, the waves for the Liquid fill seem to show the right "height" for the actual value, but the percentage value stays at 0% which seems a little odd..

**Comment by vitPinchuk** [comment]
@MrIngenieur 

The amplitude of waves set up through the `amplitude` property for series.  
To change colors please use `color` property `color: ['red', '#0f0', 'rgb(0, 0, 255)'],` for series.

Label with `0%` text takes by default from the first value of values. Label can be changed via `label` option for series.
Text, position etc. can be changed through `label option` 


```js
return {
  series: [{
    type: 'liquidFill',
    radius: '90%',
    data: [...transformWaves],
    /**
     * Amplitude
     */
    amplitude: 0,
    /**
     * Colors for waves
     */
    color: ['red', '#0f0', 'rgb(0, 0, 255)'],
    /**
     * Label
     */
    label: {
      position: ['68%', '30%'],
      formatter: function () {
        return 'Put your text here';
      },
      fontSize: 16,
      color: '#D94854'
    },
  }]
};
``` 

To find all properties, please refer to  [Echart documentation](https://echarts.apache.org/en/option.html)

Thank you
