### ISSUE TITLE
svg file reference

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#36]
1st of all amazing plugin!!! 

In the u2b tutorial I saw that in order to use custom svg, you have to open the content manually copy and paste svg related details. This seems a bit antiquated and tedious.

Is there a way to reference an actual file located on disk?

Thanks!

**Comment by mikhail-vl** [comment]
Hello @yosiasz,

  You can use URL as explained in the video: https://www.youtube.com/watch?v=ygFDhmbPU-Y
  Let me know if it helps.
