### ISSUE TITLE
Access to dashboard variables

### ISSUE THREAD

**Issue by evertoncolling** [VolkovLabs/volkovlabs-echarts-panel#39]
Is it possible to get access to the [Grafana variables](https://grafana.com/docs/grafana/latest/variables/) available for the current dashboard in the script editor? 

I am porting some plots that I developed using the [ae3e-plotly-panel (v0.5.0)](https://github.com/ae3e/ae3e-plotly-panel) where I was able to access them through a `variables` object, but I haven't been able to access them in the echarts editor.

**Comment by mikhail-vl** [comment]
@evertoncolling Yes, it's possible, it should be done using `replaceVariables` function.

```
replaceVariables - the replaceVariables() function to interpolate variables.
```

Let me know if it works for you. I will update the README to make it clear.

**Comment by evertoncolling** [comment]
Thanks for the quick answer! I just tested and the `replaceVariables` function works like a charm!

**Comment by mikhail-vl** [comment]
@evertoncolling Thank you for confirming. README updated as well.

  If you have some interesting charts, please share. We would love to see them!
