### ISSUE TITLE
sample from echarts not working

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#42]
Greetings,

Copied data from https://echarts.apache.org/examples/en/editor.html?c=custom-gauge
and pasted it into a grafana dashboard.

I cant seem to stop this from being displayed in my console until I unsintall this echart plugin, worrisome.

![image](https://user-images.githubusercontent.com/900951/187729524-0772e627-6d48-4de7-a882-c8c5e0071007.png)

**Comment by mikhail-vl** [comment]
@yosiasz That's expected behavior. Apache ECharts examples should be slightly modified to work with the ECharts panel as described in the README and our YouTube videos: https://www.youtube.com/playlist?list=PLPow72ygztmQHGWFqksEf3LebUfhqBfFu

Please let us know if there is anything else.

**Comment by yosiasz** [comment]
helps if I read the documentation!!! 😆

**Comment by mikhail-vl** [comment]
@yosiasz Documentation always helps.

  Let us know if there is anything else.
