### ISSUE TITLE
[Help] bar3D chart not rendering on Grafana

### ISSUE THREAD

**Issue by Sarunas-Girdenas** [VolkovLabs/volkovlabs-echarts-panel#48]
Hello,

Really like your plugin for Grafana, but have problems rendering `bar3D` chart. The chart I am after is [categorical chart](https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1) over time. That is, I have time series for multiple sensor readings, something like this:
| time1 | sensor1 | value1 |
| time1 | sensor2 | value2 |
| time2 | sensor1 | value3 |

I would like to get the 3D bar chart with X axis being time, Y axis being sensor and Z axis the sensor reading value. However, I am not table to get it rendered on Grafana using your Echarts plugin.

Things I've tried:
1. Copy the code from [Echarts](https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1) example and update the code as in your Youtube videos. This resulted in the blue-ish screen on Grafana with no data visible.
2. I've removed `data` object and instead used the code to extract data into arrays (as in your previous example), but that gave me the same result.
3. Converting `time` column to text as a categorical value for X axis, but that got me the same result as before

Other chart type (using Echarts) works as expected, for instance I can get time series plot on the same data.

I've attached the screenshot and the code:

```
const series = data.series.map((s) => {
  const y_axis_value = s.fields.find((f) => f.name === 'y_axis_value').values.buffer;
  const z_axis_value = s.fields.find((f) => f.name === 'z_axis_value').values.buffer;
  const date_values = s.fields.find((f) => f.name === 'time').values.buffer;
  return [date_values, y_axis_value, z_axis_value];
});
return {
  grid3D: {},
  tooltip: {},
  xAxis3D: {
    type: 'category',
    data: series[0]
  },
  yAxis3D: {
    type: 'category',
    data: series[1]
  },
  zAxis3D: {
    data: series[2]
  },
  visualMap: {
    max: 1000,
    dimension: series[2]
  },
  series: [
    {
      type: 'bar3D',
      shading: 'lambert',
      encode: {
        x: series[0],
        y: series[1],
        z: series[2]
      }
    }
  ]
};
```
![question](https://user-images.githubusercontent.com/6362380/191001747-e5b10cef-944c-419d-b50e-9ec81c0d9cd6.png)

Any hints and help would be highly appreciated :)

**Comment by mikhail-vl** [comment]
@Sarunas-Girdenas, I have not had a chance to use the `bar3D` visualization yet.

  I will take a look and get back to you.

**Comment by mikhail-vl** [comment]
@Sarunas-Girdenas Thank you for opening the issue. To support 3D GL charts, we will need to add an ECharts Extension: https://github.com/ecomfe/echarts-gl

  We will plan and look into it later this week.

**Comment by Sarunas-Girdenas** [comment]
@mikhail-vl - thank you very much for the reply. I've tried adding `echarts-gl` in the chart code on Grafana, but it did not work (I guess I was not expecting it to work, but still tried :) )

Thanks, looking forward to using it once the extension is added.

**Comment by mikhail-vl** [comment]
@Sarunas-Girdenas Correct, it should be done inside the plugin.

  I will have time to check later today or tomorrow.

**Comment by mikhail-vl** [comment]
@Sarunas-Girdenas We released a new version of Apache ECharts panel 3.4.0, which includes the ECharts-GL extension: https://github.com/VolkovLabs/volkovlabs-echarts-panel/releases/tag/v3.4.0

  We will submit it to Grafana shortly. Meanwhile, you can download it from the GitHub repository.
  Please try and let us know if it works for you.

**Comment by Sarunas-Girdenas** [comment]
@mikhail-vl  - thank you very much for your help. I've installed the new version from GitHub repo (Apache ECharts panel 3.4.0), it does work (it renders the 3D chart), but I am unable to get the example working. If I use the same code as before (from the first post), I get this (changed the theme to _light_ so its easier to the 3D chart)
![question_3D_grafana](https://user-images.githubusercontent.com/6362380/191611489-ca0e4811-b54c-4add-b8c4-78fd91ca22ea.png)

On the `X` axis it converts `datetime` to epoch time (I can get this to display human-readable date if I convert column to text from date in the query), then on `Y` it has sensor ID and on `Z` axis we have a reading value. All the numbers on each axis is correct, but it does not render the actual bars. I am sure there is something missing, but I am not sure what. I've tried following the example from [Echarts website ](https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1) but it did not work either (was not even able to  get correct data on the axis displayed).

Would you be able to help once again with getting those bars appear on the chart? :)

**Comment by mikhail-vl** [comment]
@Sarunas-Girdenas This is what works for me, you can fine-tune based on your requirements.

```
const series = data.series.map((s) => {
  const y_axis_value = s.fields.find((f) => f.name === 'y_axis_value').values.buffer;
  const z_axis_value = s.fields.find((f) => f.name === 'z_axis_value').values.buffer;
  const date_values = s.fields.find((f) => f.name === 'time').values.buffer;
  return [date_values, y_axis_value, z_axis_value];
});

return {
  grid3D: {},
  tooltip: {},
  xAxis3D: {
    type: 'category',
  },
  yAxis3D: {
    type: 'category',
  },
  zAxis3D: {
  },
  visualMap: {
    max: 1000,
  },
  series: [
    {
      type: 'bar3D',
      shading: 'lambert',
      data: series[0],
    }
  ]
};
```

![Screen Shot 2022-09-21 at 18 49 14](https://user-images.githubusercontent.com/47795110/191623836-2b8f6be6-5843-4879-a8de-8fa132781b5a.png)

Let me know if there is anything else.

**Comment by Sarunas-Girdenas** [comment]
hey @mikhail-vl  - thank you very much for this. It does work indeed :) thank you very much for the help!

**Comment by mikhail-vl** [comment]
@Sarunas-Girdenas Thank you for confirming.

  Meanwhile, Apache ECharts was updated in the Grafana repository (https://grafana.com/grafana/plugins/volkovlabs-echarts-panel/). It's the same version you are using.

  Let us know if there is anything else.
