### ISSUE TITLE
Echart gauge plot axis label format

### ISSUE THREAD

**Issue by shashank588** [VolkovLabs/volkovlabs-echarts-panel#53]
Hi @mikhail-vl 

I am trying to create a gauge plot using echarts panel. Please refer to the below link for the graph options which I want.
[https://echarts.apache.org/examples/en/editor.html?c=gauge-grade&lang=js](url)

I am able to plot the required gauge plot except for colour and format options. below is the code used in grafana echart panel and the plot I achieved. can you please help me with how to fix the colour and format option?
![image](https://user-images.githubusercontent.com/70828257/192538456-c8d6d0fd-9417-4657-a58a-45b9094c429c.png)
![image](https://user-images.githubusercontent.com/70828257/192539341-9b03b9bf-f21f-442c-95a9-01f75829eedc.png)
![image](https://user-images.githubusercontent.com/70828257/192539688-83b9b4b4-1493-4f73-bd27-a9c9840e4955.png)

**Comment by mikhail-vl** [comment]
@shashank588 `xisLine` should be `axisLine` as in the example if I understand the issue correctly.

  Could you please fix and let us know.

**Comment by shashank588** [comment]
@mikhail-vl Thanks for responding. By fixing the above issue colours have been updated but the axis labels are not yet fixed. I have tried to move the axis label parameter to axisOption but the orientation is still not tangential.


![image](https://user-images.githubusercontent.com/70828257/192685840-e80be2ec-a403-4865-a8d3-5ea4aa2fabd3.png)

**Comment by shashank588** [comment]
Hi @mikhail-vl 

I guess the orientation feature of axis labels is not available in echart `version 5.3.3` and below versions. It is available in the latest version `(Echart 5.4.0)`. May I know which version of Apache echart is used for this plugin?

If it is the older version, is there any possibility to update the Echart version to the latest version for this panel at this moment?

Thank you.

**Comment by mikhail-vl** [comment]
@shashank588 Looks like it's a feature introduced in 5.4.0 which was released less than a week ago.
  
  Plugin is using 5.3.3 and I was planning to upgrade later this week as soon as our power will be restored after Hurricane :)

**Comment by shashank588** [comment]
Thanks, @mikhail-vl for the update. Really appreciate your support to the community during this critical situation.

**Comment by mikhail-vl** [comment]
@shashank588 PR merged. I plan to improve Code Editor and release a new version over the weekend.

  Please let me know if there is anything else.

**Comment by mikhail-vl** [comment]
@shashank588 Version 3.5.0 released: https://github.com/VolkovLabs/volkovlabs-echarts-panel/releases/tag/v3.5.0

  I will submit it to the Grafana team for review. Meanwhile, you can download it from the GitHub repository.
