### ISSUE TITLE
clearInterval doesn't work in echarts

### ISSUE THREAD

**Issue by ZDgtc** [VolkovLabs/volkovlabs-echarts-panel#60]
Hi, 
Thank you for providing such a great plugin for grafana that helps me a lot : )
I used setInterval() in the echarts function to implement highlight different parts of the map automatically, but when I called clearInterval() to stop the timer, it didn't work. 
Could you tell me how to get this working?
Thanks for you help.

```
var mapData = series[0].data                 // [{name: "beijing", "value":  123456}, ......]
var dataLength = mapData.length;
var timer = "";
var index = -1

function mapActive() { 
  clearInterval(timer);
  timer = setInterval(() => {
    console.log(index)
    echartsInstance.dispatchAction({
      type: "downplay",
      seriesIndex: 0,
      dataIndex: index
    });
    index = index >= dataLength - 1 ? 0 : index + 1;
    echartsInstance.dispatchAction({
      type: "highlight",
      seriesIndex: 0,
      dataIndex: index,
    });
    echartsInstance.dispatchAction({
      type: "showTip",
      seriesIndex: 0,
      dataIndex: index,
    });
    if (index >= dataLength) {
      index = 0;
    }
  }, 5000);
}

echartsInstance.on("mouseover", function (params) {
  clearInterval(timer);
  timer = "";
  echartsInstance.dispatchAction({
    type: "downplay",
    seriesIndex: 0,
    dataIndex: index
  });
  echartsInstance.dispatchAction({
    type: "highlight",
    seriesIndex: 0,
    dataIndex: params.dataIndex,
  });
  echartsInstance.dispatchAction({
    type: "showTip",
    seriesIndex: 0,
    dataIndex: params.dataIndex,
  });
  
  if (isNaN(params.value)) {
    echartsInstance.dispatchAction({
      type: "downplay",
      seriesIndex: 0,
    });
    return;
  }
});

echartsInstance.on("mouseout", () => {
  mapActive();
});

mapActive();

return {
    (echarts option)
}
```

**Comment by mikhail-vl** [comment]
@ZDgtc Thank you for the feedback and we glad you enjoy the plugin.

  You call `clearInterval` multiple times based on `mouseover` and `mouseOut` movements. Which one does not work?
  In the `mouseover` event you may lose the Id when doing `timer = "";`.
  
  Take a look at similar issue where we successfully implemented clicks and timeouts: https://github.com/VolkovLabs/volkovlabs-echarts-panel/issues/30#issuecomment-1193035829
  
  Let me know If it helps.

**Comment by ZDgtc** [comment]
你好！我已收到你的邮件，将在查看后回复。

**Comment by ZDgtc** [comment]
@mikhail-vl Thank you for your reply and it helps ：）
It seems that every time when I refresh the panel(or refreshed by grafana automatically), the function can't get the timer value before. So the timer can't be cleared and will continue runing.
I remove the ` var timer = "";timer = "";` expression and use `window.timer` instead and it works ：）

**Comment by mikhail-vl** [comment]
@ZDgtc, I am glad it worked!

  Please let us know if you need anything else.
