### ISSUE TITLE
Add ecStat

### ISSUE THREAD

**Issue by amarant** [VolkovLabs/volkovlabs-echarts-panel#62]
Hi,

I want to be able to do regression on scatter graph, so I need access to the echarts-stat module using
`echarts.registerTransform(ecStat.transform.regression);
`
[like this example](https://echarts.apache.org/examples/en/editor.html?c=scatter-linear-regression).

Currently a ecStat like variable doesn't seems accessible.

Thanks.

**Comment by mikhail-vl** [comment]
@amarant Thank you for opening the issue. It's a really nice feature.

   I will look into including this library in the upcoming version.

**Comment by mikhail-vl** [comment]
@amarant `ecStat` added and will be available in the upcoming release later this week.

  Please let us know if there is anything else.

**Comment by mikhail-vl** [comment]
@amarant Have you had a chance to try the ecStat?
  
  We released a new video tutorial how to work with Histrograms, Clustering and Regression: https://youtu.be/qfDrAW8-Mh8

**Comment by amarant** [comment]
Yes, it works, thanks.
