### ISSUE TITLE
Button with click event?

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#63]
Hi

Does this plugin allow creation of buttons that change value of variables?

Thanks!

**Comment by mikhail-vl** [comment]
@yosiasz You can define the `onClick` event and use `replaceVariables` function to interpolate variables.

  Let me know if it works or not working for you.

**Comment by mikhail-vl** [comment]
@yosiasz Please let us know if it worked or need anything else.
