### ISSUE TITLE
use echartsInstance ERROR

### ISSUE THREAD

**Issue by XiaoChouYou** [VolkovLabs/volkovlabs-echarts-panel#67]
console.log(echartsInstance);

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.o (<anonymous>:1:83)

**Comment by mikhail-vl** [comment]
@XiaoChouYou What version of Grafana and Apache ECharts plugin do you use?

**Comment by mikhail-vl** [comment]
@XiaoChouYou I just tried it. Everything is working as expected using Grafana 9.2.2

![Screen Shot 2022-11-05 at 22 15 50](https://user-images.githubusercontent.com/47795110/200150881-675ae8f9-fe66-40aa-a59f-824c0b17964a.png)

**Comment by mikhail-vl** [comment]
@XiaoChouYou Please let us know if you are still experiencing the issue. Closing until then.
