### ISSUE TITLE
Can't use "document.getElementById('main')" for echarts.init in Grafana (v9.1.8)

### ISSUE THREAD

**Issue by naqibRDMA** [VolkovLabs/volkovlabs-echarts-panel#70]
**Steps to Reproduce**
Creating the chart itself is not a problem. I've managed to use their bar charts and line graphs with ease and no issue.
The problem comes in when I wanted to add a click event for a drill down activity. In Grafana, I need to add the chart's DOM to echarts.init. Below are the code that I've taken from the website's official documentation:

var chartDom = document.getElementById('main');
var myChart = echarts.init(chartDom);
myChart.on('click', function (event) { . . . }

**Current Behavior**
chartDom will always return NULL as there is no div tags with the id 'main' in Grafana. Grafana will render the echart into a panel and I don't know which of it's id to initialize the echart.

**Comment by mikhail-vl** [comment]
@naqibRDMA ECharts already initialized, and it's not required.

  Here is how you react to events.

/**
 * On Mouse Click
 */
echartsInstance.on('click', (params) => {
  ...
  echartsInstance.resize(); // to redraw visualization
});

/**
 * On Double Click
 */
echartsInstance.on('dblclick', (params) => {
  ...
  echartsInstance.resize();
});
```

  Let me know if It works for you. I will update documentation.

**Comment by mikhail-vl** [comment]
@naqibRDMA README updated.

  Please let us know if it works for you or there is anything else.

**Comment by naqibRDMA** [comment]
Thank you for the quick reply. It is working now. Appreciate the clarification!

**Comment by mikhail-vl** [comment]
@naqibRDMA Thank you for confirming.

  Let us know if there is anything else.
