### ISSUE TITLE
Save as Image Feature

### ISSUE THREAD

**Issue by shashank588** [VolkovLabs/volkovlabs-echarts-panel#72]
Hi @mikhail-vl,

On exploring the Volkov labs live server I came across the 'save as image' feature. I really like this feature so Is it possible to add this feature to other panels as well? if yes can you please let me know the process? Thank you.

![image](https://user-images.githubusercontent.com/70828257/201308494-107ba2b9-2bef-448e-83b1-4d2c42a7fb84.png)

**Comment by mikhail-vl** [comment]
@shashank588 It's a great question. Save as Image is a native Apache ECharts feature.

  For all other Grafana panels, take a look at https://grafana.com/grafana/plugins/grafana-image-renderer/.
  Please let us know if there is anything else.
