### ISSUE TITLE
Getting strange behaviour building my first panel 

### ISSUE THREAD

**Issue by AceSeanGG** [VolkovLabs/volkovlabs-echarts-panel#81]
<img width="1910" alt="query" src="https://user-images.githubusercontent.com/118804661/203272264-5b70452a-ec98-48e4-800e-3d801c62de5a.png">
<img width="1914" alt="query2" src="https://user-images.githubusercontent.com/118804661/203272269-6658d063-8e8f-41a8-a389-a54b933996c3.png">

this query return 3 values about cpu usage but nothing work about the y axis, there is a way to work with multiple _value at the same time?

i attach the Echart code for a better visualization 

`let Interrupt = [];
let User = [];
let DCP = [];
data.series.map((s) => {
  Interrupt = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
  DCP = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
  User = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
});

  const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;

  return {
    name: s.name,
    type: 'line',
    showSymbol: false,
    areaStyle: {
      opacity: 0.1,
    },
    lineStyle: {
      width: 1,
    },
    data: sData.map((d, i) => [sTime[i], d.toFixed(2)]),
  };
});

const axisOption = {
  axisTick: {
    show: false,
  },
  axisLine: {
    show: false,
  },
  axisLabel: {
    color: 'rgba(128, 128, 128, .9)',
  },
  splitLine: {
    lineStyle: {
      color: 'rgba(128, 128, 128, .2)',
    },
  },
};

return {
  backgroundColor: 'transparent',
  tooltip: {
    trigger: 'axis',
  },
  legend: {
    left: '0',
    bottom: '0',
    data: data.series.map((s) => s.name),
    textStyle: {
      color: 'rgba(128, 128, 128, .9)',
    },
  },
  xAxis: Object.assign(
    {
      type: 'time',
    },
    axisOption
  ),
  yAxis: Object.assign(
    {
      data: Interrupt,DCP,User,
      type: 'value',
    },
    axisOption
  ),
  grid: {
    left: 0,
    right: 16,
    top: 6,
    bottom: 24,
    containLabel: true,
  },
  series,
};`

**Comment by mikhail-vl** [comment]
@AceSeanGG Thank you for trying the Apache ECharts Panel.

  This is the very simple code to display 3 lines with emulated test values using Static Data Source:  

```
let Interrupt = [];
let User = [];
let DCP = [];
let Time = [];

const series = data.series.map((s) => {
  Time = s.fields.find((f) => f.name === '_time').values.buffer;
  Interrupt = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
  DCP = s.fields.find((f) => f.name === 'Percent_DCP_Time').values.buffer;
  User = s.fields.find((f) => f.name === 'Percent_User_Time').values.buffer;

  return [
    { data: Time.map((t, i) => [t, Interrupt[i]]), type: 'line', smooth: true },
    { data: Time.map((t, i) => [t, DCP[i]]), type: 'line', smooth: true  },
    { data: Time.map((t, i) => [t, User[i]]), type: 'line', smooth: true  }]
});

return option = {
  xAxis: {
    type: 'time',
    data: Time
  },
  yAxis: {
    type: 'value'
  },
  series: series[0]
};
```

![Screen Shot 2022-11-22 at 15 04 10](https://user-images.githubusercontent.com/47795110/203410491-75ec560c-795c-4356-8dac-de2ef6bc1de2.png)

  See if it works for you and then you can modify using additional options.

**Comment by AceSeanGG** [comment]
it works like a charm, i only change some query parameters
the last thing i want to do is add the field name in the legend (right now is showing just the value but the name is blank)
any idea?

**Comment by mikhail-vl** [comment]
@AceSeanGG I would recommend to look at the Examples: https://echarts.apache.org/examples/en/index.html. Find the best one which suits your needs and modify according to the requirements.

  Here is the updated code to display legend and tooltip.

```
let Interrupt = [];
let User = [];
let DCP = [];
let Time = [];

const series = data.series.map((s) => {
  Time = s.fields.find((f) => f.name === '_time').values.buffer;
  Interrupt = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
  DCP = s.fields.find((f) => f.name === 'Percent_DCP_Time').values.buffer;
  User = s.fields.find((f) => f.name === 'Percent_User_Time').values.buffer;

  return [
    { data: Time.map((t, i) => [t, Interrupt[i]]), type: 'line', smooth: true, name: 'Interrupt' },
    { data: Time.map((t, i) => [t, DCP[i]]), type: 'line', smooth: true, name: 'DCP' },
    { data: Time.map((t, i) => [t, User[i]]), type: 'line', smooth: true, name: 'User' }]
});

return option = {
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['Interrupt', 'DCP', 'User'],
  },
  xAxis: {
    type: 'time',
    data: Time
  },
  yAxis: {
    type: 'value'
  },
  series: series[0]
};
```

  Let us know if there is anything else and check out our YouTube tutorials which covers this and other topics: https://www.youtube.com/playlist?list=PLPow72ygztmQHGWFqksEf3LebUfhqBfFu

**Comment by AceSeanGG** [comment]
<img width="1914" alt="progress" src="https://user-images.githubusercontent.com/118804661/203750367-34c00156-0a5a-45d3-96cc-87f2cce646c9.PNG">

After some time i was able to build this panel, and for me it's looking pretty good
all thanks to your help and the playlist of video that you share to me!

here is the updated code:

let Interrupt = [];
let User = [];
let Time = [];
let Privileged = [];

const series = data.series.map((s) => {
  Time = s.fields.find((f) => f.name === '_time').values.buffer;
  Interrupt = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
  User = s.fields.find((f) => f.name === 'Percent_User_Time').values.buffer;
  Privileged = s.fields.find((f) => f.name === 'Percent_Privileged_Time').values.buffer;

  return [
    { data: Time.map((t, i) => [t, Interrupt[i]]), type: 'line', smooth: true, showSymbol: false, areaStyle: { opacity: 0.4 }, stack: 'Total', name: 'Interrupt' },
    { data: Time.map((t, i) => [t, User[i]]), type: 'line', smooth: true, showSymbol: false, areaStyle: { opacity: 0.4 }, stack: 'Total', name: 'User' },
    { data: Time.map((t, i) => [t, Privileged[i]]), type: 'line', smooth: true, showSymbol: false, areaStyle: { opacity: 0.4 }, stack: 'Total', name: 'Privileged' }]
});
return {
  color: ['#eb4034', '#3aeb34', '#37A2FF'],
  backgroundColor: 'transparent',
  title: {
    text: 'CPU Usage',
    left: 'center'
  },

  dataZoom: [
    {
      type: 'inside',
      start: 0,
      end: 100
    },
    {
      show: true,
      type: 'slider',
      top: '90%',
      start: 0,
      end: 100
    }
  ],

  tooltip: {
    trigger: 'axis',
    /*    formatter([{ value: Interrupt }, { value: User }, { value: Privileged}]) => `${Interrupt.toFixed(2)}<br/>${User.toFixed(2)}<br/>${Privileged.toFixed(2)}`,*/
  },

  legend: {
    left: '120',
    top: '35',
    data: ['Interrupt', 'User', 'Privileged'],
    textStyle: {
      color: 'rgba(255, 255, 255, 1)',
    },
  },

  toolbox: {
    right: '45',
    top: '30',
    feature: {
      magicType: {
        type: ["line", "bar"]
      },
      restore: {},
      saveAsImage: {}
    },
  },

  aria: {
    enabled: true,
    decal: {
      show: true
    }
  },

  xAxis: {
    type: 'time',
    data: Time
  },
  yAxis: {
    type: 'value',
    max: 100,
    axisLabel: {
      formatter: '{value} %'
    },
  },


  grid: [
    {
      left: 60,
      right: 50,
      height: '70%'
    },
  ],

  axisTick: {
    show: true,
  },
  axisLine: {
    show: true,
  },
  axisLabel: {
    color: 'rgba(255, 255, 255, .9)',
  },
  splitLine: {
    lineStyle: {
      color: 'rgba(255, 255, 255, 0.1)',
    },
  },

  series: series[0]

};

it's in some how possibile to format the output to show only the last two digit in the legend?
and maybe add the '%' symble at the end, something like this (Interrupt: 18,48%).

and of course thank you again for everything, without you I was never going to be able to create this panel!

**Comment by mikhail-vl** [comment]
@AceSeanGG Great to see the progress. From Zero to Hero!

  There is a formatted for the legend: https://echarts.apache.org/v4/en/option.html#legend.formatter

```
// using string template, the template variable is legend name {name}
formatter: 'Legend {name}'
// using callback function
formatter: function (name) {
    return 'Legend ' + name;
}
```

  Try it out. We also explained how to use it in one of the videos as I remember.

**Comment by AceSeanGG** [comment]
Thanks @mikhail-vl i really love this panel!!

After some try this code work perfect!

  tooltip: {
    show: true,
    trigger: 'axis',
    valueFormatter: (value) => value.toFixed(2) + '%',
  },

if you have any advice for a better visualization im glad to hear you out!

**Comment by mikhail-vl** [comment]
@AceSeanGG Looks great!

  Do you mind to do one more screenshot with updated tooltip and closed `Panel options` to show ECharts' Options and Code Editor on the left. I would love to showcase for the community as a great example for CPU Usage.

  Thank you and let us know if there is anything else.

**Comment by AceSeanGG** [comment]
<img width="1832" alt="cpuusage" src="https://user-images.githubusercontent.com/118804661/203832334-8ae69f8e-0ecf-4102-8fcc-52331bdf894e.png">

i attach the query and the echart function because i'm not able to display all of it in a single screenshot.
 
the last think a want to ask you is how to change the panel from light to dark mode, i mean if i use backgroundColor: 'transparent' and in the grafana interface i switch to light mode everything become white and unreadable.
there are any workarround? maybe a toggle to switch from light to dark as i can see in some echart example

thank you in advice for everything!


**Query**

import "influxdata/influxdb/schema"

from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "win_cpu" and r.host =~ /^${hostname:regex}$/ and r.instance == "_Total")
  |> filter(fn: (r) => r._field == "Percent_User_Time" or r["_field"] == "Percent_Interrupt_Time" or r["_field"] == "Percent_Privileged_Time")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> schema.fieldsAsCols()  
  |> yield(name: "mean")
  
**EChart Function**

let Interrupt = [];
let User = [];
let Time = [];
let Privileged = [];

const series = data.series.map((s) => {
  Time = s.fields.find((f) => f.name === '_time').values.buffer;
  Interrupt = s.fields.find((f) => f.name === 'Percent_Interrupt_Time').values.buffer;
  User = s.fields.find((f) => f.name === 'Percent_User_Time').values.buffer;
  Privileged = s.fields.find((f) => f.name === 'Percent_Privileged_Time').values.buffer;

  return [
    { data: Time.map((t, i) => [t, Interrupt[i]]), type: 'line', smooth: true, showSymbol: false, areaStyle: { opacity: 0.4 }, stack: 'Total', name: 'Interrupt', emphasis: { focus: 'series' }},
    { data: Time.map((t, i) => [t, User[i]]), type: 'line', smooth: true, showSymbol: false, areaStyle: { opacity: 0.4 }, stack: 'Total', name: 'User', emphasis: { focus: 'series' } },
    { data: Time.map((t, i) => [t, Privileged[i]]), type: 'line', smooth: true, showSymbol: false, areaStyle: { opacity: 0.4 }, stack: 'Total', name: 'Privileged', emphasis: { focus: 'series' }  }]
});
return {
  color: ['#22a345', '#d6b318', '#eb4034'],
  backgroundColor: '#181b1f',
  title: {
    left: "center",
    text: "CPU USAGE",
  },

  dataZoom: [
    {
      type: 'inside',
      start: 0,
      end: 100
    },
    {
      show: true,
      type: 'slider',
      bottom: '1%',
      start: 0,
      end: 100
    }
  ],

  tooltip: {
    show: true,
    trigger: 'axis',
    backgroundColor: 'implements',
    valueFormatter: (value) => value.toFixed(2) + '%',
    textStyle: {
      color: 'white',
    }
  },


  legend: {
    left: '0',
    data: ['Interrupt', 'User', "Privileged"],
    textStyle: {
      color: 'rgba(255, 255, 255, 1)',
    },
  },

  toolbox: {
    right: '45',
    feature: {
      magicType: {
        type: ["line", "bar"]
      },
      restore: {},
      saveAsImage: {}
    },
  },

  aria: {
    enabled: true,
    decal: {
      show: true
    }
  },

  xAxis: {
    type: 'time',
    data: Time
  },
  yAxis: [
    {
      type: 'value',
      nameTextStyle: {
        color: '#fff'
      },
      splitLine: {
        show: true,
      },
      axisLabel: {
        formatter: '{value} %',
        textStyle: {
          color: '#fff',
        }
      },
      min: 0,
      max: 100,
    },
  ],

  grid: [
    {
      left: 60,
      right: 50,
      height: '70%'
    },
  ],

  axisTick: {
    show: true,
  },
  axisLine: {
    show: true,
  },


  series: series[0]

};

**Comment by mikhail-vl** [comment]
@AceSeanGG Thank you! This is exactly what I was looking for.

  Regarding theme we initialize ECharts with Dark theme if Grafana's theme set to Dark like an `Auto` mode.

```
    setChart(echarts.init(echartRef.current, theme.isDark ? 'dark' : undefined, { renderer: options.renderer }));
```

  Do you want to keep dark theme always and don't depend on the Grafana theme?
  I am thinking to add a Panel Option for Theme: 'Auto', 'Dark', 'Light', 'Custom'. With a 'Custom' Theme you can specify your own theme for all components.

  Let me know if it will for you.

**Comment by AceSeanGG** [comment]
**I am thinking to add a Panel Option for Theme: 'Auto', 'Dark', 'Light', 'Custom'. With a 'Custom' Theme you can specify your own theme for all components.**

that would be awesome! i have changed the code a little bit and removed all the part with the tag "color" so now if i switch from light mode to dark mode the panel change consequentially
but the panel option for set up a custom theme is an awesome idea!

my first tought it's to set up "backgroundColor: '#181b1f'" in dark mode so the panel background have the same color of the classic grafana interface in dark mode.

<img width="1868" alt="background" src="https://user-images.githubusercontent.com/118804661/203938012-29dbd26a-11a8-4abe-8fec-8ecdb0b55cdf.PNG">

on the left is the pannel having the option "backgroundColor: '#181b1f'" on the right is the default one 

what you think about it?

**Comment by AceSeanGG** [comment]
other than that i have an interesting idea!
i'm thinking to build a panel based from this example: https://echarts.apache.org/examples/en/editor.html?c=line-race

the query is pretty easy it return the cardinality of all my buckets
**query**

import "influxdata/influxdb/schema"

from(bucket: "local_Cardinality")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "buckets")
  |> filter(fn: (r) => r["_field"] == "cardinality")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> group(columns: ["bucket"])
  |> schema.fieldsAsCols()
  
and the returned data are that: (i have censured the bucket name just for privacy)
<img width="478" alt="cardinalitybucket" src="https://user-images.githubusercontent.com/118804661/204030108-64299deb-2aea-4cce-a4d5-0607f8c656c7.PNG">

do you think is possible to do what i have in mind?

of course i will try it out on monday ^^, and thank for all of your help!

**Comment by mikhail-vl** [comment]
@AceSeanGG It should be easy to do. I love this Race visualization, but have not had a chance to try it ourself.

  Send me screenshot to share when done and please open a new issues for any questions.
  I am closing this one as resolved.
