### ISSUE TITLE
Trying to find the svg sample echart

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-echarts-panel#82]
Greetings

Trying to find the following viz (found in your videos) on https://echarts.apache.org/examples

![image](https://user-images.githubusercontent.com/900951/203396151-b17c535c-fb34-415c-9d6f-bd28a80c0eee.png)

Thanks much

**Comment by mikhail-vl** [comment]
@yosiasz, We (Daria) did a lot of custom Apache ECharts visualizations in the videos, some of them you can't find in the examples.

  `Path` is just a path from very simple SVG.

  Is there anything in particular you are interested in?

**Comment by mikhail-vl** [comment]
@yosiasz This is the great example how to work with SVG images in Apache ECharts using Static Data Source:

![image](https://user-images.githubusercontent.com/47795110/203397498-316e91b9-880e-418d-94c3-cf00b6f43df5.png)

**Comment by yosiasz** [comment]
> @yosiasz, We (Daria) did a lot of custom Apache ECharts visualizations in the videos, some of them you can't find in the examples.
> 
> `Path` is just a path from very simple SVG.
> 
> Is there anything in particular you are interested in?
Gotcha,

Great examples on that site for sure! I just wanted to see how one can display svg images on a clean canvas with no underlying svg file

Thanks!

**Comment by mikhail-vl** [comment]
This is how we did it for `https://live.volkovlabs.io` as a background
```
return {
  graphic: {
    type: "image",
    style: {
      image: `data:image/svg+xml;utf8,${images[0]}`,
      width: echartsInstance.getWidth(),
      height: echartsInstance.getHeight(),
    },
  },
};
```

where images was taken from the Static Data Source or can be an `<svg ...></svg>` code

```
data.series.map((s) => {
  if (s.refId === "company_logo") {
    images = s.fields.find((f) => f.name === "body").values.buffer;
  }
});
```

Let me know if it's what you are looking for.

**Comment by yosiasz** [comment]
ah beautiful!! And how about svg 
```
path://
```

**Comment by yosiasz** [comment]
never mind I got it !

```
image: `https://echarts.apache.org/examples/data/asset/geo/Veins_Medical_Diagram_clip_art.svg`,
```
