### ISSUE TITLE
Proportional text doubt

### ISSUE THREAD

**Issue by otger** [VolkovLabs/volkovlabs-echarts-panel#84]
I am using a gauge chart and I see how to set the text size on the detail:
```
    detail: {
      valueAnimation: true,
      width: '90%',
      lineHeight: 30,
      borderRadius: 8,
      offsetCenter: [0, '-15%'],
      fontSize: 50,
      fontWeight: 'bolder',
      formatter: '{value}',
      color: 'auto'
    },
```
The problem with that, is that if the final user resizes the widget, the text do not scale with the content, and it can scramble everything. Is there a way to know the size of the widget, so fontSize can be calculated?

**Comment by mikhail-vl** [comment]
@otger That's a great question. You can get them from the `echartsInstance`. I will update documentation.

```
      width: echartsInstance.getWidth(),
      height: echartsInstance.getHeight(),
```

  Let me know if it helps.

**Comment by otger** [comment]
Thank you very much!

**Comment by mikhail-vl** [comment]
@otger Thank you for confirming. README is updated in #85.

  Let us know if there is anything else and check out our YouTube tutorials: https://www.youtube.com/playlist?list=PLPow72ygztmQHGWFqksEf3LebUfhqBfFu
