### ISSUE TITLE
Add Theming Options to allow Custom Themes

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-echarts-panel#86]
I am thinking to add a Panel Option for Themes: 'Auto', 'Dark', 'Light', 'Custom'.

  With a 'Custom' Theme you can specify your own theme for all components.
  It will be a great feature!

**Comment by AceSeanGG** [comment]
my first tought it's to set up "backgroundColor: '#181b1f'" in dark mode so the panel background have the same color of the classic grafana interface in dark mode.

<img width="1868" alt="background" src="https://user-images.githubusercontent.com/118804661/203938012-29dbd26a-11a8-4abe-8fec-8ecdb0b55cdf.PNG">

on the left is the pannel having the option "backgroundColor: '#181b1f'" on the right is the default one 

what you think about it?

**Comment by mikhail-vl** [comment]
@AceSeanGG Thank you for suggestion. I was thinking to update the Dark mode to make default background color configurable. I can use the Grafana's native color for the default color panel.

  We discussed the idea internally and agreed to implement custom themes in the upcoming version along a new YouTube tutorials how to create a custom theme and use it in the panel.

  Stay tuned.

**Comment by BlueskyFR** [comment]
Hi! I see that the feature was postponed a few times: is it still planed?
Thank you for your job!

**Comment by mikhail-vl** [comment]
@BlueskyFR Is it something you are interested in? We don't see enough interest for this feature so far and postponed prioritizing other issues and plugins.

  I was considering implementing it in the upcoming release.

**Comment by BlueskyFR** [comment]
> @BlueskyFR Is it something you are interested in? We don't see enough interest for this feature so far and postponed prioritizing other issues and plugins.
> 
>   I was considering implementing it in the upcoming release.

Thanks for your quick reply!
Yes I am totally interested!
I was trying to add a custom theme this afternoon so in the mean time I hardcoded the color values in my plot but it would be nice to be able to provide one somewhere.

But I agree that it is not the most useful feature as specifying colors on a per-plot basis is not that annoying after all 😊

**Comment by mikhail-vl** [comment]
@BlueskyFR Great, it should be easy to do with another Code Editor in the upcoming version.
