### ISSUE TITLE
Size of maps

### ISSUE THREAD

**Issue by otger** [VolkovLabs/volkovlabs-echarts-panel#87]
I am doing a map where I want to show the status of some gauges.

My problem is that the map does not expand to the whole available space:
![image](https://user-images.githubusercontent.com/535081/204012079-47e2f42c-39ce-4550-b7d7-a4c59e88cbd2.png)

I would like for it to show as big as possible keeping the same aspect ratio of course. Any idea why there are those big margins and how to solve the issue?

My code: 
```
var option;
$.ajax({
  async: false,
  type: 'GET',
  url: 'https://control.ifae.es/scheme_bluefors.svg',
  success: function (svg) {
    console.log(echarts);
    echarts.registerMap('scheme_bluefors', { svg: svg });
    option = {
      tooltip: {},
      visualMap: {
        show: false,
        left: 'center',
        bottom: '10%',
        min: 0,
        max: 1,
        realtime: true,
        calculable: true,
        inRange: {
          color: ['#f33', '#23f']
        }
      },
      series: [
        {
          name: 'Bluefors Scheme',
          type: 'map',
          map: 'scheme_bluefors',
          roam: true,
          emphasis: {
            label: {
              show: false
            }
          },
          selectedMode: false,
          data: [
            { name: 'V21', value: 0 },
            { name: 'V22', value: 1 },
          ]
        }
      ]
    };
  }
});

return option;
```

Here I still have to do the connection with the data from influxdb. 

Thank you very much!

**Comment by mikhail-vl** [comment]
@otger First of all, I would suggest to use Data source to get the SVG. You can use Static Data Source to keep it in the dashboard or use real data source to fetch data before visualizing in the panel.


  Please take a look at examples: https://echarts.apache.org/examples/en/index.html#chart-type-map
  I believe `layoutSize` controls the margin.

```
    geo: {
      map: 'ksia-ext-plan',
      roam: true,
      layoutCenter: ['50%', '50%'],
      layoutSize: '100%'
    },
```

  Let me know if it works for you.

**Comment by mikhail-vl** [comment]
@otger, Please let me know if it works for you.

**Comment by otger** [comment]
Sorry for late reply, 

I've tried it and  it works, but I do not understand why, in order to fill the space available I have to set the layout size to 130%:

```
          layoutCenter: ['50%', '50%'],
          layoutSize: '130%',
```

Thank you very much!

**Comment by mikhail-vl** [comment]
@otger Interesting, probably there are margins somewhere that need to be adjusted to set it correctly.

  I would suggest using a data source instead of making requests from the panel.
  If you are using a specific SVG file, then you can store it inside the dashboard using Static Data Source.

  Please let us know if there is anything else.

**Comment by otger** [comment]
@mikhail-vl I've been checking how I could use a data source for getting a file from a server, and I do not see how to do it. Do I need a plugin?

**Comment by mikhail-vl** [comment]
@otger Yes, you need a specific data source to request SVG from external resources.

  I believe you can use [Infinity Data Source](https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/), which supports XML files.

**Comment by otger** [comment]
I will give it a try! Thank you for your support

**Comment by mikhail-vl** [comment]
@otger Great! You are welcome to share your use case when you got it working for you to showcase to the community.

  Let us know if there is anything else.
