### ISSUE TITLE
Dynamic treemap drill down 

### ISSUE THREAD

**Issue by acappelletti** [VolkovLabs/volkovlabs-echarts-panel#89]
Hi,
I found your amazing plug-in and a started to study and watch many YouTube video on your channel.
I'm very interested to this graph https://echarts.apache.org/examples/en/editor.html?c=treemap-drill-down

I didn't understand how to render dynamic my data source... Is there some video or web page to study?

Naturally on my grafana test page I got... (it's clear to me 'cause into example there is a json file)
ECharts Execution Error
ROOT_PATH is not defined

Thanks ALEN
```
const uploadedDataURL = ROOT_PATH + '/data/asset/data/ec-option-doc-statistics-201604.json';
myChart.showLoading();
$.getJSON(uploadedDataURL, function (rawData) {
  myChart.hideLoading();
  function convert(source, target, basePath) {
    for (let key in source) {
      let path = basePath ? basePath + '.' + key : key;
      if (!key.match(/^\$/)) {
        target.children = target.children || [];
        const child = {
          name: path
        };
        target.children.push(child);
        convert(source[key], child, path);
      }
    }
    if (!target.children) {
      target.value = source.$count || 1;
    } else {
      target.children.push({
        name: basePath,
        value: source.$count
      });
    }
  }
  const data = {
    children: []
  };
  convert(rawData, data, '');
  myChart.setOption(
    (option = {
      title: {
        text: 'ECharts Options',
        subtext: '2016/04',
        left: 'leafDepth'
      },
      tooltip: {},
      series: [
        {
          name: 'option',
          type: 'treemap',
          visibleMin: 300,
          data: data.children,
          leafDepth: 2,
          levels: [
            {
              itemStyle: {
                borderColor: '#555',
                borderWidth: 4,
                gapWidth: 4
              }
            },
            {
              colorSaturation: [0.3, 0.6],
              itemStyle: {
                borderColorSaturation: 0.7,
                gapWidth: 2,
                borderWidth: 2
              }
            },
            {
              colorSaturation: [0.3, 0.5],
              itemStyle: {
                borderColorSaturation: 0.6,
                gapWidth: 1
              }
            },
            {
              colorSaturation: [0.3, 0.5]
            }
          ]
        }
      ]
    })
  );
});
```

**Comment by mikhail-vl** [comment]
@acappelletti Here is the Apache ECharts playlist to get started: https://www.youtube.com/playlist?list=PLPow72ygztmQHGWFqksEf3LebUfhqBfFu

  Especially this one explains how to work with Data Sources: https://www.youtube.com/watch?v=K5YNMSIm9AM&list=PLPow72ygztmQHGWFqksEf3LebUfhqBfFu&index=3

  You can click on the `Full Code` in the Example to see where `ROOT_PATH` is defined. You don't need to request data from external resources. Data sources should be used instead.

  Let me know if it works for you.

**Comment by acappelletti** [comment]
@mikhail-vl Thanks for your answer... 
I've already seen almost all those videos... but maybe I chose a complicated typology to start with... usually the other graphs have the values expressed in the code... in this case the values are external and for my level it's too much.

Tomorrow I will try more... now I'm tired.
I've clicked on "full code" tab... but it doesn't opened my mind : )

My goal is to view a tree map of database datafile directory, something like:
Disk > Database > Filegroup > Table > Index (for tree map structure into table source)

Thanks for your support.
ALEN

**Comment by mikhail-vl** [comment]
@acappelletti Simple Treemap works with no problem, just replace `options = ` to `return`

  ![Screen Shot 2022-11-27 at 19 38 04](https://user-images.githubusercontent.com/47795110/204169005-78bbb5d0-4a7d-44ac-a56a-35086fee963b.png)

**Comment by mikhail-vl** [comment]
@acappelletti Here is another example. When using Grafana, you have to think synchronously because data is already loaded using data sources when the panel is drawing.

  Apache ECharts Examples are asynchronously loading JSON files from external resources and then drawing echarts.

![Screen Shot 2022-11-27 at 19 47 49](https://user-images.githubusercontent.com/47795110/204169710-70f65e01-0365-4ce7-b4e3-bff77258c4d4.png)

  Source code with truncated data structure:

```
const diskData = [
  {
    "value": 40,
    "name": "Accessibility",
    "path": "Accessibility"
  },
  {
    "value": 272,
    "name": "WidgetResources",
    "path": "WidgetResources",
    "children": [
      {
        "value": 16,
        "name": ".parsers",
        "path": "WidgetResources/.parsers"
      },
      {
        "value": 172,
        "name": "AppleClasses",
        "path": "WidgetResources/AppleClasses",
        "children": [
          {
            "value": 156,
            "name": "Images",
            "path": "WidgetResources/AppleClasses/Images"
          }
        ]
      },
      {
        "value": 0,
        "name": "AppleParser",
        "path": "WidgetResources/AppleParser"
      },
      {
        "value": 48,
        "name": "button",
        "path": "WidgetResources/button"
      },
      {
        "value": 32,
        "name": "ibutton",
        "path": "WidgetResources/ibutton"
      }
    ]
  }
]

const formatUtil = echarts.format;
function getLevelOption() {
  return [
    {
      itemStyle: {
        borderWidth: 0,
        gapWidth: 5
      }
    },
    {
      itemStyle: {
        gapWidth: 1
      }
    },
    {
      colorSaturation: [0.35, 0.5],
      itemStyle: {
        gapWidth: 1,
        borderColorSaturation: 0.6
      }
    }
  ];
}

return {
  title: {
    text: 'Disk Usage',
    left: 'center'
  },
  tooltip: {
    formatter: function (info) {
      var value = info.value;
      var treePathInfo = info.treePathInfo;
      var treePath = [];
      for (var i = 1; i < treePathInfo.length; i++) {
        treePath.push(treePathInfo[i].name);
      }
      return [
        '<div class="tooltip-title">' +
        formatUtil.encodeHTML(treePath.join('/')) +
        '</div>',
        'Disk Usage: ' + formatUtil.addCommas(value) + ' KB'
      ].join('');
    }
  },
  series: [
    {
      name: 'Disk Usage',
      type: 'treemap',
      visibleMin: 300,
      label: {
        show: true,
        formatter: '{b}'
      },
      itemStyle: {
        borderColor: '#fff'
      },
      levels: getLevelOption(),
      data: diskData
    }
  ]
};
```

  Let us know if there is anything else.

**Comment by acappelletti** [comment]
Hi...
I played with the tree map with static elements... 
The main difficulty is not creating the query from my database... I think I have guessed the fields... but how to inject int JS (now static). 

If you can make one of your wonderful videos on how to transform (perhaps on a tree map) static data into dynamic ones, could be great. For now I've managed to edit and add new fields and sections.

Another think...
the field 3 in red is mandatory, it's the sum of other nodes? 'cause I removed and it's the same.
![image](https://user-images.githubusercontent.com/43847440/204670224-4c373e63-f97d-4e44-9ef3-e3cfb7f77dec.png)

Thanks ALEN

**Comment by mikhail-vl** [comment]
@acappelletti Great to see your progress!

  We created a new Grafana instance (https://echarts.volkovlabs.io) and migrated 100+ visualizations, including some TreeMap examples for the community to get started. I believe it will be easier to experiment and provide examples using data sources to retrieve data. We will migrate all of them and then start improving using data sources and refactoring legacy code.

  2) We plan to do more tutorials and deep-dive sessions to cover the new Grafana instance to start exploring and experimenting. Stay tuned.

  3) Detailed documentation for any data structure you can check in Cheat Sheet on echarts.apache.org. If it works without, just remove it.

  Please share if you make it work.

**Comment by acappelletti** [comment]
@mikhail-vl AMAZING link! Thanks so much!

I didn't know the site you gave me!
I've browsed other pages on your site but not this one previously. These examples certainly cover 95% (I think) of the users' needs... certainly pairing a static example with a dynamic one (for each graph I think would solve all the problems of understanding dynamic adaptation with a data sources... side by side graph I mean.

In the next days I'll go on to understand if I'll be able to connect to a data source independently... but due to the type of tree map (querable)... it's complicated without a real starting example (from a data source).

Watching one of your videos (but I've seen almost all of them) one described how to introduce data into the graph from a data source... I can't find it anymore...
Do you remember it? If yes, please I ask you to post the link here.

Thank for now.
Alen

**Comment by mikhail-vl** [comment]
@acappelletti Most probably, you are talking about the Tutorial for the Graph we used for https://live.volkovlabs.io: https://www.youtube.com/watch?v=e3VHgpuzEF0 and https://youtu.be/oM7XAVlsOio.

**Comment by mikhail-vl** [comment]
@acappelletti How is your progress so far?

**Comment by acappelletti** [comment]
@mikhail-vl Hi and thanks for your interests.
In the past days I had to review other panels in Grafana and make some fixes, but tomorrow I will have the whole day to shoot the videos you indicated to me and try to get some results for the panels of my interest.
Tomorrow I will surely ask you something... unless I solve everything myself (but I don't think so)

Alen

**Comment by mikhail-vl** [comment]
@acappelletti Looks like a plan! 👍

**Comment by acappelletti** [comment]
@mikhail-vl 
It is! 8 hours on your plugins tomorrow morning. I've already replaced the "text panel" with your "dynamic text" (the variable handling you developed was the first thought about the limitations of those in Grafana, TOP!).

**Comment by mikhail-vl** [comment]
@acappelletti I hope you are doing great. I believe the initial questions were answered and I am closing the issue.

  Please let us know if there is anything else.
