### ISSUE TITLE
Grafana query annotations (Vertical dashed lines ) not showing

### ISSUE THREAD

**Issue by giomilan** [VolkovLabs/volkovlabs-echarts-panel#90]
grafana query annotations (Vertical dashed lines ) that are displayed for standard grafana time series panels are not displayed for Echarts panels.

is there a solution or is not currently supported?

**Comment by mikhail-vl** [comment]
@giomilan Thank you for the suggestion. Annotations are not supported recently and were not requested before.

  We can look into adding Annotations support in the upcoming version.

**Comment by giomilan** [comment]
> @giomilan Thank you for the suggestion. Annotations are not supported recently and were not requested before.
> 
> We can look into adding Annotations support in the upcoming version.

understood - yes , thanks would be great and useful enhanchment in general for different contexts.

what about dynamic Grafana variables referencing - are they supported?  e.g. ${my_variable_value}

**Comment by AceSeanGG** [comment]
Grafana have a build in feature that allows you to generate annotation based on a query on all your panel 
since 2014 the community is asking to change this feature to impact a single panel 
i mean if i have a query that generate the anomaly based on cpu usage i don't want to display it in the other panels
(hope my example is clear enought)

@mikhail-vl do you think is possibile to add a section in the echart panel to generate annotation based on a query only in the specified panel?

**Comment by mikhail-vl** [comment]
@giomilan, Grafana variables are supported and can be referenced as ${my_variable_name} - we recently also added suggestions in the Monaco Code Editor and should be able to see them when typing.

  Let me know if it works for you.

**Comment by mikhail-vl** [comment]
@AceSeanGG If you have a query with anomalies, it's like any other data, you can display it with ECharts.

  ECharts supports various types and elements on the same chart. Should be easy to implement.

**Comment by AceSeanGG** [comment]
@mikhail-vl i was miss understood, 
Other than the classic query to display data in the panel grafana have a build in feature that generate in all you panel annotations based on a query result 

The downside of this feature is that effect all your panel 
An awesome feature in the echart panel could be add a section where based on a query it generate annotation in that specific panel.

In that scenario you have the query that return the data and the query that return the annotation both in a single panel 

Hope i was clear enough, 😅

**Comment by giomilan** [comment]
> @giomilan, Grafana variables are supported and can be referenced as ${my_variable_name} - we recently also added suggestions in the Monaco Code Editor and should be able to see them when typing.
> 
> Let me know if it works for you.

I see the variable hint popping up with the monaco code editor, but it doesnt seem to be get picked up by the markLine block...

basically the variable noww is the current time - and i want to show a vertical dashed line for the current time... (so it's basically a work around for the standard grafana annotation query) 
![image](https://user-images.githubusercontent.com/91971616/204831921-360ed13b-5035-47bf-8d07-b13511c5d973.png)

**Comment by mikhail-vl** [comment]
@giomilan Please take a look at the documentation: https://github.com/volkovlabs/volkovlabs-echarts-panel#dashboard-and-global-variables.

  Variables are not replaced automatically. You should use the `replaceVariables()` method from Grafana.
  Let us know if it works for you.

**Comment by mikhail-vl** [comment]
@AceSeanGG I think I got you. The way I am thinking of implementing Annotations for ECharts is to provide the parameter `annotations`, which has a list of annotations, and when creating a panel, you will need to display it yourself.

  There is no one way to implement annotations for all kinds of visualizations. Like @giomilan used `markLine` in his example for a variable, it can be done for all returned annotations.

  @giomilan Will it work for you?

**Comment by giomilan** [comment]
> @giomilan Please take a look at the documentation: https://github.com/volkovlabs/volkovlabs-echarts-panel#dashboard-and-global-variables.
> 
> Variables are not replaced automatically. You should use the `replaceVariables()` method from Grafana. Let us know if it works for you.

line 81 - still doesnt work (while line 80 works).

also in line 82 doesnt work - there i attempted to define the variable at the top 'now = replaceVariables('${now}')'

![image](https://user-images.githubusercontent.com/91971616/205015339-57a79578-ced7-40af-a867-7d4b2289fc79.png)

**Comment by AceSeanGG** [comment]
@giomilan replace line 81 to:
xAxis: replaceVariables('${__to}'),
this should be work

**Comment by giomilan** [comment]
> @giomilan replace line 81 to: xAxis: replaceVariables('${__to}'), this should be work
still doesnt work ... 
i've tried both 
xAxis: replaceVariables('${__to.now}') 
and xAxis: replaceVariables('${__now}')

seems like a bug?  cause e.g. name: replaceVariables('${now}') works on the markArea

**Comment by AceSeanGG** [comment]
> > @giomilan replace line 81 to: xAxis: replaceVariables('${__to}'), this should be work
> > still doesnt work ...
> > i've tried both
> > xAxis: replaceVariables('${__to.now}')
> > and xAxis: replaceVariables('${__now}')
> 
> seems like a bug? cause e.g. name: replaceVariables('${now}') works on the markArea

should be just _to not __to.now or __now.
try this exact sintax: 
xAxis: replaceVariables('${__to}'),

**Comment by giomilan** [comment]
> > > @giomilan replace line 81 to: xAxis: replaceVariables('${__to}'), this should be work
> > > still doesnt work ...
> > > i've tried both
> > > xAxis: replaceVariables('${__to.now}')
> > > and xAxis: replaceVariables('${__now}')
> > 
> > 
> > seems like a bug? cause e.g. name: replaceVariables('${now}') works on the markArea
> 
> should be just _to not __to.now or __now. try this exact sintax: xAxis: replaceVariables('${__to}'),

i dont undestand... my variable name in grafana is _now_  ... how would the panel know what to replace if i dont provide the variable name?!

**Comment by AceSeanGG** [comment]
your variable "now" return the current epoch Unix Timestamp?

**Comment by giomilan** [comment]
> your variable "now" return the current epoch Unix Timestamp?

it's a query-type variable from a postgress database - yh - it returns unix timestamp but it's not necessarely the current time - i'll have multiple of those...

**Comment by AceSeanGG** [comment]
> basically the variable noww is the current time - and i want to show a vertical dashed line for the current time... (so it's basically a work around for the standard grafana annotation query) so line 77 works properly but line 76 doesnt
>

if you want something that return the current time grafana provide some built-in variables: https://grafana.com/docs/grafana/v9.3/dashboards/variables/add-template-variables/

and the variable __to return the current time...

**Comment by giomilan** [comment]
> > basically the variable noww is the current time - and i want to show a vertical dashed line for the current time... (so it's basically a work around for the standard grafana annotation query) so line 77 works properly but line 76 doesnt
> 
> if you want something that return the current time grafana provide some built-in variables: https://grafana.com/docs/grafana/v9.3/dashboards/variables/add-template-variables/
> 
> and the variable __to return the current time...

thanks - but that's not what i need for the projects - i'd need that to support grafana query variables.

tho, it seems also the __to is not working - which makes me think of a bug/missing feature of the xAxis block within  markLine

**Comment by mikhail-vl** [comment]
@giomilan So you trying to draw `markLines` like in this example? https://echarts.volkovlabs.io/d/tg6gWiKVk/line?orgId=1&editPanel=13

  Looking at the example, xAxis is not a timestamp. I think it's the position of data:
```
markLine: {
        data: [
          {
            xAxis: 1
          },
          {
            xAxis: 3
          },
          {
            xAxis: 5
          },
          {
            xAxis: 7
          }
        ],
```

  All dashboards on https://echarts.volkovlabs.io allow Edit mode to experiment, so I updated `xAxis: 1` to `xAxis: 2` and can see how `markLine` moved forward.

  Based on that, you should create a special query or process results in a function to get an array of positions in the dataset based on the timestamp and use it for markLine's data.

  Let me know if you make it work.

**Comment by giomilan** [comment]
> @giomilan So you trying to draw `markLines` like in this example? https://echarts.volkovlabs.io/d/tg6gWiKVk/line?orgId=1&editPanel=13
> 
> Looking at the example, xAxis is not a timestamp. I think it's the position in the dataset:
> 
> ```
> markLine: {
>         data: [
>           {
>             xAxis: 1
>           },
>           {
>             xAxis: 3
>           },
>           {
>             xAxis: 5
>           },
>           {
>             xAxis: 7
>           }
>         ],
> ```
> 
> All dashboards on https://echarts.volkovlabs.io allow Edit mode to experiment, so I updated `xAxis: 1` to `xAxis: 2` and can see how `markLine` moved forward.
> 
> Based on that, you should create a special query or process results in a function to get an array of positions in the dataset based on the timestamp and use it for markLine's data.
> 
> Let me know if you make it work.

thanks for sharing the dashboard.

see my test below - unfortunately i cannot seem to make it work with the replaceVariables... see the missing vertical line which instead work fine if i use the line 2 (instead of 1)


![image](https://user-images.githubusercontent.com/91971616/205104308-4442f83f-9c11-4451-ac92-0453119f97a7.png)

**Comment by mikhail-vl** [comment]
@giomilan I see what the issue is `string vs. number`. Variables are strings and need to be converted to numbers.

Works for me:
![Screen Shot 2022-12-01 at 14 31 50](https://user-images.githubusercontent.com/47795110/205143181-4cd25b95-2db4-439e-9cc0-ce81d26c7cf1.png)

If it follows the UNIX timestamp, then it should be easier. Please share if it works for you.

**Comment by giomilan** [comment]
> @giomilan I see what the issue is `string vs. number`. Variables are strings and need to be converted to numbers.
> 
> Works for me: ![Screen Shot 2022-12-01 at 14 31 50](https://user-images.githubusercontent.com/47795110/205143181-4cd25b95-2db4-439e-9cc0-ce81d26c7cf1.png)
> 
> If it follows the UNIX timestamp, then it should be easier. Please share if it works for you.

it works for me as well now - thanks a lot for your support @mikhail-vl

**Comment by mikhail-vl** [comment]
@giomilan Thank you for confirming. I will try to look into adding annotations later this week.

**Comment by giomilan** [comment]
> > @giomilan Thank you for confirming. I will try to look into adding annotations later this week.
> 
> the only thing missing to make this work around fully equivalent to the grafana annotations is the possibility to specify the colour of the vertical lines if multiples are present - with markLine it seems currently they will all have the same colour.
> 
> so I guess adding the annotations is still relevant - thanks a lot for your support

not true - my bad - it is possible - see below - so i managed to achieve the exact same results as annotations using variables and markLine

![image](https://user-images.githubusercontent.com/91971616/205276222-0239e11e-2a30-4156-aeee-f3666eef82ac.png)

**Comment by mikhail-vl** [comment]
@giomilan That's really cool. Thank you for sharing.

  We will include it in the documentation with annotations.

**Comment by mikhail-vl** [comment]
We updated the documentation and added annotations support in Apache ECharts 4.3.0: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/annotations/
