### ISSUE TITLE
Does the community need Gaode maps or Google Maps? 

### ISSUE THREAD

**Issue by X-Mars** [VolkovLabs/volkovlabs-echarts-panel#94]
Hi , there.
    Does the community need Gaode maps or Google Maps?  Maybe I can help.

**Comment by X-Mars** [comment]
Add Gaode map support
PR https://github.com/VolkovLabs/volkovlabs-echarts-panel/pull/95

**Comment by X-Mars** [comment]
![image](https://user-images.githubusercontent.com/18095822/205321291-5e67e519-7041-46f9-bd04-3017af12acd3.png)

**Comment by mikhail-vl** [comment]
@X-Mars I was looking to add Google Maps, which was updated recently.

  I am not familiar with Gaode maps but gladly accept pull requests.

**Comment by mikhail-vl** [comment]
@X-Mars Thank you, Gaode maps merged.

  You are welcome to submit PR for Google maps based on the `main` branch, which I just updated to Grafana 8.3.1.

**Comment by X-Mars** [comment]
@mikhail-vl Hi, no thanks
PR for Google Map https://github.com/VolkovLabs/volkovlabs-echarts-panel/pull/98
May be these codes have some bugs, because I can't use Google Maps very well in China.

**Comment by X-Mars** [comment]
![image](https://user-images.githubusercontent.com/18095822/205474830-383e60b7-d34a-4a70-83ba-bd3a3729e748.png)

**Comment by mikhail-vl** [comment]
Resolved in #95 and #98.

**Comment by mikhail-vl** [comment]
Looks awesome! 

![Screen Shot 2022-12-04 at 07 35 11](https://user-images.githubusercontent.com/47795110/205491527-e4a5f2b4-7a89-46cb-8e45-d8f379ba63e5.png)

**Comment by X-Mars** [comment]
Yes, we finished them, great!

**Comment by X-Mars** [comment]
@mikhail-vl It's my pleasure, waiting for new version and YouTube video.
Have a nice day.
