### ISSUE TITLE
Get last values from InfluxDB into a variable

### ISSUE THREAD

**Issue by na-am** [VolkovLabs/volkovlabs-echarts-panel#96]
hi@all

how can i put values into a const to use it later in 
`const gaugeData = [
  {
    value: t,
    name:  'Temp',`

my Influx query: SELECT last("Temp") as "temp" FROM "elsys-uno"

`const t = series[0].values[1]`
is not working

thx
na-am

**Comment by mikhail-vl** [comment]
@na-am We explained how to work with data sources in the YouTube videos: https://youtu.be/K5YNMSIm9AM and README https://github.com/volkovlabs/volkovlabs-echarts-panel#data-sources

  Also, check out the default example in the Panel. It has the logic to get time and value from the returned data source.
  Let us know if there is anything else.

**Comment by mikhail-vl** [comment]
@na-am Please let me know if it's clear or there is something else.
